site/_docs/compression.md
site/_docs/encodings.md
site/_docs/file-tail.md

Here are the fixes for the documentation that should address Dain's comments.

Fix the documentation issues that Dain brought up.

---

java/pom.xml
java/tools/pom.xml
java/tools/src/java/org/apache/orc/tools/Driver.java
java/tools/src/java/org/apache/orc/tools/convert/ConvertTool.java
java/tools/src/java/org/apache/orc/tools/convert/CsvReader.java
java/tools/src/java/org/apache/orc/tools/convert/JsonReader.java
java/tools/src/java/org/apache/orc/tools/json/JsonSchemaFinder.java
java/tools/src/test/org/apache/orc/tools/convert/TestCsvReader.java

This patch incorporates Carter's converter into the tool jar. I haven't made any tests yet.

ORC-199. Add convert from CSV.

---

java/pom.xml

ORC-240. Fix maven pom file warnings

---

java/core/src/java/org/apache/orc/UnknownFormatException.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

Signed-off-by: Owen O'Malley <omalley@apache.org>

ORC-241. Make an unknown file format an exception.

---

java/core/src/java/org/apache/orc/impl/BitFieldReader.java
java/core/src/test/org/apache/orc/impl/TestBitFieldReader.java

Fix #272
Signed-off-by: Owen O'Malley <omalley@apache.org>

ORC-367: Fix incorrect reads of boolean columns after a seek.

---

java/tools/src/java/org/apache/orc/tools/convert/JsonReader.java

Add `MapColumnConverter` to support converting JSON object to MAP type.
Since JSON keys can only be strings, we only support MAP type with string keys.

ORC-452: Support converting JSON object to MAP type

---

java/core/src/java/org/apache/orc/OrcUtils.java
java/core/src/java/org/apache/orc/impl/SchemaEvolution.java
java/core/src/test/org/apache/orc/util/TestOrcUtils.java

(cherry picked from commit 325d5829bce50d725214227325061537fe5aaa79)

ORC-477: BloomFilter for ACID table does not get created

---

java/core/src/java/org/apache/orc/TypeDescription.java
java/core/src/test/org/apache/orc/TestTypeDescription.java

Pull request to backport ORC-491 to branch-1.5
cc @prasanthj

ORC-491: PPD Column name lookups need to look a struct deeper for ACID

---

c++/src/ColumnReader.cc

skip() function is the StringDirectColumnReader and DoubleColumnReader use size_t to compute total size to skip; however, the value is casted to int when calling underlying input stream.

ORC-496: [C++] Fix integer overflow in skip of column reader

---

proto/orc_proto.proto
site/specification/ORCv1.md
site/specification/ORCv2.md

Updates the protobuf and the v1 spec for column encryption. 
After this gets approved, I'll update the v2 spec.

ORC-483 Update protobuf for column encryption.

---

java/tools/src/java/org/apache/orc/tools/convert/ConvertTool.java
java/tools/src/java/org/apache/orc/tools/convert/JsonReader.java

This is my first pull-request at ASF project.
If you have anything, please let me know.

ORC-455: Support timestampformat option in JsonReader

---

java/core/src/java/org/apache/orc/impl/SchemaEvolution.java

fix [ORC-649](https://issues.apache.org/jira/browse/ORC-649)

ORC-649: Remove duplicate buildConversion invocation

---

cmake_modules/ThirdpartyToolchain.cmake

This PR aims to upgrade ZSTD from 1.3.5 to 1.4.5.
This will bring the latest improvements and bug fixes.
- https://github.com/facebook/zstd/releases/tag/v1.4.5
- https://github.com/facebook/zstd/releases/tag/v1.4.4
- https://github.com/facebook/zstd/releases/tag/v1.4.3
- https://github.com/facebook/zstd/releases/tag/v1.4.2
- https://github.com/facebook/zstd/releases/tag/v1.4.1
- https://github.com/facebook/zstd/releases/tag/v1.4.0
- https://github.com/facebook/zstd/releases/tag/v1.3.8
- https://github.com/facebook/zstd/releases/tag/v1.3.7
- https://github.com/facebook/zstd/releases/tag/v1.3.6
Pass the CIs.

ORC-652: Upgrade ZSTD to 1.4.5

---

java/bench/README.md
java/bench/hive/pom.xml
java/bench/hive/src/java/org/apache/orc/bench/hive/RowFilterProjectionBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/BooleanRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/DecimalRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/DoubleRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/StringRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/TimestampRowFilterBenchmark.java
java/bench/pom.xml

Extending orc benchmark to support row-level filtering using existing datasets
To compare the result between versions.
Run the benchmark.

ORC-597: Add Row-level filtering benchmark

---

c++/src/Compression.cc

This PR aims to improve ZSTD performance in branch-1.6. This is a backport of #511
Zstd's "Simple API" is used which initializes the compression/decompression context each time. This includes time to initialize all compression/decompression tables. Using the "Explicit context" API improves the performance significantly as compression/decompression tables are constructed once and reused each time "decompress" or "doBlockCompression" is called. We've noticed more than 15% time improvement in some applications with this change, so it seems that any ORC user using Zstd can benefit from this change.
Pass the UT

ORC-639: Improve zstd performance

---

java/pom.xml

This PR aims to upgrade JUnit from 4.12 to 4.13.1
This will bring the bug fixes in JUnit 4.x line.
- https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.12.md
- https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.md
- https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.1.md
Pass the CI with the existing UTs.

ORC-678: Upgrade JUnit to 4.13.1

---

java/pom.xml

Upgrade commons-codec to version 1.15.
This will bring the latest bug fixes. 
Pass the CI.

ORC-681: Upgrade commons-codec to 1.15

---

java/core/pom.xml
java/mapreduce/pom.xml
java/pom.xml
java/tools/pom.xml

Upgrade to commons-lang3. 
This will bring the latest bug fixes. 
Pass the CI.

ORC-682: Upgrade to commons-lang3 3.11

---

java/mvnw
java/pom.xml

This PR aims to add `Maven Wrapper`.
This will help ORC build and testing at the environment without Maven installation.
Manual.
```
cd java
./mvnw clean
```
This closes #454

ORC-503. Add Maven Wrapper

---

java/core/pom.xml
java/mapreduce/pom.xml
java/pom.xml
java/shims/pom.xml
java/tools/pom.xml

This PR aims to upgrade JUnit from JUnit4 to JUnit5.
This is a stepping stone for migrating to JUnit5. 
Pass the CIs.

ORC-687. Upgrade to JUnit5

---

.github/workflows/publish_snapshot.yml

This PR updates the credentials according to the direction of https://issues.apache.org/jira/browse/INFRA-21150 .
To publish snapshot.
N/A (The snapshot publish job is triggered at commit only).

ORC-693: Update credential according to INFRA setup

---

c++/src/wrap/orc-proto-wrapper.cc
docker/README.md
docker/centos7/Dockerfile
docker/centos8/Dockerfile
docker/debian10/Dockerfile
docker/debian8/Dockerfile
docker/debian9/Dockerfile
docker/os-list.txt
docker/ubuntu14/Dockerfile
docker/ubuntu16/Dockerfile
docker/ubuntu18/Dockerfile
docker/ubuntu20-clang/Dockerfile
docker/ubuntu20/Dockerfile
site/_docs/building.md

- added docker files for ubuntu 20 with and without clang
- remove debian 8, and ubuntu 14
(cherry picked from commit 7275ceb8cce0a7316daa357e632fcf4bb21501c8)

ORC-674: Update docker files

---

java/core/src/java/org/apache/orc/impl/mask/SHA256MaskFactory.java
java/pom.xml

This PR aims to enable Checkstyle plugin and FileTabCharacter rule.
This will be helpful to improve code quality. 
It would be great if we could enable this in GitHub action.
Manual
```
mvn checkstyle:check
```

ORC-718: Enable Checkstyle plugin and FileTabCharacter rule.

---

README.md

This PR aims to update Java version to 8 in README.md.
Since ORC-399, Java 8 is used.
N/A

MINOR: Update Java version to 8 in README.md.

---

.github/workflows/build_and_test.yml

This PR aims to add Java 15 to GitHub action as a preparation for Java 17.
Java 17 is the next LTS.
Pass the GitHub action.

ORC-713: Add Java 15 to GitHub action

---

proto/orc_proto.proto

This PR aims to add a writer version for Trino.
Trino writer is different from Presto writer.
N/A

ORC-748: Add separate writer implementation for Trino

---

README.md

Broken link
Fix master build status badge
Grip locally

ORC-752: FIX Master branch build badge

---

java/bench/core/pom.xml
java/core/src/java/org/apache/orc/impl/OrcAcidUtils.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/java/org/apache/orc/impl/RecordReaderUtils.java
java/core/src/java/org/apache/orc/impl/TreeReaderFactory.java
java/core/src/java/org/apache/orc/impl/reader/StripePlanner.java

* Removal of group name in bench pom.xml
* Replaced Charset.forName with StandardCharsets
* Final on some variables
* Removed final on a private method
* Simplified some conditions
* Removed redundant casts
* Removed duplicate condition branches
Code cleanup
As this does not change any of the existing functionality. It was verified that none of the existing tests break.

ORC-754: Code cleanup

---

java/bench/pom.xml

This PR aims to update Spark to 3.1.1. 
Apache Spark 3.1.1 is the first official release in the 3.1 line. 
Pass the CIs.

ORC-760: Update Spark to 3.1.1

---

docker/centos7/Dockerfile
docker/centos8/Dockerfile
docker/debian10/Dockerfile
docker/debian9/Dockerfile
docker/ubuntu16/Dockerfile
docker/ubuntu18/Dockerfile
docker/ubuntu20-clang/Dockerfile
docker/ubuntu20/Dockerfile
site/Dockerfile

- Replace MAINTAINER command with LABEL command.
MAINTAINER command is deprecated since docker 1.13 or later. 
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
- Confirmed that `Dockerfile`s are built successfully with `reinit.sh`

ORC-761: Replace MAINTAINER command with LABEL command

---

java/bench/pom.xml
java/pom.xml

This PR aims to update commons-csv to version 1.8.
This will bring the latest bug fixes and improvements. 
- https://commons.apache.org/proper/commons-csv/changes-report.html#a1.8
- https://commons.apache.org/proper/commons-csv/changes-report.html#a1.7
- https://commons.apache.org/proper/commons-csv/changes-report.html#a1.6
- https://commons.apache.org/proper/commons-csv/changes-report.html#a1.5
Pass the CIs.

ORC-768: Update commons-csv to 1.8

---

java/core/src/test/org/apache/orc/TestVectorOrcFile.java

ORC-763 has a long discussion about the sql.Timestamp bug and how ORC goes around it.
This ticket introduces a Test to ensure consistency with the expected behaviour – as we have on C++ side of things.
TestVectorOrcFile.testTimestampBug

ORC-771: ORC timestamp consistency Test for sql.Timestamps close to epoch

---

java/pom.xml

This PR aims to include `source` jars at snapshots. We need this patch for all branches (master/branch-1.6/branch-1.5).
- https://repository.apache.org/content/repositories/snapshots/org/apache/orc/orc-core/
Currently, snapshot artifacts doesn't have source jars while the release artifacts have them.
`source` jars are crucial during debugging with snapshot jars.
Manually.
**BEFORE**
```
$ mvn install -DskipTests
$ ls -al ~/.m2/repository/org/apache/orc/orc-core/1.7.0-SNAPSHOT
total 2800
drwxrwxr-x 2 dongjoon dongjoon    4096 Mar 27 18:59 .
drwxrwxr-x 3 dongjoon dongjoon    4096 Mar 27 18:59 ..
-rw-rw-r-- 1 dongjoon dongjoon     912 Mar 27 18:59 maven-metadata-local.xml
-rw-rw-r-- 1 dongjoon dongjoon 1029565 Mar 27 18:59 orc-core-1.7.0-SNAPSHOT.jar
-rw-rw-r-- 1 dongjoon dongjoon 1808265 …
```

ORC-776: Include source jars during publishing snapshot

---

java/pom.xml

This PR aims to upgrade commons-cli to 1.4
This will bring the latest bug fixes and improvements.
- http://commons.apache.org/proper/commons-cli/release_1_4.html 
Pass the CIs.

ORC-779: Upgrade commons-cli to 1.4

---

site/develop/committers.md

This PR aims to add `William Hyun` to the committers.md file. 
N/A
N/A

MINOR: Add William Hyun to committers.md

---

docker/README.md
docker/centos7/Dockerfile
docker/centos8/Dockerfile
docker/debian10/Dockerfile
docker/debian9/Dockerfile
docker/ubuntu16/Dockerfile
docker/ubuntu18/Dockerfile
docker/ubuntu20/Dockerfile

Update Docker files to use `main` branch
Change needed after INFRA-21723
Manually run Docker file

ORC-786: Update Dockerfiles to use `main` branch

---

site/.htaccess
site/README.md
site/_docs/building.md
site/develop/index.md
site/develop/make-release.md
site/help/index.md

Update site to use `main`
Change needed after INFRA-21723
Locally build and run site

ORC-787: Update site to use `main`

---

README.md

Update documentation to mention the specific version of Maven required and provide usage of `mvnw` wrapper script
Provide accurate build information for new developers.
Documentation-only change

ORC-802: Document Maven Version and mvnw

---

java/core/src/java/org/apache/orc/impl/MemoryManagerImpl.java

Within the class MemoryManagerImpl, removing a writer can be simplified down to a single Map interaction.
Change reduces code size and allows the Map to be scanned only one time instead of twice (in some scenarios).
Existing unit tests

ORC-803: MemoryManagerImpl Simplify removeWriter

---

site/specification/ORCv1.md
site/specification/ORCv2.md

This PR aims to add TIMESTAMP_INSTANT to the ORC specs documents.
This will make the specs document up to date before the 1.7.0 release. 
N/A

ORC-809: Add TIMESTAMP_INSTANT to ORC specs

---

.github/labeler.yml
.github/workflows/labeler.yml

This PR aims to add GitHub labeler. 
This assists the reviewer to categorize and find the PRs easily.  
N/A.

ORC-819: Add GitHub labeler

---

.github/workflows/build_and_test.yml

This PR aims to add Java 17 to GitHub action. 
To improve test coverage. 
Pass the CIs.

ORC-716: Add Java 17 to GitHub action

---

c++/include/orc/Statistics.hh
c++/src/ColumnWriter.cc
c++/src/Statistics.cc
c++/src/Statistics.hh
c++/test/TestColumnStatistics.cc

add the collection column statistics ut.

ORC-824:[C++] Add column statistics for List and Map

---

java/core/src/java/org/apache/orc/impl/SerializationUtils.java

Optimize Serialization percentileBits method
Speed and simplicity
Existing unit tests, no functionality changes.

ORC-829: Optimize Serialization percentileBits

---

java/core/src/java/org/apache/orc/impl/DynamicIntArray.java
java/core/src/test/org/apache/orc/impl/TestDynamicArray.java

Fix NPE in `DynamicIntArray` toString method.
Restore helpful when debugging.
No changes to functionality. Added unit test covering empty list.

ORC-845: Fix NPE in DynamicIntArray toString

---

java/bench/core/src/java/org/apache/orc/bench/core/convert/GenerateVariants.java

Add additional output. Code cleanup.
Adding this logging helped me identify an error condition.
This is benchmark code. No change in functionality. Use existing unit tests.

ORC-849: Core Benchmark Cleanup

---

java/core/src/java/org/apache/orc/TypeDescription.java
java/core/src/java/org/apache/orc/impl/ColumnStatisticsImpl.java
java/core/src/java/org/apache/orc/impl/MaskDescriptionImpl.java
java/core/src/java/org/apache/orc/util/BloomFilter.java
java/mapreduce/src/java/org/apache/orc/mapred/OrcStruct.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcStruct.java

Auto-generate some hashCode methods.
Better hash code values for better distributions; less code.
No changes to functionality. Use existing unit tests.

ORC-844: Improve hashCode Methods

---

java/tools/pom.xml

This PR aims to fix CNFE in ORC tools uber jar. 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
at org.apache.orc.tools.Driver.main(Driver.java:101)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 1 more
```
Manual.

ORC-851: Fix CNFE in ORC tools uber jar

---

java/core/src/java/org/apache/orc/impl/ParserUtils.java

Fix the exception description in the findSubtype method
Avoid misleading exception output
N/A

ORC-856: Fix exception description in findSubtype

---

java/core/src/java/org/apache/orc/impl/DataReaderProperties.java
java/core/src/java/org/apache/orc/impl/RunLengthIntegerReaderV2.java
java/core/src/java/org/apache/orc/impl/TreeReaderFactory.java
java/pom.xml
java/tools/src/java/org/apache/orc/tools/convert/JsonReader.java

This PR aims to add NoLineWrap, OneStatementPerLine, NeedBraces checkstyle rules. 
This will improve code quality. 
Pass the GHA.

ORC-858: Add NoLineWrap/OneStatementPerLine/NeedBraces checkstyle rules

---

.travis.yml

This PR aims to upgrade TravisCI from xenial to focal. 
Ubuntu 16 (Xenial) is dropped from ORC. 
Pass the TravisCI.

ORC-863: Upgrade TravisCI from xenial to focal

---

java/examples/pom.xml

run orc-example, Throw an exception
```log
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
at java.lang.Class.getMethod0(Class.java:3018)
at java.lang.Class.getMethod(Class.java:1784)
at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at …
```

ORC-902: Fix hadoop-common  dependency scope in orc-example

---

java/bench/pom.xml
java/core/pom.xml
java/examples/pom.xml
java/pom.xml
java/tools/pom.xml

This PR aims to enforce maven-dependency-plugin. 
This will prevent unintended dependency changes. 
Pass the CIs and check the CI log.

ORC-910: Enforce maven-dependency-plugin

---

java/CMakeLists.txt

This PR aims to add integration tests for Java `tools` and `examples`
To prevent the future regressions. 
Pass the CIs.

ORC-886,ORC-905: Add integration tests for Java tools/examples

---

java/core/src/java/org/apache/orc/impl/ColumnStatisticsImpl.java
java/core/src/java/org/apache/orc/impl/RunLengthIntegerWriterV2.java
java/core/src/java/org/apache/orc/impl/writer/TreeWriterBase.java

This PR aims to remove redundant conditional statements. 
This will improve code quality. 
Pass the CIs.

ORC-922: Remove redundant conditional statements

---

java/bench/core/src/java/org/apache/hadoop/fs/TrackingLocalFileSystem.java
java/bench/core/src/java/org/apache/orc/bench/core/RandomGenerator.java
java/bench/core/src/java/org/apache/orc/bench/core/SalesGenerator.java
java/bench/core/src/java/org/apache/orc/bench/core/convert/json/JsonReader.java
java/core/src/java/org/apache/orc/InMemoryKeystore.java
java/core/src/java/org/apache/orc/impl/DirectDecompressionCodec.java
java/core/src/java/org/apache/orc/impl/InStream.java
java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/java/org/apache/orc/impl/RecordReaderUtils.java
java/core/src/java/org/apache/orc/impl/RedBlackTree.java
java/core/src/java/org/apache/orc/impl/RunLengthIntegerReaderV2.java
java/core/src/java/org/apache/orc/impl/SerializationUtils.java
java/mapreduce/src/java/org/apache/orc/mapred/OrcInputFormat.java
java/pom.xml
java/shims/src/java/org/apache/orc/impl/ZeroCopyShims.java
java/tools/src/java/org/apache/orc/tools/convert/JsonReader.java
java/tools/src/java/org/apache/orc/tools/json/ListType.java
java/tools/src/java/org/apache/orc/tools/json/StructType.java

This PR aims to add redundant modifier and modifier order checkstyle rules.
This will improve code quality removing inconsistent patterns. 
Pass the CIs.

ORC-924: Add redundant modifier/modifier order checkstyle rules

---

java/core/src/findbugs/exclude.xml
java/core/src/test/org/apache/orc/TestColumnStatistics.java
java/core/src/test/org/apache/orc/TestNewIntegerEncoding.java
java/core/src/test/org/apache/orc/TestOrcNullOptimization.java
java/core/src/test/org/apache/orc/TestOrcTimezone1.java
java/core/src/test/org/apache/orc/TestProlepticConversions.java
java/core/src/test/org/apache/orc/TestRowFilteringSkip.java
java/core/src/test/org/apache/orc/TestStringDictionary.java
java/core/src/test/org/apache/orc/TestTypeDescription.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java
java/core/src/test/org/apache/orc/impl/TestColumnStatisticsImpl.java
java/core/src/test/org/apache/orc/impl/TestCryptoUtils.java
java/core/src/test/org/apache/orc/impl/TestOutStream.java
java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java
java/core/src/test/org/apache/orc/impl/TestSchemaEvolution.java
java/core/src/test/org/apache/orc/impl/TestSerializationUtils.java
java/core/src/test/org/apache/orc/impl/TestStreamName.java
java/core/src/test/org/apache/orc/impl/TestZlib.java
java/core/src/test/org/apache/orc/impl/TestZstd.java
java/core/src/test/org/apache/orc/impl/mask/TestDataMask.java
java/core/src/test/org/apache/orc/util/TestBloomFilter.java
java/core/src/test/org/apache/orc/util/TestOrcUtils.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcOutputFormat.java
java/mapreduce/src/test/org/apache/orc/mapreduce/TestMapreduceOrcOutputFormat.java
java/tools/src/test/org/apache/orc/impl/TestHadoopKeyProvider.java
java/tools/src/test/org/apache/orc/impl/TestRLEv2.java
java/tools/src/test/org/apache/orc/tools/TestFileDump.java
java/tools/src/test/org/apache/orc/tools/convert/TestCsvReader.java
java/tools/src/test/org/apache/orc/tools/convert/TestJsonReader.java

This PR aims to simplify assertion statements in test code. 
This will improve overall code quality. 
Pass the Cis.

ORC-925: Simplify Assertions

---

java/CMakeLists.txt

This PR aims to add integration tests for Java bench. 
To prevent further regressions. 
Pass the CIs.

ORC-934: Add integration tests for Java bench

---

java/.idea/vcs.xml

This PR aims to add IntelliJ conf to support JIRA/PR autolinks. 
This will help IntelliJ users a lot. 
N/A.

ORC-943: Add IntelliJ conf to support JIRA/PR autolinks

---

java/pom.xml

This PR aims to add the `RedundantImport` checkstyle rule.
This will ensure no redundant imports. 
Pass the Cis.

ORC-944: Add RedundantImport checkstyle rule

---

java/bench/hive/src/java/org/apache/orc/bench/hive/RowFilterProjectionBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/RowFilterInputState.java
java/bench/spark/src/java/org/apache/orc/bench/spark/SparkBenchmark.java
java/core/src/java/org/apache/orc/OrcConf.java
java/core/src/java/org/apache/orc/Reader.java
java/core/src/java/org/apache/orc/impl/BitFieldReader.java
java/core/src/java/org/apache/orc/impl/BufferChunk.java
java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java
java/core/src/java/org/apache/orc/impl/DataReaderProperties.java
java/core/src/java/org/apache/orc/impl/DateUtils.java
java/core/src/java/org/apache/orc/impl/InStream.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/java/org/apache/orc/impl/TreeReaderFactory.java
java/core/src/java/org/apache/orc/impl/WriterImpl.java
java/core/src/java/org/apache/orc/impl/filter/leaf/LeafFilterFactory.java
java/core/src/java/org/apache/orc/impl/reader/StripePlanner.java
java/core/src/java/org/apache/orc/impl/reader/tree/BatchReader.java
java/core/src/java/org/apache/orc/impl/reader/tree/PrimitiveBatchReader.java
java/core/src/java/org/apache/orc/impl/reader/tree/StructBatchReader.java
java/core/src/java/org/apache/orc/impl/writer/TreeWriterBase.java
java/core/src/java/org/apache/orc/util/BloomFilter.java
java/core/src/java/org/threeten/extra/chrono/HybridChronology.java
java/pom.xml
java/tools/src/java/org/apache/orc/tools/RowCount.java
java/tools/src/java/org/apache/orc/tools/convert/ConvertTool.java
site/develop/coding.md

This PR aims to update the ORC Java coding guide to max line length 100 and enforce it.
Our coding guideline is outdated in terms of the max line length.
We had better make it consistent in our website and codebase.
Pass the CIs.

ORC-947: Update coding guide to max line length 100 and enforce it

---

java/bench/core/pom.xml
java/bench/core/src/java/org/apache/orc/bench/core/convert/json/JsonWriter.java
java/pom.xml
java/tools/pom.xml
java/tools/src/java/org/apache/orc/tools/JsonFileDump.java
java/tools/src/java/org/apache/orc/tools/KeyTool.java
java/tools/src/java/org/apache/orc/tools/PrintData.java
java/tools/src/test/org/apache/orc/tools/TestFileDump.java
java/tools/src/test/resources/orc-file-dump.json

The java project depends on several json libraries. Replacing jackson/jettison with Gson 
```
use jackson-core in orc-benchmarks-core
org.apache.orc.bench.core.convert.json.JsonWriter
use jettison in tools
org.apache.orc.tools.KeyTool
org.apache.orc.tools.JsonFileDump
org.apache.orc.tools.PrintData
```
gson vs. jettison has some inconsistent
1.  the scope of character escaping is inconsistent; 
jettison escapes '/'
gson does not modify
2. Inconsistent floating point writing; 
jettison removes trailing zeros and decimal points where possible. 
gson leaves it as is.
3. prettyPrint;
jettison's prettyPrint is faulty, '[' and '{' are often linked together without a line break. 
gson prettyPrint is fine.
These three behaviours are not forward compatible in this pr.
I don't think prettyPrint …

ORC-946: Unified json library

---

java/tools/src/java/org/apache/orc/tools/convert/ConvertTool.java
java/tools/src/java/org/apache/orc/tools/json/JsonSchemaFinder.java

Catching exceptions and printing messages.
1. Special prompt for empty file
2. Prompt for which file is being processed
3. Prompt for which record is being processed
Provide more valid information.
Pass the CIs.

ORC-871: Provide better error information when parsing json files with exceptions

---

java/tools/src/java/org/apache/orc/tools/json/HiveType.java
java/tools/src/java/org/apache/orc/tools/json/JsonSchemaFinder.java
java/tools/src/java/org/apache/orc/tools/json/MapType.java
java/tools/src/test/org/apache/orc/tools/json/TestJsonSchemaFinder.java

Implement MapType to support multiple ORC files for convert.
Feature Improvement.
Added testMapMerges unit test.

ORC-726: Support Map type in `orc-tools convert`

---

java/tools/src/java/org/apache/orc/tools/convert/ConvertTool.java

Make the convert command support the overwrite option.
You can overwrite old files when you convert multiple times.
Pass the CIs.

ORC-958: Convert command support overwrite option

---

java/core/src/java/org/apache/orc/impl/WriterImpl.java

Reordered multiple statements. Make variable initialization and usage closer. 
For example, before
```
193  buildIndex = rowIndexStride > 0;
216  if (buildIndex && rowIndexStride < MIN_ROW_INDEX_STRIDE) {
```
Put the heavy logic last and put the check logic first.
The create physicalWriter and treeWriter statements are placed at the end of constructor.
Clearer logic and improved readability.
Pass the CIs.

ORC-970: Reordering statements, improve readability

---

c++/src/RleEncoderV2.cc
java/core/src/java/org/apache/orc/impl/RunLengthIntegerWriterV2.java

```java
private void computeZigZagLiterals() {
// populate zigzag encoded literals
long zzEncVal = 0;
for (int i = 0; i < numLiterals; i++) {
if (signed) {
zzEncVal = utils.zigzagEncode(literals[i]);
} else {
zzEncVal = literals[i];
}
zigzagLiterals[i] = zzEncVal;
}
}
```
Avoid conditional judgments in loops. 
The unsigned case can use literals instead of zigzagLiterals. 
optimize write performance.
Pass the CIs.

ORC-976: Optimize compute zigzagliterals

---

java/core/src/java/org/apache/orc/impl/SerializationUtils.java

```
310  int idx = encodeBitWidth(findClosestNumBits(data[i]));
```
```
public int encodeBitWidth(int n) {
n = getClosestFixedBits(n);
.....
}
```
```
public int findClosestNumBits(long value) {
final int numBits = 64 - Long.numberOfLeadingZeros(value);
return getClosestFixedBits(numBits);
}
```
getClosestFixedBits is called twice.
Extracts the new method findNumBits from findClosestNumBits. Avoid double counting closestFixedBits.
Avoid redundant calls.
Pass the CIs.

ORC-975: Avoid double counting closestFixedBits

---

java/bench/core/pom.xml
java/bench/core/src/findbugs/exclude.xml
java/bench/core/src/java/org/apache/orc/bench/core/filter/FilterBench.java
java/bench/core/src/java/org/apache/orc/bench/core/filter/FilterBenchUtil.java
java/bench/core/src/java/org/apache/orc/impl/filter/RowFilter.java
java/bench/core/src/java/org/apache/orc/impl/filter/RowFilterFactory.java
java/bench/core/src/test/org/apache/orc/bench/core/filter/TestFilter.java
java/bench/core/src/test/org/apache/orc/impl/filter/ATestFilter.java
java/bench/core/src/test/org/apache/orc/impl/filter/TestRowFilter.java
java/bench/hive/src/assembly/uber.xml
java/bench/pom.xml
site/develop/design/lazy_filter.md

Includes Benchmark tests and Documentation for ORC-742 and ORC-743
Benchmarks show the benefits of adding LazyIO during reads and the documentation explains the design of the same.
There is no new functionality added here so the regression tests were run and the benchmark tests were completed to verify the improvements.

ORC-811 Benchmarks and documentation for ORC-742 and ORC-743

---

site/_docs/java-tools.md

Update `Java Tools` documentation.
Added description of count / key / version.
Commands and parameters are listed in order.
Fix the problem that the page does not display parameters.
To make it easier for users to use java-tool.
No need to test.

ORC-727: Update `Java Tools` documentation

---

java/bench/core/src/java/org/apache/orc/bench/core/CompressionKind.java
java/bench/hive/src/java/org/apache/orc/bench/hive/DecimalBench.java
java/core/src/java/org/apache/orc/DataMask.java
java/core/src/java/org/apache/orc/OrcFile.java
java/core/src/java/org/apache/orc/PhysicalWriter.java
java/core/src/java/org/apache/orc/Reader.java
java/core/src/java/org/apache/orc/RecordReader.java
java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java
java/core/src/java/org/apache/orc/impl/RecordReaderUtils.java
java/core/src/java/org/apache/orc/impl/RedBlackTree.java
java/core/src/java/org/apache/orc/impl/SchemaEvolution.java
java/core/src/java/org/apache/orc/impl/mask/RedactMaskFactory.java
java/core/src/java/org/apache/orc/impl/writer/TreeWriter.java
java/core/src/test/org/apache/orc/TestRowFilteringNoSkip.java
java/core/src/test/org/apache/orc/TestRowFilteringSkip.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcOutputFormat.java
java/tools/src/java/org/apache/orc/tools/json/HiveType.java
java/tools/src/test/org/apache/orc/impl/FakeKeyProvider.java

This PR aims to fix a typos in project.
Easy to read
Pass the CIs.

MINOR: Fix typos in project

---

java/core/src/java/org/apache/orc/InMemoryKeystore.java
java/core/src/java/org/apache/orc/OrcFile.java
java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java
java/core/src/java/org/apache/orc/impl/InStream.java
java/core/src/java/org/apache/orc/impl/IntegerReader.java
java/core/src/java/org/apache/orc/impl/writer/CharTreeWriter.java
java/pom.xml

This PR aims to add the `CommentsIndentation` checkstyle rule
This will fix misaligned comments and enforce it.
Pass the CIs.

ORC-981: Add `CommentsIndentation` checkstyle rule

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java

Couple of the log statements related to filter processing have been lowered from INFO to DEBUG level.
Make the logging less verbose.
Regression testing as there is no functional change in the patch other than the log level.

ORC-983: Revise filter processing log level/location/message

---

java/bench/spark/pom.xml
java/pom.xml

Filtering module-info.class file during build of uber.jar
Fix the warning.
```
Warning:  Discovered module-info.class. Shading will break its strong encapsulation.
Warning:  Discovered module-info.class. Shading will break its strong encapsulation.
Warning:  Discovered module-info.class. Shading will break its strong encapsulation.
```
I don't think the module system makes sense for uber.jar, it's useful during development. The module-info.class of multiple modules will override each other during the build of uber.jar, and I think its strong encapsulation may have an effect on uber.jar.
Pass the CIs.

ORC-1007: Fix a warning from the shade plugin

---

cmake_modules/ThirdpartyToolchain.cmake

```cmd
CUSTOMBUILD : error : downloading 'ftp://cygwin.osuosl.org/pub/cygwin/noarch/release/tzdata/tzdata-2020e-1.tar.xz' failed [C:\projects\orc\build\tzdata_ep.vcxproj]
status_code: 78
status_string: "Remote file not found"
log:
--- LOG BEGIN ---
timeout on name lookup is not supported
```
https://cygwin.osuosl.org/noarch/release/tzdata/
It looks like the archive tzdata-2020e-1.tar.xz has been deleted and tzdata-2021b-1-src.tar.xz was created two days ago.
Fix CI for winodw.
Pass the CIs.

ORC-1010: Bump tzdata from tzdata-2020e-1.tar.xz to tzdata-2021b-1.tar.xz

---

java/CMakeLists.txt
java/core/pom.xml
java/mapreduce/pom.xml
java/pom.xml
java/shims/pom.xml
java/tools/pom.xml

This PR aims to activate `java17` profile automatically on Java17 runtime.
This simplifies the development environment.
Pass CIs with the revised configuration.

ORC-1011: Activate `java17` profile automatically

---

c++/include/orc/orc-config.hh.in
c++/src/Adaptor.hh.in
c++/src/CMakeLists.txt
c++/src/Statistics.cc
c++/src/Statistics.hh
c++/test/TestColumnStatistics.cc
java/core/src/java/org/apache/orc/impl/ColumnStatisticsImpl.java
java/core/src/test/org/apache/orc/TestColumnStatistics.java

https://github.com/apache/orc/blob/6da96bb8ceb64528d082974efed411c4c29f3408/c%2B%2B/src/Statistics.cc#L180-L190
A counter-example can easily be given
Assume `sum=1`, `update(std::numeric_limits<int64_t>::max(), 3);`
`value * repetitions + _stats.getSum()` is overflowed, but is still a positive number : 9223372036854775806
This pr aims to fix overflow detection code for C++ int64_t / java long.
> ORC-338 Workaround C++ compiler bug in xcode 9.3 by removing an inline function.
As I fixed the implementation. The current update function can be inline.
Fix bug.
Pass the CIs.

ORC-1008: Fix overflow detection code for C++ int64_t / java long

---

tools/src/FileScan.cc
tools/test/TestFileScan.cc

The PR adds an option to support specifying columns to be read in the orc-scan tool.
Currently the orc-scan tool will scan all columns. I find it useful to specifying columns when profiling read performance on specified data types.
Manually tested with the new option.
Added tests in tools/test/TestFileScan.cc.

ORC-1012: Support specifying columns in orc-scan

---

java/core/src/java/org/apache/orc/OrcFile.java

This pr is aimed at avoiding potential ArrayIndexOutOfBoundsException possible when getting WriterVersion.
Fix bug.
Return the Future version when val is equal to versions.length to avoid throwing ArrayIndexOutOfBoundsException on line 248.
Pass the CIs.

ORC-492: Avoid potential `ArrayIndexOutOfBoundsException` when getting WriterVersion

---

site/index.html

This PR aims to add Spark link to Quickstart section. 
To improve visibility. 
Manually verify the generated webpage via docker.

MINOR: Add Spark link to Quickstart section

---

site/README.md
site/develop/make-release.md

This PR aims to update ORC release and publish process pages.
The current web content is outdated.
N/A

ORC-1050: Update ORC site README.md and release process page

---

site/develop/committers.md

This PR aims to add Yiqun Zhang and Huya Company to committers.md file.
N/A
N/A

MINOR: Add Yiqun Zhang and Huya Company to committers.md

---

site/_docs/building.md

This PR aims to update `building.md`.
We support Debian 9 to 11 and Mac 11 to 12.1. 
N/A

ORC-1069: Update building.md

---

java/core/src/java/org/apache/orc/impl/HadoopShimsFactory.java

This PR aims to use a multi-catch in `HadoopShimsFactory.java`.
To simplify the code. 
Pass the CIs.

MINOR: Use multi-catch

---

cmake_modules/ThirdpartyToolchain.cmake

This PR aims to upgrade ZSTD to 1.5.2.
This will bring the latest bug fixes and improvements.
- https://github.com/facebook/zstd/releases/tag/v1.5.2
Pass the CIs.

ORC-1102: Upgrade ZSTD to 1.5.2

---

site/develop/committers.md

This PR aims to add @stiga-huang to the committers page.
To make the committers page up-to-date.

MINOR: Add Quanlong Huang to committers page

---

.asf.yaml

This PR aims to add notification settings to .asf.yaml.
ASF require that we receive all discussions on the mailing list. 
Manual review.

ORC-1158: Add notification settings to .asf.yaml

---

site/_docs/adopters.md

Add Apache Impala to the ORC [adopters page](https://orc.apache.org/docs/adopters.html)
Make the page up-to-date.

MINOR: Add Apache Impala to the ORC adopters page

---

site/develop/committers.md

This PR aims to update Yiqun Zhang from the committer to PMC in site.
N/A
N/A

MINOR: Update Yiqun Zhang from the committer to PMC in site

---

site/doap_orc.rdf

This PR aims to update Apache ORC [DOAP](https://en.wikipedia.org/wiki/DOAP) with new releases, Apache ORC 1.7.4 and 1.6.14.
To keep DOAP up-to-date.
Manual review.

MINOR: Update DOAP with new releases

---

site/develop/committers.md

Added Pavan Lanka as a committer to the site
To update the list of committers
Manual review by bringing up the site locally

Add Pavan Lanka as committer on site

---

c++/include/orc/MemoryPool.hh
c++/include/orc/Reader.hh
c++/include/orc/Type.hh
c++/include/orc/Vector.hh
c++/include/orc/Writer.hh
c++/src/ColumnReader.cc
c++/src/ColumnReader.hh
c++/src/ColumnWriter.cc
c++/src/MemoryPool.cc
c++/src/Options.hh
c++/src/RLE.cc
c++/src/RLE.hh
c++/src/RLEv1.cc
c++/src/RLEv1.hh
c++/src/RLEv2.hh
c++/src/Reader.cc
c++/src/Reader.hh
c++/src/RleDecoderV2.cc
c++/src/Timezone.cc
c++/src/TypeImpl.cc
c++/src/TypeImpl.hh
c++/src/Vector.cc
c++/src/Writer.cc
c++/test/TestWriter.cc
tools/src/FileMetadata.cc

This patch implements int8/int16/int32/float buffer and refactors the RLE encoder/decoder, IntegerColumnWriter/Reader, and DoubleColumnWriter/Reader.
For the context of [ORC-1298](https://issues.apache.org/jira/projects/ORC/issues/ORC-1298?filter=allopenissues), this change makes user no need to focus on overflow.
Add the WriterTest.testWriterFixedWidthNumericVectorBatch UT.

ORC-1298:[C++] Support dedicated ColumnVectorBatch of numeric types

---

site/develop/committers.md

This PR aims to add Xin Zhang  to the committers page.
To keep the list of committers for the ORC website up to date.

MINOR: Add Xin Zhang to committers page

---

site/_posts/2023-02-13-add-xin.md

This is a minor commit to add a news page to welcome Xin Zhang as a new committer.

MINOR: [News] Welcome new committer Xin Zhang

---

site/develop/committers.md

Documentation update changing status to PMC for Pavan Lanka
To update the member status on the site
Manual review

Update Pavan Lanka from committer to PMC in site

---

develop/committers/index.html
docs/building.html

This PR aims to move Alan Gates to Emiritus member. 
Also, Ubuntu version update is also applied. 
Requested by Alan Gates.

MINOR: Move Alan Gates to Emiritus member

---

java/core/src/java/org/apache/orc/impl/ParserUtils.java
java/core/src/test/org/apache/orc/TestOrcFilterContext.java

This PR fixes ORC row level filter with ACID table issue.
Without this Hive can not work with ORC 1.8.3. and ACID table and row level filter enabled.
Unit test added.

ORC-1413 fix for ORC row level filter issue with ACID table

---

c++/include/orc/Vector.hh

There are some errors in the comment of Vector.hh
Fix those errors.
Not required.

ORC-1433: [C++] Fix comment in the Vector.hh

---

c++/src/ColumnReader.cc
c++/src/ColumnWriter.cc
c++/src/TypeImpl.cc

This PR aims to fix `implicit-fallthrough` warning.
To pass `Docker` tests on `clang`
Pass the CIs and manual docker testing.

ORC-1453: Fix `implicit-fallthrough` warnings

---

java/bench/pom.xml

This PR aims to update Spark to 3.4.1.
To use the most recent version of Spark in benchmark. 
Pass the CIs.

ORC-1454: Update Spark to 3.4.1
