c++/include/orc/OrcFile.hh
c++/src/Compression.cc
c++/src/Compression.hh
c++/src/OrcFile.cc
c++/src/Reader.cc
tools/test/TestReader.cc

I've set the local file system to use
128k, but hdfs and webhdfs would both have substantially larger.

ORC-22. Fixes #3 - Allow InputStreams to set the natural read size for their filesystem

---

java/core/src/java/org/apache/orc/impl/TreeReaderFactory.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

This patch adds the two required ensure calls to make sure the scratch vector is large enough.

ORC-73. Fix the vector expansion for DirectStringTreeReader and BinaryTreeReader

---

java/core/pom.xml
java/core/src/java/org/apache/orc/CompressionKind.java
java/core/src/java/org/apache/orc/impl/AircompressorCodec.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/java/org/apache/orc/impl/SnappyCodec.java
java/core/src/java/org/apache/orc/impl/WriterImpl.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java
java/pom.xml

This patch uses the aircompressor codecs to implement lzo and lz4. It also replaces the org.iq80.snappy codec with the aircompressor snappy codec. If the hadoop jni snappy library is available, it will use still use it.
We still need to do some benchmarks for the new snappy codec.

ORC-77. Implement LZO and LZ4 compression codecs.

---

c++/include/orc/MemoryPool.hh
c++/src/wrap/gmock.h

Clang Apple LLVM version 8.1.0 (clang-802.0.41).

ORC-171. Fix C++ template warnings on Mac OS 10.12.4 with

---

java/core/src/java/org/apache/orc/TypeDescription.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/test/org/apache/orc/TestReader.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java
java/mapreduce/src/java/org/apache/orc/mapred/OrcInputFormat.java
java/mapreduce/src/java/org/apache/orc/mapreduce/OrcInputFormat.java

Treat 0 byte files as an empty ORC file with schema of struct<>.

ORC-162. Handle 0 byte files as empty ORC files.

---

java/core/src/java/org/apache/orc/OrcConf.java
java/core/src/java/org/apache/orc/OrcFile.java
java/core/src/java/org/apache/orc/impl/PhysicalFsWriter.java
java/core/src/test/org/apache/orc/impl/TestPhysicalFsWriter.java
java/shims/src/java/org/apache/orc/impl/HadoopShims.java
java/shims/src/java/org/apache/orc/impl/HadoopShimsCurrent.java
java/shims/src/java/org/apache/orc/impl/HadoopShimsPre2_3.java
java/shims/src/java/org/apache/orc/impl/HadoopShimsPre2_6.java
java/shims/src/java/org/apache/orc/impl/HadoopShimsPre2_7.java
site/_docs/hive-config.md

The PhysicalFsWriter sometimes pass down negative sizes for padding, which leads to exceptions.
My fix:
* Add a new option to enable writing variable length HDFS blocks "orc.write.shortened.blocks", which is off by default.
* Modified the shim to shortenBlock so that the PhysicalFsWriter can track the offsets.
* shortenBlock isn't gated by the padding tolerance, although it is called when the new stripe would cross a block boundary.

ORC-248. PhysicalFsWriter sometimes passes negative padding down to shims

---

java/core/src/java/org/apache/orc/OrcUtils.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java

This patch adds a check on the types in the footer to ensure that the type is properly formed before we start building the tree.

ORC-360. Add Java error checking on the types when reading.

---

c++/src/ColumnWriter.cc
c++/test/TestWriter.cc

This patch is the parity of ORC-406 on the C++ side. Now char and varchar writers respect maximum length of UTF-8 characters in the specified file type.

ORC-412: [C++] Fix Char(n) and Varchar(n) writers with UTF-8

---

c++/src/ColumnWriter.cc
c++/src/Statistics.hh
c++/src/Writer.cc

Fix two issues below:
1. A new batch may override previous batch's has_null info of colIndexStatistics if the new batch has no null but the previous batch has at least one null values.
2. If ColumnStatistics does not have any not-null data, it has no sum/min/max infos and this results in writing generic ColumnStatistics in the proto-buf serialization.

ORC-415: [C++] Fix writing ColumnStatistics

---

java/tools/src/java/org/apache/orc/tools/convert/CsvReader.java

There is a missing Javadoc for the param "timestampFormat" in the constructor of `CsvReader`.

ORC-413: Add missing Javadoc for a param in CsvReader

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java

Currently, there is no way to call `RecordReaderImpl.close` if `RecordReader.rows` fails at creating `RecordReaderImpl`. This PR aims to try to invoke `close` in the constructor in case of Exceptions.
```java
@Override
public RecordReader rows(Options options) throws IOException {
LOG.info("Reading ORC rows from " + path + " with " + options);
return new RecordReaderImpl(this, options);
}
```

ORC-419: Ensure to call `close` at RecordReaderImpl constructor exception

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java

Revert "ORC-419: Ensure to call `close` at RecordReaderImpl constructor exception"

---

c++/src/TypeImpl.cc

1. In convertType() function: in the case of proto::Type_Kind_STRUCT, two vectors are created but never used. They shall be removed.
2. In TypeImpl::parseType() function: the function calls input.substr() to copy the substring before parsing it. This string copy can be avoided by directly parsing on the input string.

ORC-429: [C++] Refactor code in TypeImpl.cc

---

c++/src/Writer.cc
c++/src/io/OutputStream.cc

1. Fix typo in the exception message in WriterOptions::setFileVersion(): "Unpoorted" should be "Unsupported".
2. Simplify some code in Writer.cc and OutputStream.cc to avoid re-computation.
3. Simplify a condition check in WriterImpl::buildFooterType().

ORC-431: [C++] Fix typo in exception message and simplify code logic.

---

java/core/src/java/org/apache/orc/impl/ColumnStatisticsImpl.java
java/core/src/test/org/apache/orc/TestColumnStatistics.java

After ORC-202, we need to serialize the string statistics with the lower/upper bounds.

ORC-440. Fix deserialization of string column statistics with truncation

---

c++/src/ColumnWriter.cc
site/specification/ORCv0.md
site/specification/ORCv1.md
site/specification/ORCv2.md

Fixes #468
Signed-off-by: Tadahito Kobayashi <takobayashi@nvidia.com>

ORC-486: Fix doc for nanoseconds encoding

---

c++/src/ByteRLE.cc
c++/test/TestByteRle.cc

If boolean RLE input stream skips all remaining boolean values, we will get an exception since BooleanRLEDecoder still tries to read one last byte from underlying input stream even if the requested number of bits are multiple of 8 and then it reads over the end of stream. This patch fixes this by checking if BooleanRLEDecoder does not need to read one last byte.

ORC-470: [C++] Fix BooleanRleDecoderImpl::skip() read over end of stream

---

c++/src/Compression.cc
c++/test/TestCompression.cc

If DecomressionStream has called Next() to read some data and it has intermediate state, calling seek() can cause it to read from a wrong position. This patch clears all states and forces it to read from right position.

ORC-473: [C++] Fix DecomressionStream::seek to read from right position

---

c++/include/orc/Vector.hh
c++/src/Vector.cc

So that users can merely call it after a batch is written to empty it
recursively before adding new elements for the next batch.
Without that method I can think of no better way to reset a batch than to overload all the ColumnVectorBatch to add this method.

ORC-474: Add a clear() method to ColumnVectorBatch

---

c++/src/ByteRLE.cc
c++/test/TestByteRle.cc

- Reset remaingbits to zero on seek to make sure correct data is read.

ORC-370:[C++] Reset BooleanRleDecoder remainingbits to zero on seek

---

c++/include/orc/BloomFilter.hh
c++/include/orc/Common.hh
c++/include/orc/Reader.hh
c++/include/orc/Writer.hh
c++/src/BloomFilter.cc
c++/src/BloomFilter.hh
c++/src/CMakeLists.txt
c++/src/ColumnWriter.cc
c++/src/ColumnWriter.hh
c++/src/Murmur3.cc
c++/src/Murmur3.hh
c++/src/Reader.cc
c++/src/Reader.hh
c++/src/Writer.cc
c++/test/CMakeLists.txt
c++/test/TestBloomFilter.cc
c++/test/TestWriter.cc

1. Support C++ writer to enable bloom filter of specific columns.
2. Support C++ reader to get bloom filter of specific columns.
3. Only bloom filter of UTF8 type is supported.

ORC-488: [C++] Support BloomFilter in C++ library

---

tools/src/CSVFileImport.cc

[C++] CSVFileImport.cc has error when DataBuffer running out and doubling size
CSVFileImport was using Databuffer::reserve() but this will not change the size.
Even the size was changed, the new buffer has totally different address, which will make previous stringBatch->data[i], (i is the already finished ones) stores the wrong address.

[ORC-499][C++] Change databuffer resize and refill previous data

---

c++/include/orc/Vector.hh
c++/src/ColumnReader.cc
c++/src/Vector.cc

- Move blob ownership from StringColumnReader to StringVectorBatch to avoid data overriden
- Enforce memcpy on StringColumnReader to make sure string blob is owned by external user

ORC-501: [C++]Move blob ownership from StringColumnReader to StringVectorBatch to avoid data overriden

---

java/core/src/java/org/apache/orc/CompressionCodec.java
java/core/src/java/org/apache/orc/impl/AircompressorCodec.java
java/core/src/java/org/apache/orc/impl/CryptoUtils.java
java/core/src/java/org/apache/orc/impl/OrcCodecPool.java
java/core/src/java/org/apache/orc/impl/OutStream.java
java/core/src/java/org/apache/orc/impl/PhysicalFsWriter.java
java/core/src/java/org/apache/orc/impl/SerializationUtils.java
java/core/src/java/org/apache/orc/impl/SnappyCodec.java
java/core/src/java/org/apache/orc/impl/StreamName.java
java/core/src/java/org/apache/orc/impl/WriterImpl.java
java/core/src/java/org/apache/orc/impl/ZlibCodec.java
java/core/src/java/org/apache/orc/impl/writer/StreamOptions.java
java/core/src/test/org/apache/orc/impl/TestBitFieldReader.java
java/core/src/test/org/apache/orc/impl/TestCryptoUtils.java
java/core/src/test/org/apache/orc/impl/TestInStream.java
java/core/src/test/org/apache/orc/impl/TestIntegerCompressionReader.java
java/core/src/test/org/apache/orc/impl/TestOutStream.java
java/core/src/test/org/apache/orc/impl/TestRunLengthByteReader.java
java/core/src/test/org/apache/orc/impl/TestRunLengthIntegerReader.java
java/core/src/test/org/apache/orc/impl/TestStreamName.java
java/core/src/test/org/apache/orc/impl/TestZlib.java

The writer's stream options should be cleaned up. There are a couple of related items:
* We end up changing the IV's for streams and we need to notify the stream when we do so, therefore it is better to make an explicit API to change them.
* CryptoUtils should match with functions to modify an IV rather than forcing an allocation.
* CompressionCodec.Options only needs to be copied when we have tuning options.
* CompressionCodec would be nice to have as Closeable where that returns it to the pool.

ORC-510: Cleanup StreamOptions and CompressionCodec.Options

---

java/core/src/java/org/apache/orc/InMemoryKeystore.java
java/core/src/test/org/apache/orc/TestInMemoryKeystore.java
java/shims/src/java/org/apache/orc/EncryptionAlgorithm.java
java/shims/src/java/org/apache/orc/impl/HadoopShims.java
java/shims/src/java/org/apache/orc/impl/HadoopShimsPre2_3.java
java/shims/src/java/org/apache/orc/impl/HadoopShimsPre2_7.java
java/shims/src/java/org/apache/orc/impl/LocalKey.java
java/shims/src/test/org/apache/orc/impl/TestHadoopShimsPre2_7.java

The big things here are:
* Record how the keys were encrypted.
* Make the "Hadoop KMS" shim generate the encrypted key and use the prefix as the IV.
* Make the "Hadoop KMS" shim bit flip the IV to compensate for the bit flip in the KMS.
* Add test cases that check to make sure we get the results we expect for the encrypted key.
* Pull the LocalKey out of the HadoopShim class.

ORC-509: Update KeyProvider to match the updated spec.

---

java/core/src/java/org/apache/orc/PhysicalWriter.java
java/core/src/java/org/apache/orc/impl/PhysicalFsWriter.java
java/core/src/java/org/apache/orc/impl/WriterImpl.java
java/core/src/java/org/apache/orc/impl/writer/ListTreeWriter.java
java/core/src/java/org/apache/orc/impl/writer/MapTreeWriter.java
java/core/src/java/org/apache/orc/impl/writer/StructTreeWriter.java
java/core/src/java/org/apache/orc/impl/writer/TreeWriter.java
java/core/src/java/org/apache/orc/impl/writer/TreeWriterBase.java
java/core/src/java/org/apache/orc/impl/writer/UnionTreeWriter.java
java/core/src/java/org/apache/orc/impl/writer/WriterContext.java
java/core/src/java/org/apache/orc/impl/writer/WriterEncryptionKey.java
java/core/src/java/org/apache/orc/impl/writer/WriterEncryptionVariant.java
java/core/src/test/org/apache/orc/TestStringDictionary.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

The PhysicalWriter and its implementation need a couple of changes:
* Stripe & file statistics need to be handled differently to support encryption. There is now a method on the WriterContext that allows setting the stripe & file statistics.
* getFileBytes needs to know which encryption variant is being asked about
* I generalized PhysicalWriter.getCompressionCodec to getStreamOptions.
* The PhysicalFsWriter now tracks each encryption variant and handles them separately.
* StreamName gets the encryption variant.
* TreeWriter gets a new method for getting the current file stats.
* Add WriterEncryptionVariant and WriterEncryptionKey to keep encryption information.

ORC-484 Extend PhysicalWriter to support encryption

---

java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java
java/core/src/test/org/apache/orc/impl/TestSchemaEvolution.java

This PR removes about 700 lines from the schema evolution code:
* Removes most of the float conversions, which aren't needed now.
* Removes the duplicate reference to the underlying TreeReader in each subclass.
* Creates a new double->float conversion that casts it to a float instead of using strings.
* The test case float->double had to loosen the delta on the comparison since we don't get the implicit truncation from going through stringification.
* Moves the file names for TestSchemaEvolution to use that as the filename prefix on the written orc files.

ORC-531. Refactor schema evolution including removing the float conversions.

---

java/core/src/java/org/apache/orc/TypeDescription.java
java/core/src/test/org/apache/orc/TestTypeDescription.java
java/tools/src/java/org/apache/orc/tools/FileDump.java
java/tools/src/java/org/apache/orc/tools/JsonFileDump.java
java/tools/src/test/org/apache/orc/tools/TestFileDump.java
java/tools/src/test/org/apache/orc/tools/TestJsonFileDump.java
java/tools/src/test/resources/orc-file-dump-bloomfilter.out
java/tools/src/test/resources/orc-file-dump.json

Fix a few problems with type annotations:
* clone() needs to copy them.
* setAttribute with null should clear them.
* equals should compare them
* file dump should print them.
* json file dump should make them nicer
* add test cases for the file dump commands.
* change the json write schema to be tree-like rather than flat.

ORC-538. Fix a few problems with the type attributes.

---

c++/src/Reader.cc

Fixes uint32 overflow when calculating how many rows to skip by casting to uint64.

ORC-567: [C++] Fix integer overflow in RowReader::seekToRow

---

java/core/src/findbugs/exclude.xml
java/core/src/java/org/apache/orc/impl/writer/StringBaseTreeWriter.java
java/core/src/test/org/apache/orc/TestStringDictionary.java
java/tools/src/java/org/apache/orc/tools/Driver.java

Fixes the missing positions list in the first row index entry and adds a test case.
There is an unrelated trivial fix for the tool Driver that I found while testing this bug.

ORC-569: Fixed empty positions list in first row index entry.

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcFileEvolution.java

This patch fixes the places where the RecordReaderImpl is using the reader schema when it needs to use the file schema.
It also adds some test cases where we test with sargs combined with schema evolution.

ORC-571. Fix ArrayIndexOutOfBoundsException in StripePlanner.readRowIndex

---

c++/include/orc/Common.hh
c++/include/orc/Int128.hh
c++/include/orc/Vector.hh
c++/src/ColumnWriter.cc
c++/src/Int128.cc
c++/src/Statistics.hh
c++/src/Vector.cc
c++/test/TestInt128.cc

Before implementing predicate pushdown for C++ reader, we need to fix several issues related to decimal types.
1. Support Decimal::toString() to trim trailing zeros.
2. Int128::toDecimalString has an issue when it deals with substr operation which may lead to wrong string representation of decimal. Fix it to handle scale correctly.
3. Apply DecimalColumnWriter to trim trailing zeros before writing to bloom filter.

ORC-573: [C++] Fix several issues in Int128 and Decimal

---

c++/src/Reader.cc
c++/test/TestType.cc

For STRUCT types, fieldNames size can be different than subTypes size in
a corrupt file. We should verify it to avoid crash.

ORC-581:[C++] Verify fieldNames size for STRUCT types

---

c++/src/ColumnPrinter.cc
c++/src/ColumnReader.cc
c++/src/ColumnWriter.cc
c++/src/Compression.cc
c++/src/Options.hh
c++/src/TypeImpl.cc
c++/src/TypeImpl.hh
c++/src/Writer.cc

Substituted raw pointers to std::unique_ptrs in StructColumnReader
in order to prevent memory leaks.

ORC-586: [C++] fix memory leak in StructColumnReader

---

c++/include/orc/sargs/Literal.hh
c++/include/orc/sargs/SearchArgument.hh
c++/include/orc/sargs/TruthValue.hh
c++/src/CMakeLists.txt
c++/src/sargs/ExpressionTree.cc
c++/src/sargs/ExpressionTree.hh
c++/src/sargs/Literal.cc
c++/src/sargs/PredicateLeaf.cc
c++/src/sargs/PredicateLeaf.hh
c++/src/sargs/SargsApplier.cc
c++/src/sargs/SargsApplier.hh
c++/src/sargs/SearchArgument.cc
c++/src/sargs/SearchArgument.hh
c++/src/sargs/TruthValue.cc
c++/test/CMakeLists.txt
c++/test/TestPredicateLeaf.cc
c++/test/TestSargsApplier.cc
c++/test/TestSearchArgument.cc

1. Implement Literal class to handle literal values in a predicate of different data types.
2. Port TruthValue, ExpressionTree, PredicateLeaf, and SearchArgument from Java hive-storage-api.
3. Port SargsApplier from Java ORC reader.

ORC-40: [C++] Support building SearchArgument

---

site/_docs/adopters.md

Docs only change as part of the website.

ORC-XXX: Move blog post for ORC adopter Spark

---

c++/test/TestByteRle.cc

ASAN reports a memory leak in this tests. The "data" buffer is allocated using new but no deallocated at the end.

Memory leak on test

---

c++/src/Compression.cc

This commit does not intend to change anything in the current
behaviour, its only purpose is to reduce the huge amount of code
duplication in Compression.cc by refactoring the common functionality
of ZlibDecompressionStream and BlockDecompressionStream under a
common base class.
Tests:
- Run orc-tests successfully.

ORC-615: Refactor decompression streams into common base class

---

c++/src/Compression.cc

Issue described in [ORC-639](https://issues.apache.org/jira/browse/ORC-639):
In Compression.cc, classes ZSTDCompressionStream and ZSTDDecompressionStream employ Zstd's "Simple API", which initializes the compression/decompression context each time. This context initialization includes time to initialize all compression/decompression tables.
Using the "Explicit context" API improves the performance significantly as compression/decompression tables are constructed once and reused each time "decompress" or "doBlockCompression" is called.
We've noticed more than 15% time improvement in some applications with this change, so it seems that any ORC user using Zstd can benefit from this change.

ORC-639: Improve zstd performance

---

CMakeLists.txt
c++/src/CMakeLists.txt

Consuming Apache ORC in a C++ project as CMake submodule (via add_subdirectory) currently causes two issues:
* A warning about CMake policy CMP0048 not being set, which cannot be suppressed from the outside:
```
CMake Warning (dev) at third_party/orc/CMakeLists.txt:15 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
PROJECT_VERSION
PROJECT_VERSION_MAJOR
PROJECT_VERSION_MINOR
PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
```
* Errors about CMake modules not being found:
```
CMake Error at third_party/orc/CMakeLists.txt:116 (INCLUDE): …
```

ORC-640: [C++] Support consumption as CMake submodule

---

.travis.yml

In addition to the existing macOS `10.13` and `10.14` testing, this PR aims to support `macOS 10.15` testing by using `osx_image: xcode12`.
- https://docs.travis-ci.com/user/reference/osx/#using-macos
This will add clang 12.0.0 test coverage as we see the Travis CI log in this PR.
- https://travis-ci.org/github/apache/orc/jobs/708583066
```
$ clang --version
98Apple clang version 12.0.0 (clang-1200.0.22.8)
99Target: x86_64-apple-darwin19.5.0
```

ORC-647: Add macOS 10.15 test to Travis CI

---

.github/workflows/master.yml

This PR aims to add `GitHub Action` for explicit Java 8/11 test coverage. Since this is an independent CI setup, this will not interfere with the existing CIs.
Apache ORC is currently using
- Travis CI for testing various `clang` versions on Trusty and Mac with JDK7.
- Appveyor CI for testing Visual Studio on Windows OS.
This is tested here.
- https://github.com/dongjoon-hyun/orc/pull/3
After this PR, it seems that we need to file Apache INFRA JIRA issue to enable `GitHub Action` on ORC project.

ORC-648: Add GitHub Action for Java8/11 test coverage

---

.github/PULL_REQUEST_TEMPLATE

This PR aims to add `GitHub Pull Request Template`.
This will help contributors and reviewers to provide a standardized way to communicate.
Manually review the template.

ORC-651: Use GitHub Pull Request Template

---

c++/src/RleEncoderV2.cc
c++/test/TestBloomFilter.cc
c++/test/TestByteRle.cc

On Ubuntu 20 with Clang 10, build doesn't work https://gist.github.com/nikitamikhaylov/18e5f22e81a89f701520558a4c39f30d
Because every statement is separated by ; and ; after { means empty statement, which has no effect.
Because I want the build to work on Ubuntu 20.
Build now works.

ORC-654: Fix build with clang-10 and ubuntu-20

---

java/bench/pom.xml
java/bench/spark/pom.xml

This PR aims to update `bench` module to use Apache Spark 2.4.6.
Apache Spark 2.4.6 is the latest version and we need to update `maven-shade-plugin` to use it.
This should be tested manually.
```
$ mvn clean package
```

ORC-655: Update bench to use Spark 2.4.6

---

java/bench/fetch-data.sh

This PR aims to use gharchive.org instead of githubarchive.org.
The URL is permanently moved. 
```
--2020-08-08 23:14:16--  http://data.githubarchive.org/2015-11-01-1.json.gz
Connecting to data.githubarchive.org (data.githubarchive.org)|140.82.113.18|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://data.gharchive.org/2015-11-01-1.json.gz [following]
--2020-08-08 23:14:16--  https://data.gharchive.org/2015-11-01-1.json.gz
Connecting to data.gharchive.org (data.gharchive.org)|104.18.54.216|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4708768 (4.5M) [application/gzip]
Saving to: '2015-11-01-1.json.gz.1'
```
```
cd java/bench/
fetch-data.sh 
```

ORC-656: Use gharchive.org instead of githubarchive.org

---

java/bench/pom.xml

This PR aims to remove `com.netflix.iceberg` dependency from `java/bench` module
This is unused and `iceberg` became Apache Iceberg already.
Manually.
```
$ mvn package
```

ORC-657: Remove com.netflix.iceberg dependency in java/bench module

---

c++/src/Compression.cc

This PR aims to initialize `next_in` before calling DeflateInit2.
According to zlib documentation of DeflateInit2:
_"This is another version of deflateInit with more compression options. The fields **next_in**, zalloc, zfree and opaque must be initialized before by the caller."_
In an alpine docker DeflateInit2 was returning an error that seems to be solved with the patch.
Pass UT.

ORC-659: Initialize "next_in" before calling DeflateInit2

---

java/bench/core/pom.xml

This PR aims to add `hadoop-hdfs` dependency to `bench/core` module.
This will fix `NoClassDefFoundError` error during data generation.
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar generate data
[WARN ] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/client/HdfsDataOutputStream$SyncFlag
```
```
cd java/bench
mvn package
./fetch-data.sh
java -jar core/target/orc-benchmarks-core-*-uber.jar generate data
```

ORC-658: Fix NoClassDefFoundError during benchmark data generation

---

java/core/src/java/org/apache/orc/DateColumnStatistics.java
java/core/src/java/org/apache/orc/impl/ColumnStatisticsImpl.java
java/core/src/java/org/apache/orc/impl/DateUtils.java
java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/java/org/apache/orc/impl/writer/TreeWriterBase.java
java/core/src/test/org/apache/orc/TestColumnStatistics.java
java/core/src/test/org/apache/orc/TestProlepticConversions.java
java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java

This PR adds 4 new methods to the DateColumnStatistics.
* getMinimumLocalDate -> LocalDate
* getMinimumDayOfEpoch -> int
and the matching getMaximum functions. The current functions are deprecated. The DateColumnStatisticsImpl moves the minimum and maximum values to int instead of Integer, so they can be modified. The initial values are Integer.MAX_VALUE and MIN_VALUE.
The PPD code is changed to use LocalDate instead of Date.

ORC-661. Use LocalDate and day of epoch instead of java's Date for column statistics

---

java/core/src/test/org/apache/orc/impl/TestSchemaEvolution.java

This PR aims to use `TestSchemaEvolution` as a test file prefix to prevent failures during repeated tests.
To help the test.
Repeat the test suite twice.

ORC-668. Use `TestSchemaEvolution` as a test file prefix to prevent test failure

---

java/core/src/java/org/apache/orc/impl/ReaderImpl.java

Although this is `Implementation` class, this PR aims to reduce two breaking changes in `ReaderImpl.java` due to [ORC-520](https://github.com/apache/orc/pull/423) at Apache ORC 1.6.0 ~ 1.6.5.
This helps Apache Hive and Spark works with Apache ORC 1.6.x by removing the following breaking changes with a minor and safe revision.
```
[info] org.apache.spark.sql.hive.orc.OrcHadoopFsRelationSuite *** ABORTED ***
[info]   java.lang.NoSuchFieldError: types
[info]   at org.apache.hadoop.hive.ql.io.orc.ReaderImpl.<init>(ReaderImpl.java:64)
[info] org.apache.spark.sql.hive.orc.HiveOrcHadoopFsRelationSuite *** ABORTED ***
[info]   java.lang.IllegalAccessError: tried to access field org.apache.orc.impl.ReaderImpl.compressionKind
from class org.apache.hadoop.hive.ql.io.orc.ReaderImpl
```
Manually …

ORC-669. Reduce breaking changes in ReaderImpl.java

---

c++/src/CMakeLists.txt
c++/test/CMakeLists.txt
cmake_modules/FindGTest.cmake
cmake_modules/FindLZ4.cmake
cmake_modules/FindProtobuf.cmake
cmake_modules/FindSnappy.cmake
cmake_modules/FindZLIB.cmake
cmake_modules/FindZSTD.cmake
cmake_modules/ThirdpartyToolchain.cmake
tools/src/CMakeLists.txt
tools/test/CMakeLists.txt

This patch allows selectively linking each third party library
statically with a fallback to dynamic, if not available
This is a follow up of the discussion at: https://github.com/apache/orc/pull/524

Partially rework cmake modules to accommodate library types

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/test/org/apache/orc/TestOrcTimestampPPD.java
java/core/src/test/org/apache/orc/impl/TestPredicatePushDownBounds.java
java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java

FIx PPD Less than Equals comparison for min==max corner case
Better PPD evaluation
Extra JUnit test

ORC-673: PPD LTE Point equality comparison is wrong when RG MIN==MAX

---

c++/src/wrap/orc-proto-wrapper.cc
docker/README.md
docker/centos7/Dockerfile
docker/centos8/Dockerfile
docker/debian10/Dockerfile
docker/debian8/Dockerfile
docker/debian9/Dockerfile
docker/os-list.txt
docker/ubuntu14/Dockerfile
docker/ubuntu16/Dockerfile
docker/ubuntu18/Dockerfile
docker/ubuntu20-clang/Dockerfile
docker/ubuntu20/Dockerfile
site/_docs/building.md

Adds ubuntu 20 with gcc and clang.
Removes support for debian 8 and ubuntu 14.

ORC-674: Update Dockerfiles

---

cmake_modules/ThirdpartyToolchain.cmake

This PR aims to update tzdata to recover Win32 build in AppVeyor.
Currently, AppVeyor builds on `master/branch-1.6/branch-1.5` are broken since Oct 9, 2020. To recover CI test coverage.
Pass the AppVeyor.

ORC-679: Update tzdata to recover Win32 build in AppVeyor

---

.travis.yml

This PR aims to upgrade Travis CI from Ubuntu 14.04 to Ubuntu 16.04.
**BEFORE**
**AFTER**
Travis CI `Trusty` has a wrong `javac`. We should use JDK8 for `javac`. This is fixed with this patch.
```
$ java -Xmx32m -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3~14.04-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
$ javac -J-Xmx32m -version
javac 9.0.1
```
ORC-674 and ORC-675 removed Ubuntu 14.04.
Pass the Travis CI.

ORC-680: Upgrade Travis CI linux os from Ubuntu 14.04 to Ubuntu 16.04

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java

This PR aims to add a deprecated legacy constructor `SargApplier` back.
ORC-27 removes this at Apache ORC 1.5.9 and 1.6.3 and this causes a compilation error at Apache Hive 3.1 branch (https://github.com/apache/hive/pull/1615).
- ORC-27: https://github.com/apache/orc/commit/949c7444ef98680026d9f2b93d7299b76cdfb030#diff-8678415090c906d11e0aa6241ba24643192cd66617c68d8deb0f7efe74dd2ba3L876-R883
Pass the CI with the newly added test case.

ORC-677: Add a deprecated legacy constructor SargApplier back

---

c++/include/orc/Statistics.hh
c++/include/orc/sargs/Literal.hh
c++/src/ColumnWriter.cc
c++/src/Statistics.cc
c++/src/Statistics.hh
c++/src/sargs/Literal.cc
c++/src/sargs/PredicateLeaf.cc
c++/test/TestColumnStatistics.cc
c++/test/TestPredicateLeaf.cc
c++/test/TestSearchArgument.cc

1. Store nanosecond into TimestampColumnStatistics in C++ writer.
2. Be aware of nanosecond in the TimestampColumnStatistics.
3. Adde new functions in TimestampColumnStatistics to get nanosecond while keeping backward compatibility.
4. Fix PPD to utilize nanosecond or use a default value for timestamp columns.
To be consistent with the java side.
Several new unit tests have been added to TestPredicateLeaf.cc, TestColumnStatistics.cc, and TestSearchArgument.cc.

ORC-663: [C++] Support timestamp statistics with nanosecond

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

ORC-629 added an extra check (part of  RecordReaderImp) disabling PPD when DoubleColumnStats min, max or sum is a non-Finite number.
However, the check is unnecessarily broad – the way stats are updated, using just sum for the check would suffice.
https://github.com/apache/orc/blob/master/java/core/src/java/org/apache/orc/impl/ColumnStatisticsImpl.java#L568
Make PPD NaN check for floating point stats more strict
TestVectorOrcFile.testPredicatePushdownWithNan()

ORC-683: PPD: Make Floating point NaN check more strict

---

c++/src/sargs/PredicateLeaf.cc
c++/test/TestPredicateLeaf.cc

ORC-636 added an extra check (part of RecordReaderImp) disabling PPD when DoubleColumnStats min, max or sum is a non-Finite number.
However, the check is unnecessarily broad – the way stats are updated, using just sum for the check would suffice.
Make NAN check for DoubleStats (used for PPD) more strict
TestPredicateLeaf.cc

ORC-684: [C++] Make Floating point NaN check more strict

---

java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/test/org/apache/orc/impl/TestReaderImpl.java

This PR aims to add ReaderImpl.extractFileTail back to mitigate backward compatibility (partially as StripeStatistics are removed from ORCTail).
Apache ORC 1.6.0 ~ 1.6.5 removes extractFileTail  from the ReaderImpl. This PR adds API backward compatibility.
TestReaderImp. testOrcTailStripeStats()

ORC-685: Add `ReaderImpl.extractFileTail` back

---

java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java
java/core/src/test/org/apache/orc/impl/TestSchemaEvolution.java

Enable String conversion from varchar. 
Currently createStringConvertTreeReader in ConvertTreeReaderFactory is missing that opportunity
Modify createStringConvertTreeReader to handle char, varchar and string as part of the same group.
TestSchemaEvolution.testCharToStringEvolution

ORC-688: Allow CHAR to be promoted to STRING

---

.github/workflows/publish_snapshot.yml

This PR aims to add `GitHub Action` job to publish snapshot like the following. The following is generated by this patch from my fork `master` branch.
- https://repository.apache.org/content/repositories/snapshots/org/apache/orc/orc-core/1.7.0-SNAPSHOT/
Currently, Apache ORC community doesn't provide snapshot artifacts. It would be great if we provide it in order to help the downstream projects to test it in advance.
This is tested in my ORC fork and we need INFRA team's credential setup.
- https://github.com/dongjoon-hyun/orc/runs/1468464962 (I merged to my `master` branch and removed it after testing)
- https://issues.apache.org/jira/browse/INFRA-21150 (Upload snapshots from GitHub Actions)

ORC-689: Add GitHubAction job to publish snapshot

---

c++/src/wrap/orc-proto-wrapper.cc
docker/README.md
docker/centos7/Dockerfile
docker/centos8/Dockerfile
docker/debian10/Dockerfile
docker/debian8/Dockerfile
docker/debian9/Dockerfile
docker/os-list.txt
docker/ubuntu14/Dockerfile
docker/ubuntu16/Dockerfile
docker/ubuntu18/Dockerfile
docker/ubuntu20-clang/Dockerfile
docker/ubuntu20/Dockerfile
site/_docs/building.md

ORC-674: Update docker files (#553)
- added docker files for ubuntu 20 with and without clang
- remove debian 8, and ubuntu 14
(cherry picked from commit 7275ceb8cce0a7316daa357e632fcf4bb21501c8)

ORC-674: Update docker files (#553)

---

java/core/src/java/org/apache/orc/OrcUtils.java
java/core/src/java/org/apache/orc/impl/ParserUtils.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

Consistent TypeDescription handling for quoted field names
SARGs failing due to incorrect handling of quoted fieldNames
TestVectorOrcFile.testQuotedPredicatePushdown

ORC-696: Consistent TypeDescription handling for quoted field names

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/tools/src/java/org/apache/orc/tools/ScanData.java

This PR updates the scan tool to print information about where the file is corrupted. It
* reads data by batches until there is a problem
* tries re-reading that batch column by column to find which column is corrupted
* figures out the next location that the reader can seek to
It helps diagnose where (row & column) an ORC file is corrupted.
It was tested on ORC files that were corrupted by bad machines.

ORC-697: Improve scan tool to report the location of corruption.

---

java/tools/src/java/org/apache/orc/tools/ScanData.java

- Change the stripe id to be 0 based, which seems more consistent.
- Change the end of file stripe id to be the number of stripes rather than -1.
- Limit the recovery row to the start of the next stripe.
- Add --verbose that prints exceptions.
- Fix the --help to give more information
Tested by hand on the example files.

ORC-699. Minor improvements to the scan tool that make the exception messages optional.

---

c++/src/OrcFile.cc

Use 64-bit versions of fstat to support files bigger than 2GB in Windows.
To support big files.
Manual

ORC-702: [C++] Support big ORC files in Windows

---

.github/workflows/publish_snapshot.yml

This PR aims to only publish snapshots at apache orc repo by adding an if statement. 
To save the resources at the downstream.
N/A

ORC-704: Publish snapshots at only apache repo

---

cmake_modules/ThirdpartyToolchain.cmake

FIX tzdata to recover Win32 build in AppVeyor
Recover win32 build
AppVeyor

ORC-707: FIX tzdata to recover Win32 build in AppVeyor

---

site/_docs/adopters.md

PrestoSQL has been renamed to Trino. See: https://trino.io/blog/2020/12/27/announcing-trino.html

MINOR: Rename Presto SQL to Trino

---

java/core/src/java/org/apache/orc/impl/ColumnStatisticsImpl.java
java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java

RecordReaderImp should pass down the writer calendar info (writerUsedProlepticGregorian) when evaluating predicates to make sure column stats are properly deserialized (affects TimestampStatistics)
Correct evaluation of predicates with Timestamps
TestRecordReaderImpl.testPredEvalTimestampStatsDiffWriter

ORC-705: Predicate evaluation should take into account writer calendar

---

java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java
java/core/src/test/org/apache/orc/impl/TestSchemaEvolution.java

Special ConvertTreeReader for Boolean using StringGroupFromAnyIntegerTreeReader for String/Char/Varchar types
Properly handle Boolean to String/Char/Varchar conversions
TestSchemaEvolution.testBooleanToStringEvolution

ORC-709: FIX Boolean to StringGroup schema evolution

---

.github/workflows/publish_snapshot.yml

This PR aims to use `maven deploy` directly.
Apache repository doesn't allow 3rd party GitHub Action script.
Tested locally
This closes #593

ORC-708: Use maven command directly

---

cmake_modules/ThirdpartyToolchain.cmake

FIX tzdata to recover Win32 build in AppVeyor in 1.5 backporting #590 
Recover win32 build
AppVeyor

ORC-707: FIX tzdata to recover Win32 build in AppVeyor (#590)

---

java/shims/src/java/org/apache/orc/impl/HadoopShimsPre2_7.java

This PR aims to support `CryptoExtension` in `create/decryptLocalKey` as `KeyProvider`.
Currently, `ORC` supports `KeyProviderCryptoExtension` only.
```
public class KeyProviderCryptoExtension extends
KeyProviderExtension<KeyProviderCryptoExtension.CryptoExtension>
```
When `LoadBalancingKMSClientProvider` is used as a `KeyProvider`, `ClassCastException` occurs because we cannot cast it to `KeyProviderCryptoExtension` currently.
```java
public class LoadBalancingKMSClientProvider extends KeyProvider implements
CryptoExtension,
KeyProviderDelegationTokenExtension.DelegationTokenExtension {
```
We need to support `CryptoExtension`, too.
Manually.

ORC-711: Support CryptoExtension in create/decryptLocalKey

---

site/_data/docs.yml
site/_docs/spark-config.md
site/_docs/spark-ddl.md

This PR aims to add `USING IN SPARK` section to web site.
Like `Apache Hive`, `Apache Spark` is using `ORC`.
Manual.

ORC-712: Add `USING IN SPARK` to website

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java

PPD evaluation: Date type Pred baseObject normalization to LocalDate (comparable with ColumnStats)
Date baseObject normalization is missing leading to ClassCastException when using single Value IN ppd evaluation.
TestRecordReaderImpl.testInDatePredConversion

ORC-724: PPD: Date IN single value comparison throws ClassCastException

---

.github/workflows/build_and_test.yml

This PR aims to rename the job name of `build_and_test.yml` file to `Build and test`.
Currently, this has a branch name.
- In `master` branch, `master` is the job name
- In `branch-1.6` branch, `branch-1.6` is the job name.
The correct usage is having the same name for the same jobs.
Note that GitHub Action log view page has a filtering feature by branch names because of this.
Pass the GitHub Action.

MINOR: Rename GitHub Action job name to `Build and test`

---

.asf.yaml

According to the infra team's guide, [INFRA-21289](https://issues.apache.org/jira/browse/INFRA-21289
), this PR aims to disable merge commits from GitHub `Merge Button`.
This will prevent accidental merge commits.
This PR follows the guide
- https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#git.asf.yamlfeatures-Mergebuttons
N/A

ORC-725: Disable merge commits from Github `Merge Button`

---

java/pom.xml
java/tools/pom.xml

This PR aims to upgrade `tools` module to use Apache Hadoop 2.10.1.
This will make `orc-tools` CLI to use the latest and stable Hadoop 2.10.1 version.
Pass the CIs and manually check the dependency change with `mvn dependency:tree`
```
[INFO] ----------------------< org.apache.orc:orc-tools >----------------------
[INFO] Building ORC Tools 1.7.0-SNAPSHOT                                  [5/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ orc-tools ---
[INFO] org.apache.orc:orc-tools:jar:1.7.0-SNAPSHOT
[INFO] +- org.apache.orc:orc-core:jar:1.7.0-SNAPSHOT:compile
[INFO] |  +- org.apache.orc:orc-shims:jar:1.7.0-SNAPSHOT:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:2.5.0:compile …
```

ORC-603. Upgrade `tools` to use Hadoop 2.10.1

---

.asf.yaml

This PR aims to add to `https://github.com/apache/orc`.
- website link
- project description
To help a better UX. This will be displayed here (the red box).
N/A

ORC-730: Add website link and description to GitHub page

---

java/core/src/java/org/apache/orc/impl/RecordReaderUtils.java
java/core/src/java/org/apache/orc/impl/mask/RedactMaskFactory.java
java/core/src/test/org/apache/orc/TestColumnStatistics.java
java/core/src/test/org/apache/orc/TestUnicode.java
java/core/src/test/org/apache/orc/impl/TestPredicatePushDownBounds.java
java/mapreduce/src/java/org/apache/orc/mapred/OrcInputFormat.java
java/tools/src/java/org/apache/orc/tools/FileDump.java

Although ORC-682 upgraded to `commons-lang3`, we are still using `commons-lang` classes.
This will switch it completely.
Pass the CIs.
These are the all instances.
```
$ git grep org.apache.commons.lang.
core/src/java/org/apache/orc/impl/RecordReaderUtils.java:import org.apache.commons.lang3.builder.HashCodeBuilder;
core/src/java/org/apache/orc/impl/mask/RedactMaskFactory.java:import org.apache.commons.lang3.StringUtils;
core/src/test/org/apache/orc/TestColumnStatistics.java:import org.apache.commons.lang3.RandomStringUtils;
core/src/test/org/apache/orc/TestColumnStatistics.java:import org.apache.commons.lang3.StringEscapeUtils;
core/src/test/org/apache/orc/TestUnicode.java:import org.apache.commons.lang3.StringUtils;
core/src/test/org/apache/orc/impl/TestPredicatePushDownBounds.java:impor …
```

ORC-734: Use org.apache.commons.lang3

---

java/pom.xml

This PR aims to upgrade Zookeeper runtime dependency from 2.4.6 to 3.6.2.
Zookeeper 2.4.6 has is a known issue on Java 14 environment. This upgrade is recommended by Zookeeper community for Java 14 and also Spark community is currently moving on too.
- https://issues.apache.org/jira/browse/ZOOKEEPER-3779 (Zookeeper client 3.4.x fails to connect when using Java 14)
- https://issues.apache.org/jira/browse/SPARK-34110 (Upgrade ZooKeeper to 3.6.2)
Pass the CIs.

ORC-733: Upgrade Zookeeper to 3.6.2

---

java/tools/src/java/org/apache/orc/tools/convert/ConvertTool.java

This PR aims to fix a bug in ConvertTool by using the provided schema in case of a single file. 
**BEFORE**
```
% java -jar tools/target/orc-tools-1.7.0-SNAPSHOT-uber.jar convert ../examples/TestOrcFile.test1.orc
Merging schema from ../examples/TestOrcFile.test1.orc
Exception in thread "main" java.lang.IllegalArgumentException: Unhandled type map<string,struct<int1:int,string1:string>>
at org.apache.orc.tools.json.JsonSchemaFinder.makeHiveType(JsonSchemaFinder.java:314)
at org.apache.orc.tools.json.JsonSchemaFinder.makeHiveType(JsonSchemaFinder.java:301)
at org.apache.orc.tools.json.JsonSchemaFinder.addSchema(JsonSchemaFinder.java:319)
at org.apache.orc.tools.convert.ConvertTool.buildSchema(ConvertTool.java:81)
at org.apache.orc.tools.convert.ConvertTool.<init>(ConvertTool.java:188)
at …
```

ORC-735: ConvertTool should not fail at a single ORC file.

---

java/bench/pom.xml

This PR aims to upgrade Hive library from 2.3.3 to 3.1.2 in benchmark module.
To depend on the latest one.
Manual.
```bash
$ mvn package
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ORC Benchmarks 1.7.0-SNAPSHOT:
[INFO] 
[INFO] ORC Benchmarks ..................................... SUCCESS [  1.066 s]
[INFO] ORC Benchmarks Core ................................ SUCCESS [  7.244 s]
[INFO] ORC Benchmarks Hive ................................ SUCCESS [  9.738 s]
[INFO] ORC Benchmarks Spark ............................... SUCCESS [ 21.330 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------ …
```

ORC-736: Upgrade Hive to 3.1.2

---

java/tools/pom.xml
java/tools/src/java/org/apache/orc/tools/convert/CsvReader.java
java/tools/src/java/org/apache/orc/tools/convert/JsonReader.java
java/tools/src/test/org/apache/orc/tools/convert/TestJsonReader.java

* CSV and Json converters can now take in columns with date format instead of throwing an error on invalid type
* Removed threetenbp date/time library with standard java version
* Datetimes support OffsetDateTime formats, e.g. 2021-01-18T12:34:56.123+04:00
* Create timestamps from converting to Instant rather than manually setting seconds and nanos
Date is a common datatype and should be supported instead of using hack with timestamps at 00:00:00
threetenbp library outdated and is not necessary for java 8+
Datetime formats should allow for OffsetDateTime as well as ZonedDateTime and LocalDateTime formats for full iso8601 compatibility
TestJsonReader.testDateTypeSupport
TestJsonReader.testDateTimeTypeSupport

ORC-738: Add date type conversion support in `Java Tools`

---

java/CMakeLists.txt

This PR aims to replace `mvn` with `mvnw` in `java.CMakeLists.txt`.
Some old OSes like CentOS7 may have the old Maven installation. Maven Wrapper will prevent build and test failures.
Pass the CIs and manually do the following.
```
$ cd docker
$ ./run-one.sh local ORC-739 centos7
...
exec: curl --silent --show-error -L https://www.apache.org/dyn/closer.lua?action=download&filename=/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
Using `mvn` from path: /root/orc/java/build/apache-maven-3.6.3/bin/mvn
...
Using `mvn` from path: /root/orc/java/build/apache-maven-3.6.3/bin/mvn
[INFO] Scanning for projects...
...
Test project /root/build
Start 1: orc-test
1/3 Test #1: orc-test .........................   Passed    6.72 sec
Start 2: java-test
2/3 Test #2: java-test …
```

ORC-739: Use Maven Wrapper in java/CMakeLists.txt

---

README.md

This PR aims to update README.md with new travis-ci.com links.
https://issues.apache.org/jira/browse/INFRA-21354 migrated Apache ORC Travis CI from travis-ci.org to travis-ci.com.
1. Since we migrated, travis-ci.com is triggered on this PR correctly.
- https://travis-ci.com/github/apache/orc/builds/214961084
2. Manually click the new links.

ORC-745: Update README.md with new travis-ci.com links

---

.github/workflows/build_and_test.yml
java/core/src/findbugs/exclude.xml
java/pom.xml
java/tools/src/findbugs/exclude.xml

This change makes the analyze profile also run checkstyle:check. It pulls the manual rat and checkstyle checks into cmake's build.

ORC-749 Add checkstyle:check to analyze profile.

---

c++/src/ColumnReader.cc

C++ ORC ColumnReaders of some types have cached buffer state to issue next I/O. This is fine if we read streams continuously. However, if we try to skip some row groups and seek to a random row group, the cached buffer state is wrong and may lead to undefined behavior. This patch fixes it by clearing all stream states in the ColumnReader.
This fix is a prerequisite to introduce PPD to C++ ORC reader in that the read pattern requires seeking to any row group.
This is a trivial fix and just make sure it doesn't break any unit test case.

ORC-753: [C++] Clear stream state of ColumnReader after seek

---

c++/include/orc/Reader.hh
c++/src/Options.hh
c++/src/Reader.cc
c++/src/Reader.hh
c++/src/sargs/SargsApplier.cc
c++/src/sargs/SargsApplier.hh
c++/test/CMakeLists.txt
c++/test/TestPredicatePushdown.cc
c++/test/TestReader.cc

1. Use RowReaderOptions to pass SearchArgument to enable PPD.
2. Modify RowReaderImpl::startNextStripe to seek to next matched row group based on sarg evaluation.
3. RowReaderImpl::next seeks to next matched row group based on sarg evaluation.
4. RowReaderImpl::seekToRow also jumps to the 1st matched row group after specified row number.

ORC-751: [C++] Implement Predicate Pushdown for C++ Reader

---

site/develop/make-release.md

This PR aims to fix a typo in make-release.md.
`git co` is an incorrect command because co is from svn. We need to use git checkout instead. 
N/A.

MINOR: Fix typo in make-release.md

---

c++/src/ColumnReader.cc
c++/src/ColumnWriter.cc
c++/test/TestWriter.cc

The Java ORC reader takes one second off from timestamp values with negative second and nanosecond greater than 999999. The C++ ORC reader/writer should use same logic to be consistent.
WIthout this fix, we may see data inconsistency of timestamp values from different ORC readers.
It can be tested manually by C++/Java ORC tools.

ORC-763: [C++] Fix ORC timestamp inconsistencies with Java ORC

---

java/bench/core/src/java/org/apache/orc/bench/core/CompressionKind.java
java/bench/core/src/java/org/apache/orc/bench/core/Utilities.java
java/bench/pom.xml

This PR aims to support ZSTD compression at benchmark ORC data.
Apache ORC 1.6+ supports ZSTD compression.
Manually
**PREPARATION**
```
$ mvn clean package
```
**ZSTD ORC DATA GENERATION**
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar generate data -d sales -c zstd -f orc
$ ls -alhR data
data:
total 12K
drwxrwxr-x 3 dongjoon dongjoon 4.0K Mar 22 22:42 .
drwxrwxr-x 7 dongjoon dongjoon 4.0K Mar 22 22:42 ..
drwxrwxr-x 3 dongjoon dongjoon 4.0K Mar 22 22:42 generated
data/generated:
total 12K
drwxrwxr-x 3 dongjoon dongjoon 4.0K Mar 22 22:42 .
drwxrwxr-x 3 dongjoon dongjoon 4.0K Mar 22 22:42 ..
drwxrwxr-x 2 dongjoon dongjoon 4.0K Mar 22 22:42 sales
data/generated/sales:
total 2.5G
drwxrwxr-x 2 dongjoon dongjoon 4.0K Mar 22 22:42 .
drwxrwxr-x 3 dongjoon dongjoon 4.0K …
```

ORC-769: Support ZSTD in ORC data benchmark

---

java/bench/core/pom.xml
java/bench/core/src/java/org/apache/orc/bench/core/convert/avro/AvroWriter.java
java/bench/hive/pom.xml
java/bench/pom.xml

Apache Avro added ZSTD support. This PR aims to upgrade Apache Avro to 1.10.2 in benchmark.
To support ZSTD comparison in benchmark.
```
$ mvn package
$ java -jar core/target/orc-benchmarks-core-*-uber.jar generate data -d sales -c zstd -f avro
$ ls -alh data/generated/sales
total 3.5G
drwxrwxr-x 2 dongjoon dongjoon 4.0K Mar 23 06:03 .
drwxrwxr-x 3 dongjoon dongjoon 4.0K Mar 23 06:03 ..
-rw-r--r-- 1 dongjoon dongjoon 3.5G Mar 23 06:08 avro.zstd
-rw-r--r-- 1 dongjoon dongjoon  28M Mar 23 06:08 .avro.zstd.crc
$ java -jar core/target/orc-benchmarks-core-*-uber.jar scan data -d sales -c zstd -f avro
data/generated/sales/avro.zstd rows: 25000000 batches: 24415
```

ORC-770: Support ZSTD in Avro data benchmark

---

java/bench/spark/pom.xml

This PR aims to fix Spark benchmark jar creation by using the default Maven shade plugin configurations explicitly. Otherwise, the parent pom's configuration is applied.
Since ORC-750, it builds incorrect uber jar. 
```
$ mvn clean package -pl spark --am
$ ls -alh spark/target/*.jar      
-rw-rw-r-- 1 dongjoon dongjoon  62K Mar 23 05:28 spark/target/orc-benchmarks-spark-1.7.0-SNAPSHOT.jar
-rw-rw-r-- 1 dongjoon dongjoon 808K Mar 23 05:28 spark/target/orc-benchmarks-spark-1.7.0-SNAPSHOT-nohive.jar
```
Manually.
```
$ mvn clean package -pl spark --am
$ ls -alh spark/target/*.jar
-rw-rw-r-- 1 dongjoon dongjoon 130M Mar 23 05:56 spark/target/orc-benchmarks-spark-1.7.0-SNAPSHOT.jar
-rw-rw-r-- 1 dongjoon dongjoon  62K Mar 23 05:55 …
```

ORC-772: Fix Spark benchmark jar creation

---

site/specification/ORCv1.md

The corresponding code is https://github.com/apache/orc/blob/master/c%2B%2B/src/BloomFilter.cc#L47.
The code is correct, but the documentation is not. The code is to use `index % 64` which has the same effect as `index & 0x3f`.
```
constexpr uint64_t BITS_OF_LONG = 64;
constexpr uint8_t  SHIFT_6_BITS = 6;
void BitSet::set(uint64_t index) {
mData[index >> SHIFT_6_BITS] |= (1ULL << (index % BITS_OF_LONG));
}
```
The fixes on documentation are
1. There is no need to use `>>>`. We have already flip `combinedHash` if it's negative and `position`  sign bit will be always zero.
2. To set bit we have to mask `position` with 0x3f to keep the least 6 bits.

Update ORCv1.md: Fix documentation about bitset in bloom filter section

---

c++/src/ColumnWriter.cc
c++/test/TestWriter.cc

Add missing Bloom filter update, when new item is added to a binary column.
Even when the Bloom filter is enabled for a binary column, the filter won't be updated. 
Copied the logic from the string column in testBloomFilter.

ORC-773: BinaryColumnWriter does not update Bloom filter

---

c++/src/Compression.cc
c++/test/TestCompression.cc

A new BlockCompressionStream class was implemented, that can be used for LZ4 compression kind.
The C++ Writer doesn't support LZ4 compression. This PR aims to fix that.
The existing compression tests were copied and changed to use LZ4 compression,

ORC-780: Add LZ4 Compression to the C++ Writer

---

java/bench/pom.xml
java/pom.xml

This PR aims to update the slf4j version to 1.7.30.
We are currently using 1.7.5 and 1.7.25, unifying the versions into the latest stable 1.7.30 will bring the latest bug fixes. 
- http://www.slf4j.org/news.html
Pass the CIs.

ORC-782: Update slf4j to 1.7.30

---

java/core/src/java/org/apache/orc/MemoryManager.java
java/pom.xml

This PR aims to add a checkstyle rule to prevent trailing white spaces. 
This will enforce the coding style before merging. 
Pass the CIs or manually do the following.
```
$ cd java
$ mvn checkstyle:check -Panalyze
```

ORC-783: Add a checkstyle rule to prevent trailing white spaces.

---

README.md

Update travis build status to `main`
Change needed after INFRA-21723
N/A

ORC-788: Update travis build status to `main`

---

c++/include/orc/Type.hh
c++/src/ColumnPrinter.cc
c++/src/ColumnReader.cc
c++/src/ColumnWriter.cc
c++/src/Reader.cc
c++/src/Statistics.cc
c++/src/TypeImpl.cc
c++/src/Writer.cc
c++/test/TestType.cc
c++/test/TestWriter.cc
tools/src/CSVFileImport.cc

How was this patch tested?
1. Read and write tests for new TIMESTAMP_INSTANT type columns in unit test WriteTest.writeTimestampInstant
2. build type from the string containing the new TIMESTAMP_INSTANT type in unit test TestType.buildTypeFromString

ORC-666: [C++] support a new TIMESTAMP_INSTANT type

---

c++/src/OrcHdfsFile.cc
tools/src/CMakeLists.txt

1. `buf` pointer is not forwarded after reading a chunk
2.  some tools are not published.

fix orc-scan tool & more tools installed

---

java/core/src/java/org/apache/orc/TypeDescription.java

This patch makes TIMESTAMP_INSTANT a primitive type.

ORC-790: TIMESTAMP_INSTANT should be primitive

---

java/pom.xml

This PR aims to upgrade the guava test dependency to version 30.1.1-jre.
This will use the latest version of guava during testing. 
Pass the CIs.

ORC-791: Upgrade guava test dependency to 30.1.1-jre

---

java/core/src/java/org/apache/orc/impl/reader/ReaderEncryptionVariant.java
java/core/src/test/org/apache/orc/impl/TestCryptoUtils.java
java/core/src/test/org/apache/orc/impl/reader/TestReaderEncryptionVariant.java

This PR aims to prevent NPE due to the invalid key provider configuration.
Invalid key provider configuration returns `null` for provider and causes NPE like the following.
```java
Caused by: java.lang.NullPointerException
at org.apache.orc.impl.reader.ReaderEncryptionVariant.getDecryptedKey(ReaderEncryptionVariant.java:150)
at org.apache.orc.impl.reader.ReaderEncryptionVariant.getFileFooterKey(ReaderEncryptionVariant.java:179)
at org.apache.orc.impl.reader.ReaderEncryptionKey.isAvailable(ReaderEncryptionKey.java:142)
at org.apache.orc.impl.reader.ReaderEncryption.getVariant(ReaderEncryption.java:139)
at org.apache.orc.impl.reader.StripePlanner.buildEncodings(StripePlanner.java:222)
at org.apache.orc.impl.reader.StripePlanner.parseStripe(StripePlanner.java:126)
at …
```

ORC-793: Invalid key provider configuration should not cause NPE

---

c++/src/Compression.cc
c++/src/io/InputStream.cc
c++/src/io/InputStream.hh

The current implementation of ZlibDecompressionStream::seek and
BlockDecompressionStream::seek resets the state of the decompressor
and the underlying file reader and throws away their buffers.
This commit introduces two optimizations which rely on reusing
the buffers that still contain useful data, and therefore reducing
the time spent reading/uncompressing the buffers again.
The first case is when the seeked position is already read
and decompressed into the output stream.
The second case is when the seeked position is already read from
the input stream, but has not been decompressed yet, ie. it's
not in the output stream.
Tests:
- Run the ORC tests, and the Impala tests working on ORC tables.
- The regression that #476 would cause is not present anymore.

ORC-614: [C++] Implement efficient seek() in decompression streams

---

java/core/src/java/org/apache/orc/Writer.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/java/org/apache/orc/impl/WriterImpl.java
java/core/src/test/org/apache/orc/impl/TestWriterImpl.java

It adds a new method to the Writer that lets the user get information about the stripes of the file.
Currently Iceberg has to reopen the file after writing the file and we'd like to short circuit that.
Added a unit test.

ORC-797: Allow writers to get the stripe information.

---

java/bench/pom.xml
java/bench/spark/pom.xml
java/examples/pom.xml
java/pom.xml
java/tools/pom.xml

This PR aims to upgrade Apache Parent pom to the latest version, 23.
- https://github.com/apache/maven-apache-parent/releases/tag/apache-23 
We can remove the redundant information by using the versions from the parent pom.
Pass the CIs.

ORC-796: Upgrade Apache parent pom to version 23

---

c++/src/Reader.cc
c++/src/Reader.hh
c++/src/Vector.cc
tools/test/TestMatch.cc

MapVectorBatch::toString will encounter segment fault if map.value is selected while map.key is not selected.

ORC-800: Add `key` and `value` nullness check in `MapVectorBatch`

---

java/core/src/java/org/apache/orc/impl/BufferChunk.java
java/core/src/java/org/apache/orc/impl/InStream.java
java/core/src/java/org/apache/orc/impl/OrcCodecPool.java
java/core/src/java/org/apache/orc/impl/PhysicalFsWriter.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java

Clean up some logging statements with the project. Remove instances of log-and-throw anti-pattern, remove superfluous logging guards, use anchors in debug statements instead of concatenation.
Trivial performance increases, decrease in lines of code (readability), log-and-throw makes troubleshooting more difficult because the same error may be logged multiple times.
Existing unit tests, but should be no change in functionality.

ORC-801: Clean up Logging

---

.asf.yaml

According to the announcement, we need to add this to our website branch before July 1st.
- https://github.com/apache/infrastructure-website/blob/asf-site/.asf.yaml
To comply ASF Git Web site publishing change.
N/A

ORC-805: Add .asf.yaml for Apache ORC website publishing

---

java/bench/pom.xml

This PR aims to update Spark to version 3.1.2.
The latest version of Spark is 3.1.2.
This will bring the latest improvements. 
Pass the CIs.

ORC-808: Update Spark to 3.1.2

---

java/core/src/test/org/apache/orc/TestVectorOrcFile.java
java/tools/src/test/org/apache/orc/tools/TestFileDump.java
java/tools/src/test/org/apache/orc/tools/TestJsonFileDump.java

ORC-757 introduced HT as the default string dictionary implementation.
testStripeLevelStats need to be updated and existing tests with ORC files written with RBTree dict should use the same dict to avoid size inconsistencies
Fix tests upstream
Passed tests locally

ORC-810: FIX expected Output Stats when using Hash Dictionary

---

c++/src/Compression.cc
c++/test/TestCompression.cc

A new BlockCompressionStream class was implemented for Snappy compression.
The C++ Writer doesn't support Snappy compression. This PR aims to fix that.
The existing compression tests were copied and changed to use Snappy compression.
PR #282 aims for the very same thing, but it's not complete and inactive for a while now. The BlockCompressionStream has been introduced since it was opened, thus it was easier for me to start over from the current state and open a new pull request.
I hope it's not a problem that I've stepped in to add the functionality.

ORC-377: [c++] Add SnappyCompressionStream

---

cmake_modules/ThirdpartyToolchain.cmake

This PR aims to upgrade ZSTD from 1.4.5 to 1.5.0.
This will bring in the latest performance improvements and bugfixes:
- https://github.com/facebook/zstd/releases/tag/v1.5.0
- https://github.com/facebook/zstd/releases/tag/v1.4.9
- https://github.com/facebook/zstd/releases/tag/v1.4.8
- https://github.com/facebook/zstd/releases/tag/v1.4.7
Pass the CIs.

ORC-813: Upgrade ZSTD to 1.5.0

---

java/bench/pom.xml
java/bench/spark/pom.xml

Be explicit about Jackson versioning for the various modules.
Allow main ORC components to use different Jackson version than bench-spark.
Manually build and test benchmark module.

ORC-807: Separate Jackson Versions in benchmark module

---

java/pom.xml

This PR aims to build and test Java module on Apple Silicon.
Currently, the protocol buffer download fails on Apple Silicon.
Manual
```
mvn package -Papplesilicon
```

ORC-814: Build and test Java module on Apple Silicon

---

java/core/src/java/org/apache/orc/impl/WriterImpl.java

This PR aims to simplify getClosestBufferSize by introducing rounding up to the nearest power of 2.
Reduce the amount of code (readability); reduce the number of branches (performance)
Ran unit tests. Code is already covered in existing tests.

ORC-812: Simplify getClosestBufferSize in Writer

---

java/pom.xml

This PR aims to rename and enable aarch64 profile automatically. 
- First, we don't need to specify the profile. 
- Second, `make package` currently fails because it doesn't know the new profile. These changes will make it succeed.
Pass the CIs.

ORC-816: Rename and enable aarch64 profile automatically

---

java/core/src/java/org/apache/orc/impl/MaskDescriptionImpl.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

This PR aims to use `List` instead of `Set` in `MaskDescriptionImpl`.
If there are multiple encrypted columns with the same types for a single key, only the first column is masked.
Pass the CIs with the newly added test cases.

ORC-804: MaskDescriptionImpl should use List instead of Set

---

.asf.yaml

This PR aims to add GitHub repo labels. 
Apache ORC is incorrectly labeled as a database. 
N/A.

MINOR: Add GitHub repo labels

---

.github/workflows/build_and_test.yml

This PR aims to add Java 16 to GitHub Action instead of Java 15 because Java 15 is EOL.
To add Java 16 test coverage and prepare for Java 17 LTS.
Pass the CIs

ORC-820: Add Java 16 to GitHub Action

---

.github/workflows/publish_snapshot.yml
.travis.yml
README.md
java/bench/README.md
site/_docs/building.md
site/develop/make-release.md

This PR uses `mvnw` instead of `mvn` in our build system and documentation.
For consistency.
Pass the CIs.

ORC-821: Use mvnw instead of mvn

---

java/bench/pom.xml
java/examples/pom.xml
java/pom.xml
java/tools/pom.xml

This PR aims to upgrade maven-assembly-plugin to 3.3.0.
This is required to build with Java 17.
Pass the CIs.

ORC-823: Upgrade maven-assembly-plugin to 3.3.0

---

java/bench/core/pom.xml
java/bench/hive/pom.xml
java/bench/pom.xml
java/bench/spark/pom.xml
java/examples/pom.xml
java/pom.xml
java/tools/pom.xml

Upgrade Apache Parent POM to version 23 and clean up superfluous Maven POM elements
Get benefits from upgraded maven plugins. Simplification.
Existing unit tests.

ORC-806: Upgrade to Apache POM 23

---

java/core/src/java/org/apache/orc/impl/RunLengthIntegerReaderV2.java

The number of iterations of the loops in RunLengthIntegerReaderV2 nextVector look at two distinct, but known, values. Instead of check each value in each loop, pre-compute the batch size.
Code clarity, and if the optimizer doesn't already do it automagically, saves a few branches.
No changes in functionality.  Uses existing unit tests.

ORC-833: Calculate nextVector Batch Size Once

---

java/core/src/java/org/apache/orc/impl/Dictionary.java
java/core/src/java/org/apache/orc/impl/DictionaryUtils.java
java/core/src/java/org/apache/orc/impl/DynamicByteArray.java
java/core/src/java/org/apache/orc/impl/StringHashTableDictionary.java
java/core/src/java/org/apache/orc/impl/StringRedBlackTree.java
java/core/src/java/org/apache/orc/impl/writer/StringBaseTreeWriter.java

The code to flush first loads (copies) the data into a Text object and then writes it to the direct stream. Instead, pass the directStream to the dictionary and have it write directly to the stream instead of an intermediate Text object.
Performance.
No change in behavior so using existing unit tests.

ORC-831: Do Not Copy String When Flushing Dictionary

---

java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java

When converting from Double to String, use the Double class methods directly. Lower overhead of encoding by using ASCII.
Performance.
No change in functionality.  Use existing unit tests.

ORC-836: StringGroupFromDoubleTreeReader Use Double toString

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java

Remove Superfluous Array Fill in RecordReaderImpl.
Less code. Performance.
No changes in functionality. Use existing unit tests.

ORC-840: Remove Superfluous Array Fill in RecordReaderImpl

---

java/core/src/java/org/apache/orc/impl/RunLengthIntegerReaderV2.java

Remove unused code in RunLengthIntegerReaderV2
Minor cleanup to remove code. Less is more.
No changes in functionality. Use existing unit tests.

ORC-855: Remove Unused isRepeating from RunLengthIntegerReaderV2

---

java/pom.xml

This PR aims to update maven-checkstyle-plugin to 3.1.2 and checkstyle to 8.44.
This will bring the bug fixes of 8.30 ~ 8.44.
- https://checkstyle.sourceforge.io/releasenotes.html
Pass the GHA.

ORC-859: Update maven-checkstyle-plugin to 3.1.2 and checkstyle to 8.44

---

CMakeLists.txt

This PR aims to bump CMake minimum requirement from 2.6 to 2.8.12.
As of today, we are currently using CMake 3.21.0 and hitting this warning because our minimum requirement is 2.6.
```
$ cmake --version
cmake version 3.21.0
$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:13 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
Pass the CIs

ORC-861: Bump CMake minimum requirement to 2.8.12

---

docker/centos8/Dockerfile

This PR aims to add libarchive to centos8 docker image. 
```
% docker run -it --rm centos:8
[root@917a5c3b68ac /]# yum install -y -q cmake
Failed to set locale, defaulting to C.UTF-8
warning: /var/cache/dnf/appstream-02e86d1c976ab532/packages/cmake-3.18.2-11.el8_4.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
Importing GPG key 0x8483C65D:
Userid     : "CentOS (CentOS Official Signing Key) <security@centos.org>"
Fingerprint: 99DB 70FA E1D7 CE22 7FB6 4882 05B5 55B3 8483 C65D
From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
[root@917a5c3b68ac /]# cmake
cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd
[root@917a5c3b68ac /]# yum install -y -q libarchive
Failed to set locale, defaulting to C.UTF-8
[root@917a5c3b68ac /]# cmake
Usage …
```

ORC-862: Add libarchive to centos8 docker image.

---

.github/dependabot.yml

This PR aims to add `dependabot` with a weekly schedule.
This one makes PRs to us and we can pin the dependencies when they are incompatible.
For example, Apache Avro and Druid projects are using this like that.
- https://github.com/apache/avro/blob/master/.github/dependabot.yml
- https://github.com/apache/druid/blob/master/.github/dependabot.yml
- This will keep ORC community up-to-date
- This will make the ORC community more efficiently by removing the burden of new dependency monitoring.
- This will convert the implicit knowledges about `incompability` to the community-wide explicit one.
N/A

ORC-860: Add dependabot

---

java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/TimestampRowFilterBenchmark.java
java/core/src/java/org/apache/orc/impl/Dictionary.java
java/core/src/java/org/apache/orc/impl/DictionaryUtils.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/java/org/apache/orc/impl/RunLengthIntegerReaderV2.java
java/core/src/java/org/apache/orc/impl/SerializationUtils.java
java/core/src/java/org/threeten/extra/chrono/HybridDate.java
java/pom.xml
java/shims/src/java/org/apache/orc/impl/ZeroCopyShims.java

This PR aims to enforce the maximum line length in Java file from 125 to 120.
ORC-795 started LineLength rule with 125 maximum at Apache ORC 1.6.8.
This issue aims to enforce it with 120 at Apache ORC 1.7.0.
Pass the CIs with the new 120 limit.

ORC-866: Reduce LineLength from 125 to 120

---

.github/dependabot.yml

This PR aims to pin `gson` to 2.2.4 explicitly.
Apache Hive 4.0 is still using 2.2.4 and Spark 3.1.2 distribution also has 2.2.4 due to that.
- https://github.com/apache/hive/blob/master/pom.xml#L219
```
<gson.version>2.2.4</gson.version>
```
N/A. This will inform `dependabot` to ignore son 2.3+.
This closes #766 .

ORC-868: Pin gson to 2.2.4

---

java/pom.xml
java/tools/src/java/org/apache/orc/tools/convert/CsvReader.java

This PR aims to bump opencsv from 3.9 to 5.5.1.
To bring the latest improvements and bug fixes:
- http://opencsv.sourceforge.net/project-info.html
Pass the CIs with the existing `TestCsvReader` suite.
Closes #768

ORC-865: Bump opencsv from 3.9 to 5.5.1

---

.github/dependabot.yml

This PR aims to pin `jmh` to 1.20.
As we see the test result (https://github.com/apache/orc/pull/769), the upgrade needs more efforts. ORC-870 will handle it later.
N/A
Closes #769

ORC-869: Pin jmh 1.20

---

cmake_modules/FindCyrusSASL.cmake

This PR aims to use the package name `CyprusSASL` at `find_package_handle_standard_args`.
```cmake
-find_package_handle_standard_args(CYRUS_SASL DEFAULT_MSG
+find_package_handle_standard_args(CyrusSASL DEFAULT_MSG
```
Currently, it shows a warning like the following.
```
CMake Warning (dev) at /opt/homebrew/Cellar/cmake/3.21.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
The package name passed to `find_package_handle_standard_args` (CYRUS_SASL)
does not match the name of the calling package (CyrusSASL).  This can lead
to problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
cmake_modules/FindCyrusSASL.cmake:46 (find_package_handle_standard_args) …
```

ORC-873: Fix FindCyrusSASL to use the package name CyrusSASL

---

java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java

Cache byte value for TRUE and FALSE strings.
Performance.
No change in functionality. Uses existing unit tests.

ORC-835: Cache TRUE/FALSE Bytes in StringGroupFromBooleanTreeReader

---

java/bench/README.md
java/bench/fetch-data.sh

This PR aims to update `READM.md` in bench submodule and allow user environment shell in `fetch-data.sh`.
- ORC-821 added `mvnw` in the parent directory.
- Since ORC-354, `-Pbenchmark` is recommended.
- In some OS environments, `/bin/bash` is too old to run the script.
Pass the CIs.

ORC-885: Update bench README.md and allow user env shell

---

java/core/pom.xml
java/pom.xml

This PR aims to remove `hamcrest-core` test dependency.
This was added at ORC-60 and is not used now.
```
$ git show 08b854425 | grep hamcrest
+      <groupId>org.hamcrest</groupId>
+      <artifactId>hamcrest-core</artifactId>
+        <groupId>org.hamcrest</groupId>
+        <artifactId>hamcrest-core</artifactId>
```
Pass the CIs.
This closes #778 .

ORC-882: Remove hamcrest-core test dependency

---

java/core/src/java/org/apache/orc/impl/SerializationUtils.java

Optimize ORC's readFully method for a condition where the buffer is always fully read.
Better performance reading Float/Long/Double values.
No change in functionality. Use existing unit tests.

ORC-854: Optimize ReadFully for Full Reads

---

site/news/index.html

This PR aims to remove ORC Twitter link from `news` page.
The twitter account has not used during last 3 years since 2018.
N/A (We need to update `asf-website` branch after merging)

ORC-887: Remove ORC Twitter link from news page

---

java/pom.xml

This PR aims to add a filtering rule at `maven-shade-plugin` to remove a build warning due to the overlapping resources.
We had better remove this warnings on `orc-mapreduce` module before Apache ORC 1.7.0 release.
```
[INFO] --- maven-shade-plugin:3.2.4:shade (default) @ orc-mapreduce ---
[INFO] Including com.google.protobuf:protobuf-java:jar:2.5.0 in the shaded jar.
[INFO] Including org.apache.hive:hive-storage-api:jar:2.7.2 in the shaded jar.
[INFO] Excluding org.apache.orc:orc-core:jar:1.8.0-SNAPSHOT from the shaded jar.
[INFO] Excluding org.apache.orc:orc-shims:jar:1.8.0-SNAPSHOT from the shaded jar.
[INFO] Excluding io.airlift:aircompressor:jar:0.19 from the shaded jar.
[INFO] Excluding javax.xml.bind:jaxb-api:jar:2.2.11 from the shaded jar.
[INFO] Excluding …
```

ORC-889: Remove orc-mapreduce build warnings due to overlapping resources

---

.github/dependabot.yml

This PR aims to pin the minimum support Hadoop version to 2.2.0.
We have `min.hadoop.version` for three dependencies. We need to pin them all.
```
$ git grep -C1 min.hadoop.version
java/pom.xml-
java/pom.xml:    <min.hadoop.version>2.2.0</min.hadoop.version>
java/pom.xml-    <hadoop.version>2.7.3</hadoop.version>
--
java/pom.xml-        <artifactId>hadoop-common</artifactId>
java/pom.xml:        <version>${min.hadoop.version}</version>
java/pom.xml-        <scope>provided</scope>
--
java/pom.xml-        <artifactId>hadoop-hdfs</artifactId>
java/pom.xml:        <version>${min.hadoop.version}</version>
java/pom.xml-        <scope>provided</scope>
--
java/pom.xml-        <artifactId>hadoop-mapreduce-client-core</artifactId>
java/pom.xml:        <version>${min.hadoop.version}</version> …
```

ORC-890: Pin minimum support Hadoop version to 2.2.0

---

java/core/src/test/org/apache/orc/TestInMemoryKeystore.java
java/core/src/test/org/apache/orc/TestOrcNullOptimization.java
java/core/src/test/org/apache/orc/TestOrcTimestampPPD.java
java/core/src/test/org/apache/orc/TestOrcTimezone1.java
java/core/src/test/org/apache/orc/TestOrcTimezonePPD.java
java/core/src/test/org/apache/orc/TestRowFilteringComplexTypes.java
java/core/src/test/org/apache/orc/TestRowFilteringIOSkip.java
java/core/src/test/org/apache/orc/TestRowFilteringNoSkip.java
java/core/src/test/org/apache/orc/TestRowFilteringSkip.java
java/core/src/test/org/apache/orc/TestStringDictionary.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java
java/core/src/test/org/apache/orc/impl/TestPredicatePushDownBounds.java
java/core/src/test/org/apache/orc/impl/TestStringHashTableDictionary.java
java/core/src/test/org/apache/orc/util/TestOrcUtils.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcFileEvolution.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcStruct.java
java/tools/src/test/org/apache/orc/tools/TestFileDump.java

This PR aims to use `assertXXX` methods directly without their package name, `Assert`.
```java
-import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
@@ -194,12 +193,12 @@ public class TestFileDump {
if (actualLine != null) {
actualLine = actualLine.trim();
}
-      Assert.assertEquals(expectedLine, actualLine);
+      assertEquals(expectedLine, actualLine);
```
There are three benefits after this PR.
- This reduces the heterogeneity in the test suites which uses both `assertEquals` and `Assert.assertEquals` at the same time currently.
- It's easy to remove the JUnit5 `vintage` engine and migrate to the real JUnit5. Although ORC-687 upgraded to JUnit5, our test cases are still using JUnit5 engine.
- It reduces the length of lines. We are gradually reducing the maximum …

ORC-891: Use assert methods without package name

---

.github/dependabot.yml

This PR aims to pin scala-library to 2.12.10.
Apache Spark 3.1 uses 2.12.10 
N/A
This closes #796 .

ORC-892: Pin scala-library to 2.12.10

---

java/shims/pom.xml
java/shims/src/test/org/apache/orc/impl/TestHadoopShimsPre2_7.java

This PR aims to remove junit-vintage-engine from shims module. 
This will complete the migration to JUnit 5 in `shims` module. 
Pass the CIs.

ORC-893: Remove junit-vintage-engine from shims module

---

java/bench/core/pom.xml
java/bench/pom.xml

This PR aims to use `snappy-java` 1.1.8.4 instead of the one (1.1.8) of `parquet-hadoop` dependency.
To support benchmark in Apple Silicon, we need to use 1.1.8.2+.
- https://github.com/xerial/snappy-java/releases/tag/1.1.8.2
Support Apple Silicon (M1, Mac-aarch64)
Otherwise, we hit the following error.
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar generate data -d sales -f parquet
Processing sales [parquet]
[WARN ] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
```
Manually.
```
$ cd java
$ ./mvnw clean package -DskipTests -Pbenchmark
$ cd bench
$ java -jar …
```

ORC-895: Use snappy-java 1.1.8.4 in bench/core to support Apple Silicon

---

java/core/src/java/org/apache/orc/OrcFile.java

```java
private static boolean sameKeys(EncryptionKey[] first,
EncryptionKey[] next) {
if (first.length != next.length) {
return false;
}
for(int k = 0; k < first.length && k < next.length; ++k) {
if (!first[k].getKeyName().equals(next[k].getKeyName()) ||
first[k].getKeyVersion() != next[k].getKeyVersion() ||
first[k].getAlgorithm() != next[k].getAlgorithm()) {
return false;
}
}
return true;
}
```
There are five similar codes.
The length of `first` and `next` are the same, otherwise the loop is unreachable.
k <next.length is redundant conditions.
I think they can be removed.
Optimization loop termination condition in readerIsCompatible method
Pass the CIs.

ORC-897: Optimization loop termination condition

---

site/_data/releases.yml

This PR aims to mark `Apache ORC 1.4.5` as `archived` instead of `stable`.
- http://orc.apache.org/docs/releases.html
Most community are currently using Apache ORC 1.5.x and moved on Apache ORC 1.6.9 already.
- 2021-07-02 Apache ORC 1.6.9 is released.
- 2021-07-02 SPARK-35992: Upgrade ORC to 1.6.9
- 2021-07-16 ICEBERG: Upgrade ORC to 1.6.9
- 2021-07-26 HIVE-25384: Bump ORC to 1.6.9
- 2021-07-30 ARROW-13506: Upgrade ORC to 1.6.9
- 2021-07-31 Apache Druid: Upgrade ORC to 1.6.9
- (Under Review) FLINK-23551 Bump ORC to 1.6.9
Apache ORC 1.4 was released on 2019-12-09 and it's time to mark it `archived` because we are not going to maintain it.
Apache ORC 1.0/1.1/1.2/1.3 are marked as `archived` explicitly.
N/A

ORC-899: Archive Apache ORC 1.4.x in `releases` page

---

site/doap_orc.rdf

This PR aims to update `doap_orc.rdf` file.
The following Apache Projects page is populated from `doap_orc.rdf`. We need to keep it up-to-date. For example, we need to show `1.6.9 (2021-07-02): Apache ORC 1.6.9` instead `1.4.3 (2018-02-09): Apache ORC 1.4.3`.
- https://projects.apache.org/project.html?orc
N/A

ORC-900: Update doap_orc.rdf for Apache Projects page

---

java/mapreduce/pom.xml
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcFileEvolution.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcList.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcMap.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcOutputFormat.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcStruct.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcTimestamp.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcUnion.java
java/mapreduce/src/test/org/apache/orc/mapreduce/TestMapreduceOrcOutputFormat.java
java/pom.xml
java/tools/pom.xml
java/tools/src/test/org/apache/orc/impl/TestHadoopKeyProvider.java
java/tools/src/test/org/apache/orc/impl/TestRLEv2.java
java/tools/src/test/org/apache/orc/tools/TestFileDump.java
java/tools/src/test/org/apache/orc/tools/TestJsonFileDump.java
java/tools/src/test/org/apache/orc/tools/convert/TestCsvReader.java
java/tools/src/test/org/apache/orc/tools/convert/TestJsonReader.java
java/tools/src/test/org/apache/orc/tools/json/TestJsonSchemaFinder.java

This PR aims to remove old dependencies from `mapreduce` and `tools` modules by removing `junit-vintage-engine`.
- `junit-jupiter-api` is added.
- `junit-jupiter-params` is added to replace the JUnit4's parameterized test class.
- Remove unused `objenesis` and `net.bytebuddy` from `mapreduce` module.
This will complete the JUnit5 migration in these modules.
Pass the CIs.

ORC-901: Remove junit-vintage-engine from `mapreduce/tools` module

---

java/pom.xml

This is to get HIVE-25400 & HIVE-25190 fixed.

ORC-906: Move to storage-api 2.7.3.

---

java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java
java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java

This PR removes `commons-lang` usage.
Although ORC-734 removed commons-lang usage from Apache ORC in favor of lang3, ORC-742 seems to bring it back.
Pass the CIs.

MINOR: Remove org.apache.commons.lang usage

---

java/core/src/test/org/apache/orc/impl/TestRecordReaderImpl.java
java/pom.xml

This PR aims to upgrade `hive-storage-api` from 2.7.2 to 2.8.1.
This will bring the latest improvement and bug fixes.
Pass the CIs.

ORC-867: Upgrade hive-storage-api to 2.8.1

---

java/core/pom.xml
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

This PR aims to migrate `TestVectorOrcFile` to JUnit5.
`TestVectorOrcFile` is one of the largest test file in ORC which has 4768 lines.
This is the first step to migrate `core` module. The others are smaller than this.
Pass the CIs.
**BEFORE**
```
$ mvn test -pl core -Dtest=org.apache.orc.TestVectorOrcFile
[WARNING] Tests run: 147, Failures: 0, Errors: 0, Skipped: 18, Time elapsed: 6.669 s - in org.apache.orc.TestVectorOrcFile
```
**AFTER**
```
$ mvn test -pl core -Dtest=org.apache.orc.TestVectorOrcFile
[WARNING] Tests run: 147, Failures: 0, Errors: 0, Skipped: 18, Time elapsed: 6.844 s - in org.apache.orc.TestVectorOrcFile
```

ORC-903: Migrate TestVectorOrcFile to JUnit5

---

java/core/src/java/org/apache/orc/impl/DictionaryUtils.java
java/core/src/java/org/apache/orc/impl/StringHashTableDictionary.java

When there is a collision adding a value into a StringHashTableDictionary, a temp Text object is created and then each value in the byte array is copied into the temp Text until a match is found (or worst-case scenario, a match is not found and every value is loaded).
Instead of loading (copying) the values, just compare directly against the byte array without copying the data into a intermediate (temp) buffer.
Performance.  StringTreeWriter#writeBatch() consumes some number the cycles, much of which is spent in getText().  By Changing this getText() implementation (removing the copy), the number of cycles consumed is decreased measurably.
No functionality change, utilized existing unit tests.

ORC-830: Do Not Copy String When Adding to StringHashTableDictionary

---

java/pom.xml

This PR aims to use `https` instead of `http` for website links in `pom.xml`.
To introduce safer links.
N/A

ORC-908: Use https instead of http for website links in 'pom.xml'

---

java/core/src/java/org/apache/orc/impl/IOUtils.java
java/core/src/java/org/apache/orc/impl/RunLengthByteReader.java
java/core/src/java/org/apache/orc/impl/SerializationUtils.java

This PR aims to remove `commons-io` v2.1 dependency which comes from `Hadoop 2.2.0`.
- https://mvnrepository.com/artifact/org.apache.orc/orc-core/1.6.9
This is a hidden dependency due to four lines using a single function `IOUtils.skipFully`. We had better cut this.
```
$ git grep org.apache.commons.io
core/src/java/org/apache/orc/impl/RunLengthByteReader.java:import org.apache.commons.io.IOUtils;
core/src/java/org/apache/orc/impl/SerializationUtils.java:import org.apache.commons.io.IOUtils;
```
```
$ git grep IOUtils | grep -v import
core/src/java/org/apache/orc/impl/RunLengthByteReader.java:        IOUtils.skipFully(input,1);
core/src/java/org/apache/orc/impl/RunLengthByteReader.java:        IOUtils.skipFully(input, numSkipRows); …
```

ORC-909: Remove commons-io v2.1 dependency

---

java/bench/pom.xml
java/bench/spark/pom.xml

This PR aims to remove `janino` runtime dependency from `bench` module in favor of Spark's transitive dependency.
We should not override it. Spark uses a specific version because some latest Janino has bugs.
Pass the CIs.
Closes #799 and #804 .

ORC-911: Remove janino dependency in favor of Spark's transitive dependency

---

java/bench/pom.xml
java/bench/spark/pom.xml

This PR aims to exclude Spark's transitive avro/parquet dependency and some duplicate META-INF files from Spark benchmark uber jar.
Spark benchmark excludes ORC dependencies in order to measure the performance of our branches.
In the same way, we should exclude Spark's transitive Parquet/Avro dependencies and some duplicated files.
Manual.
```
// Run on the prepared the benchmark data according to the README.md
$ java -jar spark/target/orc-benchmarks-spark-1.8.0-SNAPSHOT.jar spark data
Records: 22773249
Invocations: 1
io: 81
Bytes: 1333069106
10393911.120 us/op
...
```

ORC-912: Exclude Spark transitive avro/parquet dependency from Spark benchmark

---

java/bench/pom.xml
java/bench/spark/pom.xml

This PR aims to remove `io.netty:netty` dependency from Spark benchmark.
```
$ ls spark-2.4.8-bin-hadoop2.7/jars/netty-*
spark-2.4.8-bin-hadoop2.7/jars/netty-3.9.9.Final.jar      spark-2.4.8-bin-hadoop2.7/jars/netty-all-4.1.47.Final.jar
$ ls spark-3.1.2-bin-hadoop3.2/jars/netty-all-4.1.51.Final.jar
spark-3.1.2-bin-hadoop3.2/jars/netty-all-4.1.51.Final.jar
```
Manual.
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar generate data -d sales -c none -f orc
$ java -jar spark/target/orc-benchmarks-spark-1.8.0-SNAPSHOT.jar spark data
```
This closes #794

ORC-915: Remove `io.netty:netty` from Spark benchmark

---

java/bench/core/src/java/org/apache/orc/bench/core/convert/GenerateVariants.java
java/bench/spark/src/java/org/apache/orc/bench/spark/SparkBenchmark.java

This PR aims to support data/format/compress options in Spark benchmark.
This will make Spark benchmark more controllable. 
This extension does not appear in -h option, however, it will work. 
Manual
```
java -jar spark/target/orc-benchmarks-spark-1.8.0-SNAPSHOT.jar spark data -d sales -c snappy -f orc
```

ORC-913: Support data/format/compress options in Spark benchmark

---

.github/dependabot.yml

This PR aims to pin `maven-dependency-plugin` to 3.1.2.
There are multiple bugs like MDEP-753, MDEP-757, MDEP-759.
N/A
Closes #820

ORC-914: Pin `maven-dependency-plugin` to 3.1.2

---

.github/dependabot.yml

This PR aims to pin protobuf-java version to 2.5.0
To avoid incompatibility risk.
N/A
Closes #828 .

ORC-918: Pin protobuf-java to 2.5.0

---

java/bench/spark/pom.xml

This PR aims to use the same objenesis version as Spark in Spark benchmark. 
To fix the class not defined error seen below
```
java.lang.NoClassDefFoundError: org/objenesis/strategy/InstantiatorStrategy
at org.apache.orc.mapred.OrcInputFormat.setSearchArgument(OrcInputFormat.java:97)
at org.apache.orc.mapreduce.OrcInputFormat.setSearchArgument(OrcInputFormat.java:57)
at org.apache.spark.sql.execution.datasources.orc.OrcFileFormat.$anonfun$buildReaderWithPartitionValues$5(OrcFileFormat.scala:190)
```
Manual. 
```
java -jar spark/target/orc-benchmarks-spark-1.8.0-SNAPSHOT.jar spark data -d sales -c snappy -f orc
```

ORC-919: Spark bench objenesis should be the same as Spark

---

java/pom.xml

This PR aims to define `junit.version` and `mockito.version` properties and use it.
In addition, `junit.version` is updated to 5.7.2.
Currently, `Dependabot` makes separate PRs per dependencies.
This will advise it to make one PR in the future.
Pass the CIs.
Closes #831

ORC-920: Use junit.version and mockito.version property and bump junit to 5.7.2

---

java/pom.xml

This PR aims to bump Apache parent pom to 24 and add `project.build.outputTimestamp` property to comply with the new enforcement. However, Apache ORC project is using `reproducible-build-maven-plugin` already since ORC-504.
To use the latest Apache pom file.
Pass the CIs.
Closes #834.

ORC-923: Bump apache from 23 to 24

---

java/bench/hive/src/findbugs/exclude.xml
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/BooleanRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/DecimalRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/DoubleRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/RowFilterInputState.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/StringRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/TimestampRowFilterBenchmark.java

Create a new class RowFilterInputState to hold duplicate code.
`filterValues`, `generateRandomSet` and `customIntRowFilter` previously existed in different internal classes as static variables/methods and do not affect each other. After refactoring, they were changed to instance variables/methods to avoid interaction between different benchmarks.
Easier to maintain.
Pass the CIs.

ORC-927: Extracting duplicate codes for RowFilterBenchmark

---

java/tools/src/java/org/apache/orc/tools/FileDump.java

ORC-929: Fix NaN error at orc-tools meta command

---

java/core/src/java/org/apache/orc/impl/RunLengthIntegerWriterV2.java

RunLengthIntegerWriterV2.java
512-546 line
```java
if (diffBitsLH > 1) {
for (int i = 0; i < numLiterals; i++) {
baseRedLiterals[i] = literals[i] - min;
}
brBits95p = utils.percentileBits(baseRedLiterals, 0, numLiterals, 0.95);
brBits100p = utils.percentileBits(baseRedLiterals, 0, numLiterals, 1.0);
if ((brBits100p - brBits95p) != 0 && Math.abs(min) < BASE_VALUE_LIMIT) {
encoding = EncodingType.PATCHED_BASE;
preparePatchedBlob();
return;
} else {
encoding = EncodingType.DIRECT;
return;
}
} else {
// if difference in bits between 95th percentile and 100th percentile is
// 0, then patch length will become 0. Hence we will fallback to direct
encoding = EncodingType.DIRECT;
return;
}
```
All three conditional branch logics have been completed and the return statement is redundant.
691-704 …

ORC-931: Modify RunLengthIntegerWriterV2 code to improve readability

---

java/bench/core/src/java/org/apache/orc/bench/core/convert/GenerateVariants.java
java/bench/core/src/java/org/apache/orc/bench/core/convert/ScanVariants.java

This PR aims to ignore unsupported JSON x ZSTD combination in bench.
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar generate data -d sales -c zstd -s 1
Processing sales [avro, json, orc, parquet]
[WARN ] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.IllegalArgumentException: Unhandled kind ZSTD
```
Manually.
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar generate data -d sales -c zstd -s 1
Processing sales [avro, json, orc, parquet]
```
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar scan data -d sales -c zstd
[WARN ] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
data/generated/sales/avro.zstd rows: 1 …
```

ORC-930: Ignore unsupported JSON x ZSTD combination in bench

---

java/pom.xml

This PR removes `threetenbp` dependency because it's removed at Apache ORC 1.7.0 via ORC-738
- https://github.com/apache/orc/pull/631/files#diff-1108423b084c5105f5c0309e48278ea6b98c7fd3c95d37df984bd1139a2699d6L81-L84
This is not used.
```
$ git grep org.threeten.bp | wc -l
0
```
Manual.
This closes #827 .

ORC-939: Remove threetenbp dependency

---

.github/workflows/build_and_test.yml
.travis.yml

This PR aims to migrate the following jobs from `Travis CI` to `GitHub Action`.
- Mac OS 10.15
- Mac OS 11.5
This job takes 40-minutes execution time and waits in the queue over 6 hours frequently while GitHub Action jobs finish in around 20 minutes in total.
- https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
- System Version: macOS 10.15.7 (19H1323)
- https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md 
- System Version: macOS 11.5 (20G71)
Pass the CIs.

ORC-941: Move `MacOS 10.15/11.5` test from Travis to GitHub Action

---

.gitignore

This PR aims to add `.java-version` to `.gitignore`.
This is convenient when we use `jenv` to test various Java versions. 
Manual
```
$ touch .java-version
$ git status
On branch jenv
Your branch is up to date with 'dongjoon/jenv'.
nothing to commit, working tree clean
```

MINOR: Add `.java-version` to `.gitignore`

---

java/core/pom.xml
java/core/src/java/org/apache/orc/impl/mask/SHA256MaskFactory.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java
java/core/src/test/org/apache/orc/impl/mask/TestSHA256Mask.java
java/pom.xml

This PR aims to remove `javax.xml.bind:jaxb-api` dependency.
This was added via ORC-411 to support Java 10+ at Apache ORC 1.4.5.
Since we only use `DatatypeConverter.printHexBinary` API, we can use the similar logic of `commons-codec` `Hex.encodeHexString`.
Pass the CIs with Java8/11/16/17-ea.
Closes #846

ORC-942: Remove javax.xml.bind:jaxb-api dependency

---

java/CMakeLists.txt

This PR aims to add `OUTPUT_QUIET` and `ERROR_QUIET` to suppress Java8 `add-open` error messages
Error messages could be misleading, so we had better suppress it. 
- https://github.com/apache/orc/runs/3324055264
```
Unrecognized option: --add-opens
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
Check the GHA logs on this PR.

ORC-945: Add OUTPUT_QUIET, ERROR_QUIET to suppress Java8 add-open error messages

---

java/CMakeLists.txt

This PR aims to add hive benchmark integration tests. 
To improve test coverage and prevent future regressions. 
Pass the CIs.

ORC-948: Add hive benchmark integration tests

---

java/bench/spark/pom.xml

This PR aims to add more exclusion patterns at Spark bench uber jar building. 
Since ORC-940, it seems that we have more warnings.
This will suppress more new warnings.
Check GHA build logs.

MINOR: Add more exclusion patterns at Spark bench uber jar building

---

java/pom.xml

This PR aims to bump `aircompressor` to 0.20.
To bring the following patch.
- https://github.com/airlift/aircompressor/commit/5e353d056222ea633b79dbead71137d85934ca96
Pass the Cis.

ORC-950: Bump aircompressor to 0.20

---

java/core/src/java/org/apache/orc/impl/DictionaryUtils.java
java/core/src/java/org/apache/orc/util/CuckooSetBytes.java

This PR aims to recover `Javadoc` generation failure.
This is a blocker for new release.
Manually.
```
$ cd java
$ mvn install -DskipTests
$ mvn javadoc:javadoc
```

ORC-954: Fix Javadoc generation failure

---

.github/workflows/build_and_test.yml

This PR aims to add a `javadoc` generation test coverage to prevent a future regression.
Although Javadoc generation is a non-functional step, we had better remove the possibility of VOTE failure completely.
Pass the GitHub Action with the new job.

ORC-955: Add Javadoc generation GitHub Action job

---

java/core/src/java/org/apache/orc/Writer.java

This PR aims to add `since` tag to `org.apache.orc.Writer` interface.
To help ORC developers to check the API availability easily by improving code and Javadoc.
Manual.

ORC-953: Add `since` tag to `org.apache.orc.Writer` interface

---

java/core/src/java/org/apache/orc/RecordReader.java

This PR aims to add `since` tag to `org.apache.orc.Reader` interface.
To help ORC developers to check the API availability easily by improving code and Javadoc.
Manual

ORC-952: Add `since` tag to `org.apache.orc.RecordReader` interface

---

java/core/src/java/org/apache/orc/Reader.java

This PR aims to add `since` tag to `org.apache.orc.Reader` interface.
- The APIs added by ORC-1 is marked as `1.1.0` according to the JIRA release version.
- The followings are the added versions.
- 1.1.0, 1.2.0, 1.3.0, 1.5.0, 1.5.3, 1.5.9, 1.5.11, 1.6.0, 1.7.0
To help ORC developers to check the API availability easily by improving code and Javadoc.
Manual.

ORC-951: Add `since` tag to `org.apache.orc.Reader` interface

---

java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java

When converting Timestamp to Decimal type, do not use String operations.
Performance.
A quick test (hardly definitive, but indicative) shows an order of magnitude (10x) performance improvement:
```java
long t1 = System.nanoTime();
long r = 0;
for (long i = -100_000L; i < 100_000; i++) {
BigDecimal secondsBd = new BigDecimal(i);
BigDecimal nanosBd = new BigDecimal(i).movePointLeft(9);
BigDecimal resultBd = (i >= 0L) ? secondsBd.add(nanosBd) : secondsBd.subtract(nanosBd);
r += resultBd.longValue();
}
long t2 = System.nanoTime();
System.out.println(r);
System.out.println(t2 - t1);
```
No changes to functionality. Use existing unit tests.

ORC-834: Do Not Convert to String in DecimalFromTimestampTreeReader

---

java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java

Create reusable HiveDecimalWritable objects instead of creating a new HiveDecimalWritable for each processed item.
Performance, less garbage collection
No change in functionality. Use existing unit tests.

ORC-837: Reuse HiveDecimalWritable in ConvertTreeReaderFactory

---

java/core/src/java/org/apache/orc/impl/RecordReaderUtils.java

Simplify ByteBufferAllocatorPool Key class. Cache hash value for Key as it's computed more than once: putBuffer to insert into Tree and getBuffer to remove it from tree.
Less code. Performance.
No changes to functionality. Use existing unit tests.

ORC-838: Simplify `compareTo/equals/putBuffer` of ByteBufferAllocatorPool

---

c++/src/sargs/SargsApplier.cc
c++/src/sargs/SargsApplier.hh
c++/test/TestSargsApplier.cc

This patch fixes a crash in the C++ reader when SearchArgument is created on nested columns of collection types (e.g. array/map). Only STRUCT type has field names for subtypes. So we should check the current node type before checking any field names. JIRA description contains details on how to reproduce the crash.
Same as the above.
Added unit tests in c++/test/TestSargsApplier.cc to reproduce the crash and verify the fix on ARRAY and MAP types.

ORC-959: [C++] Fix crash of SargsApplier in finding nested field names

---

java/CMakeLists.txt

This PR aims to build the `benchmark` module always for integration testing. 
Since we always run the integration tests, we need to build the `benchmark` module. Otherwise, those tests will fail when we run manually without any configurations.
Manually.

ORC-963: Build benchmark module always for integration testing

---

c++/include/orc/sargs/SearchArgument.hh
c++/src/sargs/PredicateLeaf.cc
c++/src/sargs/PredicateLeaf.hh
c++/src/sargs/SargsApplier.cc
c++/src/sargs/SearchArgument.cc
c++/src/sargs/SearchArgument.hh
c++/test/TestPredicatePushdown.cc

Currently in the C++ reader, SearchArgumentBuilder only provides interfaces for creating SearchArguments using field column names. Column names can be ambiguous if there are nested struct columns using the same names. Array item column or map key/value columns even don't have names.
This patch addes corresponding interfaces to create SearchArguments using column ids. Refactors some codes using templates to avoid duplicated codes.
As described above and in the JIRA description, we need creating SearchArguments using column ids.
Added end-to-end tests in c++/test/TestPredicatePushdown.cc.

ORC-960: [C++] Support creating SearchArguments using column ids

---

java/core/src/java/org/apache/orc/impl/Dictionary.java
java/core/src/java/org/apache/orc/impl/DictionaryUtils.java
java/core/src/java/org/apache/orc/impl/DynamicByteArray.java
java/core/src/java/org/apache/orc/impl/StringHashTableDictionary.java
java/core/src/java/org/apache/orc/impl/StringRedBlackTree.java
java/core/src/test/org/apache/orc/impl/TestStringHashTableDictionary.java

Allow `DyanmicByteArray` and `Dictionary` to return a ByteBuffer of its content.
Performance.
No change to functionality. Existing unit tests used.

ORC-852: Allow DynamicByteArray to return a ByteBuffer

---

c++/include/orc/sargs/SearchArgument.hh
c++/src/sargs/PredicateLeaf.cc
c++/src/sargs/PredicateLeaf.hh
c++/src/sargs/SearchArgument.cc
c++/src/sargs/SearchArgument.hh
c++/test/TestPredicateLeaf.cc

Add two more interfaces for creating IN-predicate literals using vector. This provide more flexibility that doesn't requires callers know the list size at compilation time.
Described as above.
Add unit test in c++/test/TestPredicateLeaf.cc

ORC-973: [C++] Support providing IN-predicate literals using vector

---

c++/Doxyfile
java/core/src/test/org/apache/orc/TestVectorOrcFile.java
site/_docs/building.md
site/_posts/2017-05-16-new-committer.md
site/_posts/2019-01-10-add-dongjoon.md
site/_posts/2020-11-16-add-panagiotis.md
site/_posts/2021-02-08-panagiotis-pmc.md
site/_posts/2021-04-13-add-william.md

This PR aims to make our codebase and websites a little more neutral.
In addition, it fixes some typos.
Although we are already careful, this will improve our awareness.
N/A

ORC-977: Update webpages and TestVectorOrcFile.java to be more neutral

---

java/core/src/test/org/apache/orc/TestVectorOrcFile.java
java/pom.xml

This PR aims to fix `Overflow detected` failures in ZSTD compression by bringing new aircompressor version.
- https://github.com/airlift/aircompressor/commit/1e364f713390008eada1daa451e7b42cd6647250 (Fix failure when data compressing incompressible data)
`Overflow detected` happens not only for the small buffer, but also for the incompressible data. The following is a link to the JIRA image.
Pass the UTs.

ORC-965: Fix ZSTD 'Overflow detected' failure

---

java/core/src/java/org/apache/orc/impl/WriterImpl.java
java/core/src/test/org/apache/orc/impl/TestWriterImpl.java

This PR aims to fix NPE in TestFlinkOrcReaderWriter.
```java
@Override
public void close() throws IOException {
if (!isClosed) {
try {
if (batch.size > 0) {
writer.addRowBatch(batch);
batch.reset();
}
} finally {
writer.close();
this.isClosed = true;
}
}
}
```
writer.addRowBatch(batch);
```java
.......
checkMemory();
} catch (Throwable t) {
try {
close();
} catch (Throwable ignore) {
// ignore
}
if (t instanceof IOException) {
throw (IOException) t;
} else {
throw new IOException("Problem adding row to " + path, t);
}
}
```
addRowBatch method throws java.lang.OutOfMemoryError causing writerImpl to close twice in TestFlinkOrcReaderWriter case.
The first close already set the rawWriter to null, so the second time throw a NullPointerException.
I added status variables to ensure that close …

ORC-978: Fix NPE in TestFlinkOrcReaderWriter

---

java/checkstyle.xml
java/pom.xml
site/develop/coding.md

Extract checkstyle to a single file.
Added tips to coding.md.
[CheckStyle-IDEA](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea) plugin is very simple to load this checkstyle.xml. This way you get checkstyle errors/warnings already when you are coding.
Pass the CIs.

ORC-982: Extract checkstyle to a single file, help newcomers check code style

---

java/bench/core/src/java/org/apache/orc/bench/core/filter/FilterBench.java
java/bench/core/src/java/org/apache/orc/impl/filter/RowFilterFactory.java
java/bench/core/src/test/org/apache/orc/bench/core/filter/TestFilter.java
java/bench/core/src/test/org/apache/orc/impl/filter/ATestFilter.java
java/bench/core/src/test/org/apache/orc/impl/filter/TestRowFilter.java
java/core/src/java/org/apache/orc/impl/OrcFilterContextImpl.java
java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/java/org/apache/orc/impl/SchemaEvolution.java
java/core/src/java/org/apache/orc/impl/filter/FilterFactory.java
java/core/src/java/org/apache/orc/impl/filter/leaf/LeafFilterFactory.java
java/core/src/java/org/apache/orc/impl/reader/tree/StructBatchReader.java
java/core/src/test/org/apache/orc/TestOrcFilterContext.java
java/core/src/test/org/apache/orc/TestRowFilteringIOSkip.java
java/core/src/test/org/apache/orc/impl/TestOrcFilterContextImpl.java
java/core/src/test/org/apache/orc/impl/filter/ATestFilter.java
java/core/src/test/org/apache/orc/impl/filter/TestAndFilter.java
java/core/src/test/org/apache/orc/impl/filter/TestConvFilter.java
java/core/src/test/org/apache/orc/impl/filter/TestOrFilter.java
java/core/src/test/org/apache/orc/impl/filter/leaf/TestFilters.java

The filter processing incorrectly ignores the case-sensitivity flag for schema supplied by the reader. This fixes this bug and uses the flag in determining field and vector information.
In the absence of this the read incorrectly fails by performing a case-sensitive match even when case-insensitive match was requested by the reader.
Unit Tests were added to verify the failure and subsequently the fix.

ORC-980: Filter processing respects the case-sensitivity flag

---

java/core/src/java/org/apache/orc/OrcConf.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

The new hash table implementation in ORC-757 results in significantly larger ORC files compared to ORC 1.6. Changing the default back to rbtree.

ORC-985: Change default back to rbtree

---

c++/src/Reader.cc

ORC-990: [C++] fix RowReaderImpl::seekToRowGroup
In environment Windows, MSVC 19.12.25835.0 
test DictionaryEncoding.multipleStripesWithIndex failed due to invalid iterators in positionProviders.
```
for (auto rowIndex ... {
// copy index positions for a specific column
positions.push_back({});
auto& position = positions.back();
for (int pos = 0; pos != entry.positions_size(); ++pos) {
position.push_back(entry.positions(pos));             // iterators may be invalidated here due to reallocation
}
positionProviders.insert(std::make_pair(colId, PositionProvider(position))); //    iterator taken here
}
```
test DictionaryEncoding.multipleStripesWithIndex passed with proposed fix

ORC-990: [C++] fix RowReaderImpl::seekToRowGroup

---

java/core/src/java/org/apache/orc/impl/reader/StripePlanner.java
java/core/src/java/org/apache/orc/impl/writer/Decimal64TreeWriter.java
java/core/src/java/org/apache/orc/impl/writer/TreeWriterBase.java
java/core/src/test/org/apache/orc/impl/TestEncryption.java

1. RowIndex is never marked as encrypted.  The StreamName constructor adds encryption to make rowIndex encrypted when needed.
TreeWriterBase.java
```java
public void writeStripe(int requiredIndexEntries) throws IOException {
.....
-    context.writeIndex(new StreamName(id, OrcProto.Stream.Kind.ROW_INDEX), rowIndex);
+    context.writeIndex(new StreamName(id, OrcProto.Stream.Kind.ROW_INDEX, encryption), rowIndex);
.....
}
```
2.  findStreams in StripePlanner.java total offset order and write inconsistency.
finalizeStripe In PhysicalFsWriter.java
> 1. write the unencrypted index streams 
> 2. write the encrypted index streams 
> 3. write the unencrypted data streams
> 4. write the encrypted data streams
```java
@Override
public void finalizeStripe(OrcProto.StripeFooter.Builder …
```

ORC-991: Fix the bug of encrypted column read crash

---

java/pom.xml

While working on another PR, I found the head of main failed in GA with the failure like below. 
```Error:  Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-java-version) on project orc: Execution enforce-java-version of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce: java.lang.ExceptionInInitializerError: null
Error:  -----------------------------------------------------
Error:  realm =    plugin>org.apache.maven.plugins:maven-enforcer-plugin:1.4.1
Error:  strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Error:  urls[0] = file:/Users/runner/.m2/repository/org/apache/maven/plugins/mave …
```

ORC-1001: Bump maven-enforcer-plugin to 3.0.0

---

java/core/pom.xml
java/examples/pom.xml
java/mapreduce/pom.xml
java/pom.xml
java/shims/pom.xml
java/tools/pom.xml

This PR aims to add `java17` profile for Java 17 Unit testing.
This is required because Java 17 is supported by Hadoop 3.3.
Manual. This PR didn't add `activation` intentionally.
```
$ java -version
openjdk version "17" 2021-09-14 LTS
OpenJDK Runtime Environment Zulu17.28+13-CA (build 17+35-LTS)
OpenJDK 64-Bit Server VM Zulu17.28+13-CA (build 17+35-LTS, mixed mode, sharing)
$ mvn package -Pjava17
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:53 min
[INFO] Finished at: 2021-09-16T02:33:07-07:00
[INFO] ------------------------------------------------------------------------
```

ORC-1002: Add `java17` profile to support Java 17 unit testing

---

.github/workflows/build_and_test.yml
java/CMakeLists.txt
java/shims/pom.xml

This PR aims the following.
- Use `Java 17` instead of `Java 17 EA`.
- Remove `Java 16` to save the community testing resources
- Recover GitHub Action CI by using `java17` profile.
- Disable dependency check on `hadoop-hdfs` of `shim` module
Note that there is a TODO (ORC-1003) which fails due to some `shaded` classes.
We will revisit that.
Java 17 is finally available.
Pass the CIs with Java 17.
When we test manually, it passed like the following.
```
$ java -version
openjdk version "17" 2021-09-14 LTS
OpenJDK Runtime Environment Zulu17.28+13-CA (build 17+35-LTS)
OpenJDK 64-Bit Server VM Zulu17.28+13-CA (build 17+35-LTS, mixed mode, sharing)
...
Test project /Users/dongjoon/APACHE/orc-merge/build
Start 1: orc-test
1/7 Test #1: orc-test .........................   Passed    3.41 sec …
```

ORC-1000: Use Java 17 in GitHub Action

---

c++/src/RLEv2.hh
c++/src/RleEncoderV2.cc
java/core/src/java/org/apache/orc/impl/RunLengthIntegerWriterV2.java

1. Make that the java and C++ impl of determineEncoding in RLEV2 are consistent. 
2. Extracts the prepare for Direct or PatchedBase encoding into a separate function (prepareForDirectOrPatchedBase) to avoid code duplication.
The current Java determineEncoding impl is not optimal and may compute ZigzagLiterals and zzBits100p before deciding on DELTA encoding, which is redundant.
The C++ implementation is better, keeping Java consistent with C++.
Pass the CIs.

ORC-1005: Make that the java and C++ impl of determineEncoding in RLEV2 are consistent.

---

c++/src/sargs/ExpressionTree.hh

Include string in ExpressionTree.hh.
Without it the library cannot be built on Windows with newer msvc++ compiler (version 19.29).
Manually, successfully building the library on Windows on a local machine.

ORC-1009: [C++] Missing string include causes build failure with MSVC++

---

java/core/src/java/org/apache/orc/OrcFile.java

Configuring a customized `MemoryManager` is now a public API so changing the comment to reflect the status quo. 
This will fix this.
- https://orc.apache.org/api/orc-core/org/apache/orc/OrcFile.WriterOptions.html#memory-org.apache.orc.MemoryManager-
There's no code change but a comment fixing.

ORC-1015: Update `OrcFile.WriterOptions::memory` javadoc

---

.github/workflows/build_and_test.yml

This PR aims to recover GitHub Action by using `openssl@1.1` because GitHub Action `macOS` image does not ship `openssl` recently.
GitHub changed its `openssl` install version.
- [[MacOS] Do not install latest OpenSSL](https://github.com/actions/virtual-environments/pull/4154)
- [Updating readme file for macOS-10.15 version 20210927.1](https://github.com/actions/virtual-environments/commit/3198af0e94db478c4529106e3835ce27b43153e4#diff-7a1606bd717fc0cf55f9419157117d9ca306f91bd2fdfc294720687d7be1b2c7R85)
Pass the GitHub Action.

ORC-1016: Use `openssl@1.1` in GitHub Action MacOS CIs

---

java/core/src/java/org/apache/orc/TypeDescription.java
java/core/src/test/org/apache/orc/TestTypeDescription.java
java/tools/pom.xml
java/tools/src/findbugs/exclude.xml
java/tools/src/java/org/apache/orc/tools/ColumnSizes.java
java/tools/src/java/org/apache/orc/tools/Driver.java

This patch adds a new tool that accounts for the total size of a set of ORC files. For files written by >= ORC 1.5, you'll get a column breakdown of the file. There are some virtual columns that are included:
- _index the indexes that are used for skipping inside the stripe
- _data the data in files written prior to ORC 1.5
- _stripe_footer the stripe metadata
- _file_footer the file metadata
- _padding padding added to align stripes to HDFS block boundaries
I also added a new method on TypeDescription that gets the full field name, which is the inverse of findSubtype.
The tool helps diagnose the compression of a set of files.
I added a test of the new TypeDescription.getFullFieldName. I ran the tool over some of the examples and some multiple-terabyte directories of production ORC files.

ORC-1017: Add sizes tool to determine and display the sizes of each column in a set of files.

---

java/bench/pom.xml

This PR aims to remove redundant jackson dependencies.
Unfortunately, ORC-946 forgot to remove the bench dependency on jackson. In fact, the bench module does not directly depend on jackson, only spark indirectly depends on the specified version of jackson. 
Minimising dependencies.
Pass the CIs.
Closes #928

ORC-1019: Remove redundant jackson dependencies

---

docker/debian11/Dockerfile
docker/os-list.txt

This PR aims to add Debian 11 docker test.
To improve test coverage.
Manual, pass the docker tests.
Currently, there is only one C++ test case failure, which is ORC-1041.
```
[  PASSED  ] 402 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestDecompression.testLzoLong
```

ORC-1040: Add Debian 11 docker test

---

c++/test/TestMurmur3.cc

This PR aims to fix a C++ compilation error in CentOS 7.
To recover compilation. 
Manually test on CentOS 7.

ORC-1043: Fix C++ compilation error in CentOS 7

---

c++/src/RLEv2.hh
c++/src/RleDecoderV2.cc
c++/test/TestRleDecoder.cc

This PR optimizes the C++ implementation of orc::RleDecoderV2::nextDirect. It provides different methods for different bit sizes, which significantly reduces the instructions and branches. Note that only bit sizes of 4,8,16,24,32,40,48,56,64 are optimized in this PR. bitSize 1 and 2 are skipped since they usually have short runs which won't benefit from loop unrolling. Other deprecated bit sizes, e.g. 3,5,6,7 are also skipped.
When the bit size is specified, we can better exhaust the buffer before calling readByte(). This also improves performance.
Perf tests show that orc::RleDecoderV2::nextDirect() dominant the time in reading random integers. There are more details in the JIRA description.
Performance improvement for scanning 1 billion unsigned numbers in different bit sizes:
bitSize | …

ORC-1020: [C++] Optimize RleDecoderV2::nextDirect base on bit sizes

---

c++/src/LzoDecompressor.cc

This pr is aimed to fix the implementation of copy data blocks during LZO decompression.
`*reinterpret_cast< int64_t*>(output) = *reinterpret_cast< int64_t*>(matchAddress);`  can lead to unexpected behavior, and in failed test cases it does not appear to be an atomic operation.
This pr uses memcpy instead of the above statement.
Here are the performance benchmarks, where `memcpy` is basically the same as `reinterpret_cast` + `assignment`.  The newer compilers outperform unfolded assignment, so here is a screenshot of the results with only some of the parameters, which you can reproduce with the following test code at https://quick-bench.com/
```c++
#include <string.h>
static void use_memcpy(benchmark::State& state) {
auto size = state.range(0);
char buf[size];
for (int i = 0; i < 8; ++i) …
```

ORC-1041: Use `memcpy` during LZO decompression

---

c++/src/TypeImpl.cc
c++/src/TypeImpl.hh
c++/test/TestType.cc
c++/test/TestWriter.cc

Improve parsing schema string with `Type::buildTypeFromString` to handle quoted field names and have stricter validations.
The current implementation cannot handle quoted field names and allows parsing string schemas that the Java implementation would reject (e.g. `struct<bigint>`, `map(boolean,float)`). It also cannot parse schema with `timestamp with local time zone` in the root.
Ran the existing test suites locally with the newly added tests for quoted field names and invalid schemas.

ORC-1047: Handle quoted field names during string schema parsing

---

java/bench/pom.xml
java/bench/spark/pom.xml

This PR aims to update the transitive dependencies of Spark 3.2.0.
- aircompressor: 0.16 -> 0.21
- Netty-all: 4.1.67.Final -> 4.1.68.Final
- scala-librari: 2.12.10 -> 2.12.15
- spark.jackson.version: 2.10.0 -> 2.12.3
When ORC-1037 updates to Spark 3.2.0, these dependencies are missed.
Pass the CIs.

ORC-1051: Update benchmark dependencies

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/mapreduce/src/test/org/apache/orc/mapred/TestOrcFileEvolution.java

When trying to bump Apache Hive to 1.7 I noticed query failures related to SArgs pushdown.
In more detail, Hive may push Partition column filters that are not part of the columns, until 1.6 recently these columns were ignored, while 1.7 throws IllegalArgumentException. 
Align findColumns behaviour between 1.6 and 1.7 release
Existing tests

ORC-1059: Align findColumns behaviour between 1.6 and 1.7 release

---

java/core/src/java/org/apache/orc/impl/TreeReaderFactory.java

In old code, when dictionary string encoding columns are read by vectorized reading, 2 copy of current stripe's dictionary data and 1 copy of next stripe's dictionary data are hold in memory when reading across different stripes. That could make vectorized reading's memory usage is larger than row reading. This patch fixes this issue, and only hold 1 copy of current stripe's dictionary data.
This patch logic has 3 parts:
1) Directly read data to primitive byte array, rather than using DynamicByteArray as intermediate variable. Using DynamicByteArray as intermediate variable causes 2 copy of current stripe's dictionary data are hold in memory.
2) Lazy read dictionary data until read current batch data. In previous code, RecordReaderImpl class's nextBatch method reads dictionary data of …

ORC-1060: Reduce memory usage when vectorized reading dictionary string encoding columns

---

cmake_modules/ThirdpartyToolchain.cmake

Upgrade zstd in the C++ library to version 1.5.1.
This version is primarily a maintenance release that contains a variety of small bug fixes and improvements to the testing process. It also includes small performance improvements (~3-5%) at the fast compression levels. The release notes are here:
https://github.com/facebook/zstd/releases/tag/v1.5.1
Builds and passes CIs.

ORC-1067: Upgrade ZSTD to 1.5.1

---

java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/test/org/apache/orc/impl/TestReaderImpl.java

Use buffer limit as `readSize` to avoid `IndexOutOfBoundsException`.
**main**
https://github.com/apache/orc/blob/3a2cb60e4ab6af6305c351fbdb51b98f460f64a0/java/core/src/java/org/apache/orc/impl/ReaderImpl.java#L720-L725
**branch-1.5**
https://github.com/apache/orc/blob/5f88704d9bd36fc55b57a60c2fbbd35980b1b7e5/java/core/src/java/org/apache/orc/impl/ReaderImpl.java#L487-L490
ORC-251 remove `ReaderImpl.extractFileTail`  
ORC-685 Add `ReaderImpl.extractFileTail` back  
In ORC-685, file length is used as readsize, which causes that if the buffer is read from the cache, the use of length is incorrect, resulting in IndexOutOfBoundsException.
```
long readSize = fileLen != -1? fileLen: buffer.limit();
int psLen = buffer.get((int) (readSize-1)) & 0xff; 
```
```
Caused by: …
```

ORC-1065: Fix IndexOutOfBoundsException in ReaderImpl.extractFileTail 

---

c++/src/CMakeLists.txt

On my machine (Ubuntu Focal 20.04.3, libc6=2.31-0ubuntu9.2, tzdata=2021e-0ubuntu0.20.04) the following results are returned by strptime:
```
time2037.tm_hour = 13; // weird
time2038.tm_hour = 12; // correct
```
This results in time difference 31532400 (which is 3600 less than expected). Some other configurations give the expected result, thus making the build variable to flap during sequential builds on different systems.
Since this is just a basic test, I suggest relaxing it a bit in order to make it stable.

ORC-1068: [C++] Stabilize HAS_POST_2038 test

---

site/Dockerfile

This PR aims to upgrade the `site` docker image to use Ubuntu 20.04
To migrate to the latest OS. 
Manually.

ORC-1070: Upgrade site docker image to use Ubuntu 20.04

---

.github/workflows/build_and_test.yml

This PR aims to add a test coverage for Windows on GitHub Action additionally.
This PR aims to replace `AppVeyor` with GitHub Action eventually.
**AS IS(AppVeyor)**
https://github.com/apache/orc/blob/ae660f3006cae145d0db7a897fd81fe94029c0b2/appveyor.yml#L18-L41
**THIS PR(GitHub Action)**
https://github.com/apache/orc/runs/4662857757?check_suite_focus=true
```
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- compiler MSVC version 19.0.24245.0
...
Test project D:/a/orc/orc/build
Start 1: orc-test
1/1 Test #1: orc-test .........................   Passed   61.99 sec
```
Pass the GitHub Action with newly add Windows job.

ORC-875: Add GitHub Action job for Windows Server 2019

---

site/_docs/adopters.md

This PR aims to update the [adopters page](https://orc.apache.org/docs/adopters.html). 
To make it up-to-date. 

ORC-1071: Update adopters page

---

.github/workflows/stale.yml

This PR aims to add a new GitHub Action job, `Stale`.
This will help the maintenance of the PRs with `days-before-stale=365` (1 year).

ORC-1072: Add 'Stale' GitHub Action job

---

README.md

This PR aims to remove `Travis PR Builder Link` from `README.md` because it's misleading. Our main PR builder is GitHub Action which runs majority of tests. In addition, https://github.com/apache/orc/pulls is the correct link to show both PR builders' status.
To make `README.md` up-to-date.
Since this is a doc change, manual review.

ORC-1076: Remove Travis PR Builder Link from README.md

---

java/mapreduce/pom.xml
java/mapreduce/src/java/org/apache/orc/mapred/OrcInputFormat.java
java/pom.xml

This PR aims to remove `commons-codec` dependency and use `java.util.Base64`.
Java version is faster and we can minimize our dependency.
- http://java-performance.info/base64-encoding-and-decoding-performance/
Pass the CIs.

ORC-1077: Remove commons-codec dependency and use java.util.Base64

---

.github/workflows/build_and_test.yml

Apache ORC uses `Docker`-based tests to provide `GNU C++` test coverage on `CentOS 7/8`, `Debian 9/10/11`, `Ubuntu 18/20`.
- https://github.com/apache/orc/tree/main/docker
This PR aims to add a new GitHub Action job for `Linux Clang 11.0.0`(Ubuntu) test coverage. Previously, `Clang 7.0.0` test coverage was provided by Travis CI.
**BEFORE (GitHub Action)**
| OS | CXX |
|----|------|
| Ubuntu 20.04 | GNU 9.3.0 |
| MacOS 10.15 | AppleClang 12.0.0 |
| MacOS 11.6 | AppleClang 13.0.0 |
| Windows Server 2019 | MSVC 19.0.24245.0 |
**AFTER (GitHub Action)**
| OS | CXX |
|----|------|
| Ubuntu 20.04 | GNU 9.3.0 |
| **Ubuntu 20.04** | **Clang 11.0.0** |
| MacOS 10.15 | AppleClang 12.0.0 |
| MacOS 11.6 | AppleClang 13.0.0 |
| Windows Server 2019 | MSVC 19.0.24245.0 |
After adding this, we can remove …

ORC-1079: Add `Linux Clang 11` GitHub Action test coverage

---

c++/src/sargs/SearchArgument.cc

This PR fixes the heap-use-after-free issue in `SearchArgumentBuilderImpl::end()`. `std::deque::pop_front` will delete the element. We should call it after using the element.
This crashes the test when building ORC with AddressSanitizer. The ASAN report is attached in the JIRA.
After this fix, I'm able to run all existing tests with AddressSanitizer enabled.

ORC-1081: Fix heap-use-after-free in SearchArgumentBuilderImpl::end()

---

.github/workflows/build_and_test.yml

This PR aims to add a test coverage for Windows on GitHub Action additionally.
This PR aims to replace `AppVeyor` with GitHub Action eventually.
**AS IS(AppVeyor)**
https://github.com/apache/orc/blob/ae660f3006cae145d0db7a897fd81fe94029c0b2/appveyor.yml#L18-L41
**THIS PR(GitHub Action)**
https://github.com/apache/orc/runs/4662857757?check_suite_focus=true
```
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- compiler MSVC version 19.0.24245.0
...
Test project D:/a/orc/orc/build
Start 1: orc-test
1/1 Test #1: orc-test .........................   Passed   61.99 sec
```
Pass the GitHub Action with newly add Windows job.

ORC-875: Add GitHub Action job for Windows Server 2019 (#872)

---

java/tools/src/java/org/apache/orc/tools/FileDump.java
java/tools/src/java/org/apache/orc/tools/JsonFileDump.java

This pr is aims to fixing code in the FileDump and JsonFileDump commands that determines whether a column statistic exists or not.
Before we can get the ColumnStatistics from RowIndex we need to determine whether it exists or not.
`entry.getStatistics()` does not return null at any time, and will return a default object when it is not set.
The current impl is wrong
```java
OrcProto.ColumnStatistics colStats = entry.getStatistics();
if (colStats == null) {
buf.append("no stats at ");
}
```
This can be tested with the following code
```java
@Test
public void test() {
OrcProto.RowIndexEntry entry = OrcProto.RowIndexEntry.newBuilder().addPositions(0).build();
assertFalse(entry.hasStatistics());
assertNotNull(entry.getStatistics());
}
```
But since this is just testing Protobuf generated code, …

ORC-1082: Improve `FileDump` and `JsonFileDump` to be robust on missing column statistics

---

java/core/src/test/org/apache/orc/TestSelectedVector.java

This pr aims to add test cases specifically to check that writers support the selected vector feature.
`testWriteBaseTypeUseSelectedVector`: For covering base types.
`testWriteComplexTypeUseSelectedVector`: For covering multiple nested types.
`testWriteRepeatedUseSelectedVector`: For covering repeated values.
`testWriteEncryptionUseSelectedVector`:  For covering field encryption.
Test the idea that the value written to one field is associated with the row number and that the other fields are obtained by some transformation of the value of this field. The feature is guaranteed to be correct by checking the selected row number against the read result.
Enrich test cases to ensure robustness of feature.
Pass the commit test cases. Currently marked as disabled first until …

ORC-1089: Add test cases verifying writers with selected vector

---

site/develop/index.md

This PR aims to add `Tests` section at Apache ORC `develop` web page.
To help review process.
Manually because this is a doc-only change.

ORC-1091: Add `Tests` section at ORC `develop` page

---

java/core/src/java/org/apache/orc/impl/WriterImpl.java
java/core/src/test/org/apache/orc/TestSelectedVector.java

This PR is to enable the Java ORC writer to respect the selection vector from VectorizedRowBatch. The implementation tries to find each longest batch that is continuously selected to get the best performance.
Currently the ORC writer doesn't support the selected vector. This could cause clients that expect it to be supported to get trash rows in the output.
Enabled UT TestSelectedVector.java

ORC-1004: Java ORC writer supports the selection vector

---

docker/run-one.sh

This PR aims to remove `debian8` specific code in `run-one.sh`
ORC removed `debian8` support already. 

ORC-1093: Remove `debian8` specific code in `run-one.sh`

---

.asf.yaml

This PR aims to enable the GitHub issues tab for ORC. 
To remove the hurdle of creating a Jira ID to report an issue. 
N/A.

ORC-1094: Enable GitHub issues tab

---

java/core/src/java/org/apache/orc/UnknownFormatException.java
java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

This PR aims to deprecate `UnknownFormatException` at Apache ORC 1.7.3.
This extends `IOException` to expose more data and used once here. However, the downstream projects are not using this information because `checkOrcVersion` returns `IOException`.  The error message is enough.
https://github.com/apache/orc/blob/80b98126cf8a15d9d44c67a9aabfabfdcc7f913e/java/core/src/java/org/apache/orc/impl/ReaderImpl.java#L517-L525
This PR replaces it with `IOException` with the same message generated by `UnknownFormatException` previously.
https://github.com/apache/orc/blob/80b98126cf8a15d9d44c67a9aabfabfdcc7f913e/java/core/src/java/org/apache/orc/UnknownFormatException.java#L33-L35
Pass the CIs.

ORC-1095: Deprecate `UnknownFormatException`

---

c++/src/Reader.cc
site/_docs/cpp-tools.md
tools/src/CMakeLists.txt
tools/src/FileContents.cc
tools/src/FileMemory.cc
tools/src/FileScan.cc
tools/src/ToolsHelper.cc
tools/src/ToolsHelper.hh
tools/test/TestFileContents.cc
tools/test/TestFileScan.cc

This is a follow-up task of #921. Currently we have options for the tools to work on specified top-level column fields. However, ACID ORC files usually have nested structure. We need the type ids to specify nested columns. As an extension, adding support for column names will also be helpful. So we don't need to manually convert column names to type ids. Also reports the valid values when an invalid column name is given.
This PR extracts the option parsing codes into ToolsHelper. So similiar cpp tools can share the same option set.
It makes the tools more useful in practice.
Added unit tests for the new options.

ORC-1098: [C++] Support specifying type ids or column names in cpp tools

---

c++/src/TypeImpl.cc
c++/test/TestType.cc

The changes are made to validate the indices in the Protobuf message type tree especially for the Type_Kind_STRUCT when fieldnames are less than the subtypes_size() , so it won't crash when we convert the proto::Types to TypeImpls.
To handle the malformed STRUCT type more gracefully.
Pass the CIs with the newly added test coverage.
Closes #1021 and #1023

ORC-1101: [C++] Improve malformed STRUCT handling

---

README.md
java/pom.xml

This PR aims to use Apache Maven 3.8.4 for Java building and testing.
- Apache Maven 3.6.3 was released on 2019-11-25.
- Apache Maven 3.8.x has the latest fixes including CVE patches.
https://maven.apache.org/docs/history.html
Pass the CIs.

ORC-1103: Use Maven 3.8.4

---

README.md

This PR aims to update `README.md` by
- Removing `Travis CI` link
- Adding `release tags` link and `plan` link.
To make release information more visible.
Manually check the new README in the following link.
- https://github.com/apache/orc/blob/39680343ef9a4bb3b90268ebdda6f93016e668c8/README.md

MINOR: Update `README.md` to remove `Travis CI` links and add release tags and plan

---

java/bench/pom.xml

This PR aims to use Spark 3.2.1 in benchmark. 
To make benchmark up-to-date. 
N/A.

ORC-1104: Use Spark 3.2.1 in benchmark

---

java/bench/fetch-data.sh

This PR aims to use zsh in `fetch-data.sh` instead of bash. 
`bash` has a different behavior in `MacOS` environment. `zsh` works like Linux bash.
```
$ bash -c "echo {01..15}"
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
$ zsh -c "echo {01..15}"
01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
$ docker run -it --rm ubuntu bash -c 'echo {01..15}'
01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
```
Manually test by running `fetch-data.sh` on MacOS.

ORC-1105: fetch-data.sh should use zsh instead of bash

---

java/bench/pom.xml

This PR aims to use transitive `commons-lang3` dependency in `bench` module. 
Hadoop 3.3 and Spark 3.2 are using `commons-lang3` 3.12.0
Manually check with 
```
mvn dependency:tree
```

ORC-1106: Use transitive commons-lang3 dependency in bench module

---

java/bench/core/src/java/org/apache/orc/bench/core/Utilities.java

This PR aims to fix a NPE at benchmark data schema loading.
**BEFORE**
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar scan data -d taxy -c zstd
Exception in thread "main" java.lang.NullPointerException
at org.apache.orc.bench.core.Utilities.loadSchema(Utilities.java:37)
at org.apache.orc.bench.core.convert.ScanVariants.run(ScanVariants.java:78)
at org.apache.orc.bench.core.Driver.main(Driver.java:64)
```
**AFTER**
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar scan data -d taxy -c zstd
Exception in thread "main" java.lang.IllegalArgumentException: Schema Not Found: taxy.schema
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
at org.apache.orc.bench.core.Utilities.loadSchema(Utilities.java:37)
at …
```

ORC-1107: Fix NPE at benchmark data schema loading

---

java/bench/core/src/java/org/apache/orc/bench/core/convert/GenerateVariants.java

This PR aims to use `RawLocalFileSystem` to skip checksum files during benchmark data generation. 
There is no need to check for checksums. 
Manually.

ORC-1108: Use `RawLocalFileSystem` to skip checksum files during benchmark data generation

---

java/bench/core/src/java/org/apache/orc/bench/core/convert/GenerateVariants.java
java/bench/core/src/java/org/apache/orc/bench/core/convert/ScanVariants.java

This PR aims to use `zstd` instead of `none` in the default compress option.
This will reduce the hardware requirements for running benchmark. 
```
$ du -h * | sort -nr
112G	github
67G	sales
21G	taxi
```
```
$ du -h */*none | sort -nr
663M	taxi/parquet.none
28G	github/json.none
22G	sales/json.none
18G	github/avro.none
14G	github/parquet.none
12G	github/orc.none
10G	taxi/json.none
4.9G	sales/avro.none
4.2G	sales/parquet.none
2.9G	sales/orc.none
2.0G	taxi/avro.none
1.2G	taxi/orc.none
```
Manually generate benchmark data.

ORC-1109: Use zstd instead of none in the default compress option

---

.github/dependabot.yml

This PR aims to update the pinning version of Scala library to `[2.12.16, )`.
Apache Spark 3.2+ is using Scala 2.12.15.
N/A

MINOR: Update scala-library pinning version to `[2.12.16, )`

---

site/_data/docs.yml
site/_docs/pyarrow.md
site/index.html

This PR aims to add `Using with Python` web page to Apache ORC website for the community Python users.
To help Python users to use `Apache Arrow` project more with latest `Apache ORC 1.7.x C++` release.
Build the doc and check generated website. The embedded code can be test with `PyArrow 6.0.1 (latest)` and will be improved at `PyArrow 7.0` via [ARROW-15338: [Python] Add pyarrow.orc.read_table API](https://github.com/apache/arrow/commit/ff4b9bea56aeb2c48f19d6137dd2fbae59d618c7)
This closes #1027

ORC-1112: Add `Using with Python` web page

---

site/_docs/pyarrow.md

This PR aims to update `Using with Python` page with new PyArrow 7.0.0 API.
- https://pypi.org/project/pyarrow/7.0.0/
New APIs are more convenient.

ORC-1114: Update `Using with Python` page with `PyArrow` 7.0.0

---

java/pom.xml

This PR aims to add `--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED` for testings.
This will suppress the following Hadoop 2 logs during testing with Java 9+.
```
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/root/.m2/repository/org/apache/hadoop/hadoop-auth/2.2.0/hadoop-auth-2.2.0.jar) to method sun.security.krb5.Config.getInstance()
[ERROR] WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a …
```

ORC-1115: Suppress `Illegal reflective access` warnings on Java9+ Tests

---

java/tools/src/java/org/apache/orc/tools/convert/ConvertTool.java
java/tools/src/java/org/apache/orc/tools/convert/JsonReader.java
java/tools/src/test/org/apache/orc/tools/convert/TestJsonReader.java

This patch add support to convert json to UNION type in orc file. For
example, for schema `struct<foo:uniontype<int,string>>`, the following
json lines can be parsed into UNION type.
```
{"foo": {"tag": 0, "value": 1}}
{"foo": {"tag": 1, "value": "testing"}}
{"foo": {"tag": 0, "value": 3}}
```
This add a missing support for UNION type in java convert tool.
Manually test against handcrafted json file.

ORC-236: Support `UNION` type in Java Convert tool

---

site/_data/docs.yml
site/_docs/dask.md
site/index.html

This PR aims to add `Dask` page under `Using in Python` section.
This helps more users.
Manually generate the page and check.

ORC-1117: Add `Dask` page at `Using in Python` section

---

tools/src/CSVFileImport.cc
tools/test/TestCSVFileImport.cc

Let each string type columns use its own databuffer before writing data into orc file, so that when one column is calling buffer.resize(), the invalidated buffer.data() is not affecting other columns which points to it.
When using the csv-import tool to export a orc file with schema like "struct<a:string,b:binary>", if the data in column "b" has very long bytes (over 4MB), the process could segmentation fault or the exported data in column "a" could become empty string.
Following the code in CSVFileImport.cc, when writing a orc file, all string type columns is using one databuffer inside function fillStringValues(). If a data length is larger than the buffer, the buffer will be resized. The resize() operation will cause all previous result of buffer.data() become invalid. 
In this case, …

ORC-1116: [C++] Fix csv-import tool when exporting long bytes

---

docker/debian10/Dockerfile
docker/debian11/Dockerfile
docker/ubuntu18/Dockerfile
docker/ubuntu20/Dockerfile

This PR aims two goals:
- Support Java 17 docker test
- Support ARM64 docker test
The current test Dockerfile contains a hardcoded architecture postfix `-amd64` which was broken on ARM64.
Although we only support Apple Silicon so far, this test suite should support ARM64 first.
Manually tested with the build argument in the OS directories on ARM64 machine.
```
docker build -t test --build-arg jdk=17 .
```
Note that `protoc 2.5.0` supports only Intel Architecture and `Apple Silicon` so far. We cannot make the all Docker tests pass on ARM64.

ORC-1118: Support Java 17 and ARM64 docker tests

---

java/pom.xml

This PR removes timestamps from ORC API docs.
This will reduce the diff.
```
<head>
-
+
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Class Hierarchy (ORC Tools 1.7.2 API)</title>
-<meta name="date" content="2021-12-20">
```
Manually check the generated API doc.
```
$ mvn javadoc:javadoc
```

ORC-1119: Remove timestamp from ORC API docs

---

java/core/src/java/org/apache/orc/Writer.java
java/core/src/java/org/apache/orc/impl/WriterImpl.java

Add `estimationMemory` method for writer. It exposes the internal treeWriter to estimate the memory used for the buffer.
This method help the write engine to better control the refresh policy of the ORC.
The source of this issue comes from Iceberg's discussion.
https://lists.apache.org/thread/g6yo7m46mr86ov1vkm9wnmshgw7hcl6b
Pass the CIs

ORC-1123: Add `estimationMemory` method for writer

---

README.md

Delete the content in README.md which states the cpp writer only writes 0.11 version.
Inconsistency between doc and code.
Manually check the README.md file under root directory.

ORC-1120: Remove C++ library limitation about write version

---

site/_posts/2022-03-05-add-quanlong.md

Add a new page in the news to reflect the latest change of committer activity.

Added Quanlong as a committer to site

---

java/core/src/java/org/apache/orc/impl/SchemaEvolution.java
java/core/src/test/org/apache/orc/impl/TestSchemaEvolution.java

Add a map in `SchemaEvolution` which contains the mapping from the file column id to the reader column id, the mapping will be used in `SchemaEvolution.isPPDSafeConversion()`
`RecordReaderImpl.pickRowGroups()`  calls `SchemaEvolution.isPPDSafeConversion()` with file column id rather than reader column id which is required, this causes column filters can't work effectively and recordReader can't skip row groups which are not matched, so we need find the corresponding reader column id via file column id to ensure `SchemaEvolution.isPPDSafeConversion()` can work correctly.
UT

ORC-1121: Fix column coversion check bug which causes column filters don't work

---

c++/src/RLEv2.hh
c++/src/RleDecoderV2.cc
c++/src/RleEncoderV2.cc

This PR adds a buffer to decode the whole run at once in RleDecoderV2, which leverages the improvement of ORC-1020 (#944) to deal with null values. It also benifits other encodings like PATCHED_BASE and DELTA, and helps to remove the state variables in RleDecoderV2 to improve the code redability.
This is a follow up task of ORC-1020 which didn't optimize the code path when the column has nulls.
Tested with random unsigned numbers fitting into bitSize n with a given ratio of nulls. Reading 1B rows for each test.
| bitSize | % nulls | baseline avg(s) | optimized avg(s) | Speedup      |
|---------|---------|-----------------|------------------|--------------|
| 4       | 0%      | 3.52            | 2.745            | 1.2823315118 |
| 4       | 5%      | 7.925           | 7.185            | …

ORC-1122: [C++] Add buffer to decode the whole run in RleDecoderV2

---

tools/src/CMakeLists.txt
tools/test/CMakeLists.txt

Make `tool-test` depends on cpp tools so when any of the tool codes change, recompile tool-test will also recompile the tool.
This avoids mistakes when `tool-test` is using the old tool binaries that are inconsistent with the current codes.
Manually tested `make -j8 tool-test` and `make -j8 DESTDIR=./tmp install`

ORC-1129: [C++] Make tool-test depends on cpp tools

---

c++/src/ColumnReader.cc
c++/src/ColumnReader.hh
c++/src/Reader.cc
c++/src/Reader.hh
c++/src/StripeStream.cc
c++/src/StripeStream.hh
c++/test/TestColumnReader.cc
c++/test/TestRleDecoder.cc
tools/test/TestFileContents.cc

This PR adds a reader for decimal64 in ORCv2 (added in ORC-49). Also extends `FileVersion` to recognize the version of "UNSTABLE-PRE-2.0". Decimal columns written in such version will be read using the new reader.
The original reader codes come from #147 
Before this PR, the cpp reader is unable to read decimal columns in ORCv2.
Adds unit tests in TestColumnReader.cc
Adds an end to end test in TestFileContents.cc. 
Unfortunately, I can't find a clean way to generate such ORC files. So this PR introduces a new test file (decimal_v2.orc) generated by Hive.

ORC-1125: [C++] Support reading decimal64 in ORCv2

---

tools/src/CSVFileImport.cc

Fix the option strings passed to getopt_long functions, should be "d:s:c:b:t:h" instead of "s:b:c:p:t:h".
The original option parsing is not dealing with stripe size option '-s' and delimiter option '-d' correctly.
The following command runs successfully:
./csv-import -d ',' -s 1 -b 1024 -c 1024 "struct<a:string>" a a.orc

ORC-1133: [C++] fix csv-import tool command line options not working

---

c++/src/ColumnReader.cc

This PR unrolls the loops inside DoubleColumnReader::readDouble() and readFloat(). Also refactor DoubleColumnReader to be a template class to save some runtime checks.
When running on a little-endian machine, the layout of the DATA stream matches the memory layout of the output double array. We use std::memcpy to copy data as more as we can in reading double columns.
This PR improves the performance in DoubleColumnReader::next(). The screenshot in the JIRA description shows it as a hot path.
Ran a performance test on reading 4 double columns on a file of tpch lineitem table using orc-scan. The file is 264MB with 7,296,488 rows.
I can see #instructions reduce 20% and time elapsed reduce 13%. More details here (collected by perf-stat):
|                   | original   | optimized   | reduce …

ORC-1137: [C++] Unroll loops and copy data directly in DoubleColumnReader::next()

---

java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java
java/core/src/test/org/apache/orc/TestVectorOrcFile.java

This pr is aimed at checking whether the float category statistic sum has a finite value.
When the orc float category is written with NaN, pushing down is not supported.
Added unit test.

ORC-1146: Float category missing check if the statistic sum is a finite value

---

c++/src/ColumnWriter.cc
c++/test/TestTimestampStatistics.cc

Fix converting non UTC timestamps for statistics.
Currently, the statistics for timestamp columns are incorrect, when the writer's time zone is not UTC.
Ran the existing test cases.

ORC-1151: [C++] Fix `ColumnWriter` for non-UTC Timestamp columns

---

c++/src/Reader.cc
c++/src/Reader.hh
c++/src/sargs/SargsApplier.cc
c++/src/sargs/SargsApplier.hh
c++/test/TestReader.cc
c++/test/TestSargsApplier.cc
tools/test/TestFileScan.cc

In case of PPD, SargsApplier mantains a bool vector representing whether a RowGroup is picked after evaluating the SearchArguments. The bool vector is then used in RowReaderImpl::computeBatchSize() to compute the next skipped row id for  the current row range. The computation is done for each batch.
In the worst case, if all RowGroups are picked, computeBatchSize() has to iterate the whole vector starts from the current RowGroup. In practise, a stripe can have thousands of RowGroups. The complexity of iterating the bool vector is comparable to materializing the batch (usually have size as 1024). The perf result in the JIRA description shows that it can take 1/4 of the scan time.
Instead of maintaining the bool vector, we can pre-compute the next skipped row id of the row range that each …

ORC-1150: [C++] Optimize RowReaderImpl::computeBatchSize() by pre-computation

---

c++/src/Reader.cc
c++/test/TestPredicatePushdown.cc

When PPD is enabled, `RowReaderImpl::seekToRow()` only seeks to the start of the next matched row group. It should continue to seek within the selected row group in need.
This PR modifies `seekToRow()` to finish the remaining seek.
Without the fix, `RowReaderImpl::seekToRow()` could seek to a wrong position, leading to wrong results.
Add tests in TestPredicatePushdown.cc

ORC-1160: [C++] Fix seekToRow can't seek within selected row group

---

site/index.html

This will add Apache Event page to the Apache ORC website.
Currently, Apache Project Website Checks show warnings on the Apache ORC website.
https://whimsy.apache.org/site/project/orc
Manually check the generated website.
This closes #1103

ORC-1162: Fix Apache Project Website Checks Warning

---

c++/src/Reader.cc
c++/src/Reader.hh
c++/test/TestPredicatePushdown.cc

This PR fixes a bug introduced by a recent improvement (#1073). When the last stripe is skipped by StartNextStripe(), we should return in RowReaderImpl::next().
This fixes a crash of the C++ client when sargs exist and the last stripe is skipped.
We are lack of test coverage for the above case. Add more tests in TestPredicatePushdown.

ORC-1159: [C++] Fix crash when the last stripe is skipped

---

java/pom.xml

This PR aims to upgrade Hadoop to 3.3.2 on `java17` profile in Apache ORC 1.8.0.
[Apache Hadoop 3.3.2 is the latest version](https://hadoop.apache.org/docs/r3.3.2/index.html) with the following.
- This is the first release to support ARM architectures.
- Upgrade protobuf from 2.5.0 to something newer
- Java 11 runtime support is completed.
- Shaded Guava from thirdparty
Pass the Java 17+ CIs.

ORC-1169: Use Hadoop to 3.3.2 on Java 17+

---

.github/workflows/build_and_test.yml

This PR aims to skip build and test on docker and site updates.
To save community resources from running tests on irrelevant changes. 
Manually verify after merging.

ORC-1171: Skip build and test on docker and site updates

---

.github/workflows/build_and_test.yml
java/pom.xml

This PR aims to add `Ubuntu 22.04` to GitHub Action.
This will help the verification on the latest release.
Although [GitHub Action Virtual Environments](https://github.com/actions/virtual-environments) don't support `Ubuntu 22.04` officially yet, `Ubuntu 22.04` is available as `Public Beta`.
- https://github.com/actions/virtual-environments/issues/5490
Pass the GitHub Action on this PR.

ORC-1174: Add `Ubuntu 22.04` to GitHub Action

---

java/pom.xml

This PR aims to use Hadoop 3.3.3 on Java 17 and above. 
To bring the latest bug fixes. 
Pass the Java 17 CI.

ORC-1178: Use Hadoop 3.3.3 on Java 17+

---

java/pom.xml

This PR aims to upgrade checkstyle to 10.2 on Java 11 and above. 
However, checkstyle 10+ supports only Java 11+, so I created a Java8 profile to keep Java8 support. 
- https://checkstyle.org/releasenotes.html#Release_10.2
- https://checkstyle.org/releasenotes.html#Release_10.1
- https://checkstyle.org/releasenotes.html#Release_10.0
- https://checkstyle.org/releasenotes.html#Release_9.3
Pass the CIs. 
Closes #1123

ORC-1179: Upgrade checkstyle to 10.2 on Java 11+

---

site/_docs/releases.md

This PR aims to update RELEASES page by adding the official ASF release verification link.
- https://orc.apache.org/docs/releases.html
To give more background for the verification procedure.
Manual review because this is a webpage update.

MINOR: Add ASF verification instruction link

---

java/core/src/java/org/apache/orc/OrcConf.java
java/core/src/java/org/apache/orc/OrcFile.java
java/core/src/java/org/apache/orc/impl/WriterImpl.java
java/core/src/test/org/apache/orc/impl/TestWriterImpl.java

add row count limit config "orc.stripe.row.count" to limit row count in one stripe.
for query engine like presto，stripe is the base unit for query concurrency, one stripe can only be processed by one split.
In current implement of orc writer, the only config which can control row count in stripe is the "orc.stripe.size".
But for different kind of table, the row count is difficult to use.
for table with much columns( eg. 100 columns), 64MB may contain 5000 rows.
for table with less columns(eg. 5 columns), 64MB may contain 100000 rows.
for presto, normal olap query only read a subset of table columns, the row count is the key factor of query performance. If one stripe contain much rows, the query performance may become too low.
So, besides the config "orc.stripe.size", we need another …

ORC-1172: Add row count limit config in one stripe

---

java/bench/hive/src/java/org/apache/orc/bench/hive/ColumnProjectionBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/DecimalBench.java
java/bench/hive/src/java/org/apache/orc/bench/hive/FullReadBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/RowFilterProjectionBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/BooleanRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/DecimalRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/DoubleRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/StringRowFilterBenchmark.java
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/TimestampRowFilterBenchmark.java
java/bench/spark/src/java/org/apache/orc/bench/spark/SparkBenchmark.java

This PR aims to use `orc.zstd` as the default data source in the benchmarks.
After ORC-1109, we use `orc.zstd` by default instead of `orc.none`.
**BEFORE**
```
$ git grep 'none"' | grep Benchmark
java/bench/hive/src/java/org/apache/orc/bench/hive/ColumnProjectionBenchmark.java:  @Param({"none", "snappy", "gz"})
java/bench/hive/src/java/org/apache/orc/bench/hive/FullReadBenchmark.java:  @Param({"none", "gz", "snappy"})
java/bench/hive/src/java/org/apache/orc/bench/hive/RowFilterProjectionBenchmark.java:  @Param({"none"})
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/BooleanRowFilterBenchmark.java:    String dataRelativePath = "data/generated/sales/orc.none";
java/bench/hive/src/java/org/apache/orc/bench/hive/rowfilter/DecimalRowFilterBenchmark.java:    String …
```

ORC-1192: Use `orc.zstd` instead of `orc.none`

---

java/pom.xml

This PR aims to upgrade a test dependency, `byte-buddy`, in branch-1.7 to 1.12.13.
To sync with branch-1.8 and main.
Pass the CIs.

ORC-1244: Upgrade `byte-buddy` to 1.12.13 in branch-1.7

---

README.md

This PR aims to add a cmake build version in [README.md](https://github.com/apache/orc/blob/main/README.md)
[add_compile_definitions ](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html)only supprt cmake 3.12+. We can update the docs [README.md](https://github.com/apache/orc/blob/main/README.md)
In ubuntu 18.04:
> sudo apt install cmake
> make ..
we will get an error:
CMake Error at CMakeLists.txt:147 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".

ORC-1278: Update cmake docs version to 3.12

---

c++/src/ByteRLE.cc
c++/src/ColumnReader.cc
c++/src/RLEv1.cc
c++/test/TestByteRle.cc

This patch adds static_cast for the char type cast in RLE/ColumnReader.
For the context of [ORC-1315](https://issues.apache.org/jira/browse/ORC-1315), this patch fixes signed char to unsigned char conversions fail where char is by default unsigned.
No new tests were added.

ORC-1315:[C++] Fix byte to integer conversions fail on platforms with unsigned char type

---

c++/src/ColumnReader.cc
c++/test/TestColumnReader.cc

Previous fix of ORC-1315 is not complete yet. This is a follow up commit to fix the remaining issues where unsigned chars may produce unexpected behavior.
In the debian docker images, several test cases fail like below:
```
[----------] Global test environment tear-down
[==========] 87 tests from 10 test cases ran. (8039 ms total)
[  PASSED  ] 83 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] TestMatch.selectColumns
[  FAILED  ] TestMatchParam/FileParam.Contents/7, where GetParam() = TestOrcFile.testSeek.orc
[  FAILED  ] TestMatchParam/FileParam.Contents/18, where GetParam() = nulls-at-end-snappy.orc
[  FAILED  ] TestMatchParam/FileParam.Contents/23, where GetParam() = over1k_bloom.orc
```
- Add `-funsigned-char` flag to compile manually to make sure all tests pass.
- All test …

ORC-1315: [C++] Fix test failure when unsigned char is in effect

---

.github/workflows/build_and_test.yml

This PR aims to use Java 19 instead of Java 18 in GHA testing.
Java 19 is the latest version. 
Pass the new CIs.

ORC-1324: Use Java 19 instead of 18 in GHA

---

cmake_modules/ThirdpartyToolchain.cmake
docker/centos7/Dockerfile
docker/run-one.sh

Upgrade centos7 docker image to use gcc9 instead of gcc4. After this change, the C++ build on centos7 is fully recovered.
ORC-1301 recently enabled C++17 to the C++ code base and build on centos7 fails like the following.
```
CMake Error at CMakeLists.txt:134 (message):
A c++17-compliant compiler is required, please use at least GCC 5
-- compiler GNU version 4.8.5
-- Configuring incomplete, errors occurred!
See also "/root/build/CMakeFiles/CMakeOutput.log".
FAILED centos7
```
Test it manually that all tests pass.

ORC-1322: Upgrade centos7 docker image to use gcc 9

---

c++/src/Timezone.cc

timezone file might be hundreds or thousands of bytes, pass references of byte vector should be more efficient.
so change `TimezoneImpl(const std::string& name, const std::vector<unsigned char> bytes)` to
`TimezoneImpl(const std::string& name, const std::vector<unsigned char>& bytes)`.
this can reduce vector copy so improve performance.
It doesn't introduce new features and passed all test cases.

ORC-1348: [C++] TimezoneImpl constructor should pass vector ref

---

.github/workflows/build_and_test.yml
.github/workflows/publish_snapshot.yml

This PR aims to upgrade `setup-java` from `v1` to `v3`. `v3` has two breaking changes.
1. JDK distribution field is required
2. `1.8` is not accepted. We need to use `8` instead.
Currently, we are using `v1` which is too old and shows warnings like the following.
- https://github.com/apache/orc/actions/runs/3871285820/jobs/6598946894
```
Warning: The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
The latest one is v3.9.0. We will use it.
- https://github.com/actions/setup-java/releases/tag/v3.9.0
Note that Node.js is upgraded since v3.0.
https://github.com/actions/setup-java/releases/tag/v3.0.0
> In …

ORC-1350: Upgrade `setup-java` to v3

---

.github/dependabot.yml

This PR aims to pin `Mockito` to 4.x.
5.x is a major version change which is incompatible. We can revisit this later.
Closes #1381

ORC-1360: Pin `mockito` to 4.x

---

.github/dependabot.yml

This PR pins `spotless` to 2.30.0.
`spotless` dropped Java 8 support at 2.31.0.
- https://github.com/diffplug/spotless/pull/1514
- #1392
Manual review.

ORC-1364: Pin `spotless` to 2.30.0

---

java/core/src/java/org/apache/orc/impl/ReaderImpl.java
java/core/src/test/org/apache/orc/TestOrcWithLargeStripeStatistics.java

Catch `InvalidProtocolBufferException` when parsing stripe statistics, log a warning message, and return an empty list.
In some cases ORC files may be created with very large Metadata section due to stripe statistics. The bigger the ORC file gets the easier is to endup with a large Metadata section. Nevertheless, it is still possible to hit the problem with smaller ORC files and `TestOrcWithLargeStripeStatistics` demonstrates some extremes.
Any attempt to read back the stripe statistics from the file will fail with `InvalidProtocolBufferException`. The exact exception may differ slighly and depending on: a) the size of stripe statistics; b) protobuf size limit.
Stripe statistics less than 2GB, and protobuf limit less than stats size:
```
com.google.protobuf.InvalidProtocolBufferException: …
```

ORC-1361: InvalidProtocolBufferException when reading large stripe statistics

---

java/bench/pom.xml
java/core/pom.xml
java/examples/pom.xml
java/pom.xml
java/tools/pom.xml

This PR aims to optimize logging dependency definition.
Here are the changes:
1. Add slf4j-simple as the logging implementation for SLF4J in example module to remove warnings:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```
2. Exclude log4j from hadoop dependencies to remove warnings in example module:
```
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
3. Set slf4j-simple to runtime scope to avoid accidentally binding ORC
project to a single logging implementation.
4. Remove …

ORC-1378: [Java] Optimize logging dependency definition

---

c++/include/orc/Exceptions.hh
c++/include/orc/Type.hh
c++/src/CMakeLists.txt
c++/src/Exceptions.cc
c++/src/Reader.cc
c++/src/Reader.hh
c++/src/SchemaEvolution.cc
c++/src/SchemaEvolution.hh
c++/src/TypeImpl.cc
c++/src/TypeImpl.hh
c++/src/sargs/SargsApplier.cc
c++/src/sargs/SargsApplier.hh
c++/test/TestSargsApplier.cc

Add schema evolution and check PPD security
This pr adds a class `schema evolution` which checks validity and  PDD security of a type conversion. The convertions would be finished later.
To support schema evolution in c++
UT

ORC-1376: [C++] Scaffolding of schema evolution

---

c++/src/SchemaEvolution.cc
c++/src/SchemaEvolution.hh

Add Apache 2.0 License to the SchemaEvolution.hh and SchemaEvolution.cc
The prior patch forgot it.
have no need

ORC-1376: [C++] Add Apache 2.0 License to the new file

---

c++/src/ColumnReader.cc
c++/src/ColumnWriter.cc
c++/src/TypeImpl.cc
c++/test/TestWriter.cc

Return LongVectorBatch when create a RowBatch for BOOLEAN type with useTightNumericVector option, instead of ByteVectorBatch.
If a ByteVectorBatch is returned, BooleanColumnReader/Writer would crash because they only accept LongVectorBatch.
no test

ORC-1399 [C++] Return LongVectorBatch when createRowBatch for boolean type with useTightNumericVector option

---

c++/include/orc/Reader.hh
c++/include/orc/Vector.hh
c++/src/CMakeLists.txt
c++/src/ColumnReader.cc
c++/src/ColumnReader.hh
c++/src/ConvertColumnReader.cc
c++/src/ConvertColumnReader.hh
c++/src/Options.hh
c++/src/Reader.cc
c++/src/Reader.hh
c++/src/SchemaEvolution.cc
c++/src/StripeStream.cc
c++/src/StripeStream.hh
c++/src/TypeImpl.cc
c++/test/CMakeLists.txt
c++/test/MockStripeStreams.cc
c++/test/MockStripeStreams.hh
c++/test/TestColumnReader.cc
c++/test/TestConvertColumnReader.cc
c++/test/TestSchemaEvolution.cc

support schema evolution converting between types within {boolean, tinyint, smallint, int, bigint, float, double}
To support shecma evolution in c++
UT passed

ORC-1385: [C++] Support schema evolution of numeric types

---

cmake_modules/ThirdpartyToolchain.cmake

Upgrade zstd to v1.5.5 for the C++ library.
The most recent release of zstd has fixed a rare corruption bug and brings some speed improvements.
see also https://github.com/facebook/zstd/releases/tag/v1.5.5
All UT passed

ORC-1410: [C++] Bump zstd to v1.5.5

---

c++/include/orc/OrcFile.hh
c++/include/orc/Writer.hh
c++/src/OrcFile.cc
c++/src/Writer.cc
c++/test/MemoryOutputStream.hh
c++/test/TestWriter.cc

Current C++ code base does not support writing intermediate footers as Java code base does.
It would be beneficial to the C++ based writers to have an ability to write intermediate footer(s) to the opened file while streaming data into it. The benefit is not losing the so far persisted data (after flushing stripes) in case of writer failure in closing the file (application crash).
The writer that wants to support the feature would follow similar approach as Hive does in writing a side file with the latest footer offsets. The reader would be able to determine the location of the last valid footer by using the last footer location from the side file (instead of assuming that the footer is at the end of the file).
The change was tested by creating a small ORC file writer test application …

ORC-1401: [C++] allow writing an intermediate footer

---

c++/src/ByteRLE.cc
c++/src/RLEv1.cc
c++/src/RLEv1.hh
c++/test/TestByteRle.cc
c++/test/TestReader.cc
c++/test/TestRleDecoder.cc

This backports ORC-1304 (#1299) to branch-1.8. Resolved some conflicts due to ReaderMetrics not supported in branch-1.8.
The bug of ORC-1304 also occurs on branch-1.8
Ran orc-test

ORC-1304: [C++] Fix seeking over empty PRESENT stream

---

CMakeLists.txt
c++/src/CpuInfoUtil.cc
c++/src/CpuInfoUtil.hh

To fix a bug reported in https://github.com/apache/orc/issues/1534
The bug is that some CpuInfoUtil.cc functions don't support the ARM platform. In this PR, try to fix this bug.
Currently, ORC can't build success on the ARM platform without this PR.
We can build ORC on the ARM platform directly to check if it can succeed.
If user enabled -DBUILD_ENABLE_AVX512=ON in the cmake process, it will get the below warning message, and BUILD_ENABLE_AVX512 will be changed back to OFF.
CMake Warning at CMakeLists.txt:183 (message):
Only X86 platform support AVX512

ORC-1447: [C++] Fix a bug in CpuInfoUtil.cc to support ARM platform

---

c++/src/CpuInfoUtil.cc

Move UNUSED macro under the definition of CPUINFO_ARCH_X86 in order to avoid unused macro error.
Without this patch, the C++ build fails on MacOS and other non-x86 machines.
It builds successfully and passes all tests on my laptop.

ORC-1455: [C++] Fix build with unused macro in CpuInfoUtil.cc

---

c++/test/TestConvertColumnReader.cc

Fix the failure of ConvertColumnReader.TestConvertNumericToStringVariant when char is unsigned.
The UT fails when compiled with unsigned char.
The UT is passed when compiled both with and without the flag -funsigned-char.

ORC-1475: [C++] ConvertColumnReader.TestConvertNumericToStringVariant fails when compiled with unsigned char

---

c++/test/TestConvertColumnReader.cc

Fix the failure of ConvertColumnReader.TestConvertNumericToStringVariant when char is unsigned.
The UT fails when compiled with unsigned char.
The UT is passed when compiled both with and without the flag -funsigned-char.

ORC-1475: [C++] ConvertColumnReader.TestConvertNumericToStringVariant fails when compiled with unsigned char 

---

README.md

This is a minor PR to replace `http://` with `https://` in `README.md`.
HTTPS is a recommended safe way.
Manual review.

MINOR: Use `https` in README.md
